mbta/screens

- assets/css/v2.scss
- assets/css/v2/flex/one_large.scss
- assets/css/v2/flex/one_medium_two_small.scss
- assets/css/v2/flex/two_medium.scss
- assets/css/v2/screen/normal.scss
- assets/css/v2/screen/takeover.scss
- assets/css/v2/screen_container.scss
- assets/src/components/v2/flex/one_large.tsx
- assets/src/components/v2/flex/one_medium_two_small.tsx
- assets/src/components/v2/flex/two_medium.tsx
- assets/src/components/v2/screen/normal.tsx
- assets/src/components/v2/screen/takeover.tsx
- assets/src/components/v2/widget.tsx
**Asana task**: [Container components](https://app.asana.com/0/1185117109217413/1200023663996429)
This PR defines components for the screens and flex zones.
> feat: widget front-end container components

- assets/css/v2.scss
- assets/css/v2/footer/normal.scss
- assets/src/components/v2/footer/normal.tsx
- assets/src/components/v2/widget.tsx
**Asana task**: [normal footer](https://app.asana.com/0/1185117109217413/1199987812749007/f)
> feat: Normal footer widget

- assets/css/v2.scss
- assets/css/v2/departures/no_data.scss
- assets/css/v2/departures/normal.scss
- assets/src/components/v2/departures/no_data.tsx
- assets/src/components/v2/departures/normal.tsx
- assets/src/components/v2/widget.tsx
- lib/screens/v2/widget_instance/departures.ex
- test/screens/v2/widget_instance/departures_test.exs
**Asana tasks**:
-  [departures](https://app.asana.com/0/1185117109217413/1199987812749003)
-  [departures no data](https://app.asana.com/0/1185117109217413/1199987812749019)
Define components `Departures` and `DeparturesNoData`.
> feat: NormalDepartures and NoDataDepartures widgets

- assets/src/components/dup/departure.tsx
- assets/src/components/dup/section.tsx
- assets/src/components/solari/departure.tsx
- assets/src/components/solari/route_pill.tsx
- assets/src/components/solari/section.tsx
- lib/screens/audio.ex
- lib/screens/config/dup/section.ex
- lib/screens/config/query/params.ex
- lib/screens/departures/departure.ex
- lib/screens/dup_screen_data/request.ex
- lib/screens/predictions/parser.ex
- lib/screens/predictions/prediction.ex
- lib/screens/route_type.ex
- lib/screens/schedules/parser.ex
- lib/screens/schedules/schedule.ex
- lib/screens_web/templates/audio/_bus_route.ssml.eex
- lib/screens_web/templates/audio/_train_route.ssml.eex
- lib/screens_web/views/audio_view.ex
This reverts commit 0fa81bc9236a1d58d986112cad9d0a44de1b3138.
> feat: re-apply CR track number changes

- lib/screens/route_patterns/parser.ex
- lib/screens/route_patterns/route_pattern.ex
> fix: only use route patterns with matching route id in line map stops

- config/config.exs
> fix: Add alert headsign matcher for Quincy Center

- assets/css/base/base_route_pill.scss
- assets/css/dup/departure_route.scss
- assets/src/components/eink/base_route_pill.tsx
**Asana task**: [Support long route numbers on DUPs](https://app.asana.com/0/1185117109217413/1200062478427236/f)
> Handle long slashed bus route numbers on DUPs

- assets/src/hooks/v2/use_api_response.tsx
- lib/screens/config/bus_shelter.ex
- lib/screens/config/screen.ex
- lib/screens_web/controllers/v2/screen_api_controller.ex
- lib/screens_web/controllers/v2/screen_controller.ex
- lib/screens_web/templates/v2/layout/app.html.eex
- lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Backend setup](https://app.asana.com/0/1185117109217413/1200050362904577)
> feat: make v2 backend use app_id

- lib/screens/dup_screen_data/request.ex
> fix: via isn't capitalized in 214/216 destination overrides

- assets/src/components/dup/version.tsx
This marks the release of the frontend version with the stacked bus pill CSS fix.
> chore: Bump DUP frontend version

- assets/css/bus_eink_v2.scss
- assets/css/bus_shelter_v2.scss
- assets/css/dup_v2.scss
- assets/css/gl_eink_double_v2.scss
- assets/css/gl_eink_single_v2.scss
- assets/css/solari_large_v2.scss
- assets/css/solari_v2.scss
- assets/css/v2/bus_shelter/normal_header.scss
- assets/css/v2/dup/normal_header.scss
- assets/css/v2/eink/normal_header.scss
- assets/css/v2/solari/normal_header.scss
- assets/css/v2/solari_large/normal_header.scss
- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/bus_shelter.tsx
- assets/src/apps/v2/dup.tsx
- assets/src/apps/v2/gl_eink_double.tsx
- assets/src/apps/v2/gl_eink_single.tsx
- assets/src/apps/v2/solari.tsx
- assets/src/apps/v2/solari_large.tsx
- assets/src/components/v2/dup/normal_header.tsx
- assets/src/components/v2/eink/normal_header.tsx
- assets/src/components/v2/lcd/normal_header.tsx
- assets/src/components/v2/normal_header.tsx
- lib/screens/v2/candidate_generator/solari.ex
- lib/screens/v2/candidate_generator/solari_large.ex
- test/screens/v2/candidate_generator/solari_large_test.exs
- test/screens/v2/candidate_generator/solari_test.exs
**Asana task**: [Frontend real headers](https://app.asana.com/0/1185117109217413/1200050362904583)
There's a lot of CSS that could (and should) be factored out later, but I wanted to wait until we have a chance to talk with the designers about how exactly we should do that.
> feat: NormalHeader frontend components

- lib/screens/bus_screen_data.ex
> fix: sort bus eink departures by time

- codecov.yml
- config/dev.exs
- config/test.exs
- lib/screens/config/state/local_fetch.ex
- semaphore/test.sh
- test/screens/config_test.exs
**Asana task**: [disable CodeCov on screens](https://app.asana.com/0/1185117109217413/1200274986747515)
> feat: disable codecov

- lib/screens/config/v2/departures/section.ex
- lib/screens/v2/candidate_generator/helpers/departures.ex
- test/fixtures/config.json
> fix: small departures backend fixes

- .github/workflows/elixir.yml
- mix.exs
**Asana task**: [Migrate screens CI to GitHub Actions](https://app.asana.com/0/home/1114181446740766/1199946732081240)
Description
> chore: set up Elixir CI GitHub action

- lib/screens_web/controllers/screen_api_controller.ex
(cherry picked from commit 73a71add5839edc3ae3213a74f53fa2fd41ca1f3)
**Asana task**: [Log data requests from new Solari screens](https://app.asana.com/0/1185117109217413/1200074998406104/f)
> feat: temporarily log user agent on solari api requests

- assets/src/components/v2/subway_status.tsx
1. Full station names, delays up to N minutes
2. Abbreviated station names, delays up to Nm
3. Abbreviated station names, delays (no time specified)
> fix(subway status): further abbreviate delays

- lib/screens_web/controllers/auth_controller.ex
> feat: Log messages from Ueberauth failures

- assets/src/components/admin/admin_tables.tsx
> feat: Add evergreen content config column to V2 app admin tables

- lib/screens/v2/screen_data.ex
- lib/screens_web/controllers/v2/screen_controller.ex
**Asana task**: [set up splunk alert to check is power is on](https://app.asana.com/0/1185117109217413/1200857245763080/f)
> feat: Log bus shelter requests ahead of launch

- lib/screens/v2/screen_data.ex
- lib/screens_web/controllers/v2/screen_api_controller.ex
**Asana task**: [Make sure V2 client app responds properly to `{force_reload: true}`](https://app.asana.com/0/1185117109217413/1200857421333777/f)
(Frontend is already all set)
> feat: Add backend logic to communicate force-reloads to V2 app clients

- assets/css/v2/bus_shelter/flex/page_indicator.scss
- assets/src/components/v2/bus_shelter/flex/page_indicator.tsx
**Asana task**: [Non transition animations for bus shelters](https://app.asana.com/0/1174677763694537/1200837195220161/f)
Pretty straightforward! I opted not to do the "empty" animation when the bar resets, since that would require awareness and comparison of previous/current state.
> feat: Bus shelter page indicator animation

- assets/css/v2/gl_eink/departures/time.scss
> fix: increase size of Now in GL e-Ink departures

- assets/css/gl_eink_v2.scss
- assets/css/v2/eink/departures/overnight.scss
- assets/src/apps/v2/gl_eink.tsx
- assets/src/components/v2/eink/overnight_departures.tsx
- lib/screens/v2/candidate_generator/gl_eink.ex
- lib/screens/v2/candidate_generator/widgets/departures.ex
- lib/screens/v2/widget_instance/overnight_departures.ex
- lib/screens_web/views/v2/audio/overnight_departures_view.ex
- test/screens/v2/candidate_generator/widgets/departures_test.exs
- test/screens/v2/widget_instance/overnight_departures_test.exs
**Asana task**: [Handle overnight on GL e-Ink v2](https://app.asana.com/0/1185117109217413/1201257438721090/f)
> fix/feat: Added new widget for overnight on GL eInk.

- lib/screens_web/views/v2/audio/departures_view.ex
**Asana task**: [Update the second bus arrival in departures audio](https://app.asana.com/0/1185117109217413/1201290145138216/f)
> tweak: Added headsign to second arrival departures audio.

- assets/src/components/dup/README.md
This bit about packaging for local testing was missing.
> doc: Update DUP packaging README

- assets/package-lock.json
- assets/package.json
- assets/src/apps/bus_eink.tsx
- assets/src/apps/dup.tsx
- assets/src/apps/gl_eink_double.tsx
- assets/src/apps/gl_eink_single.tsx
- assets/src/apps/solari.tsx
- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/bus_shelter.tsx
- assets/src/apps/v2/dup.tsx
- assets/src/apps/v2/gl_eink.tsx
- assets/src/apps/v2/gl_eink_single.tsx
- assets/src/apps/v2/solari.tsx
- assets/src/apps/v2/solari_large.tsx
- assets/src/hooks/use_sentry.tsx
- config/config.exs
- config/prod.exs
- lib/screens_web/controllers/screen_controller.ex
- lib/screens_web/controllers/v2/screen_controller.ex
- lib/screens_web/templates/screen/index.html.eex
- lib/screens_web/templates/v2/screen/index.html.eex
- lib/screens_web/views/screen_view.ex
- lib/screens_web/views/v2/screen_view.ex
**Asana task**: [Set up Sentry](https://app.asana.com/0/1185117109217413/1201331890574433/f)
Until SENTRY_DSN is added as an environment variable and `record_sentry` is set to true in the config, issues will not report to Sentry. DSNs can be found [here](https://sentry.io/settings/mbtace/projects/screens-frontend/keys/) if you ever want to test this locally.
PR to add new variables: https://github.com/mbta/devops/pull/201
> feat: Add Sentry

- lib/screens_web/controllers/v2/audio_controller.ex
**Asana task**: [Add audio request logging for v2 apps](https://app.asana.com/0/1185117109217413/1201338926200092/f)
> feat: Add audio request logging for v2 apps

- config/config.exs
> fix: ENV variable name for Sentry

- config/config.exs
> fix Corrected Sentry ENV variable name take 2.

- config/config.exs
- config/releases.exs
> fix: Corrected Sentry ENV variable name take 2.

- lib/screens/v2/widget_instance/subway_status.ex
**Asana task**: [Remove closed B branch stations from Subway Status widget](https://app.asana.com/0/1185117109217413/1201417948872069/f)
> chore: Remove closed B branch stations from Subway Status widget

- lib/screens/dup_screen_data/response.ex
> cleanup: Removed unnecessary function.

- lib/screens/v2/departure.ex
- test/screens/v2/departure_test.exs
**Asana task**: [Fix handling of non-numerical bus route pills](https://app.asana.com/0/1185117109217413/1201507620913022/f)
> fix: name used for non-numerical route pills

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- README.md
- assets/package-lock.json
- docs/devcontainer_development.md
- docs/local_development.md
**Asana task**: [Consider using a VSCode dev container for development](https://app.asana.com/0/1185117109217413/1201503555711110/f)
This adds config and documentation for running the app in a VS Code dev container, which confers the advantage of quick, repeatable builds and much easier version upgrades.
I manually tested the setup steps from both a freshly cloned repo and an existing project that's been built/run under local development previously.
> chore: Devcontainer config and documentation

- lib/screens/config/screen.ex
- lib/screens/config/v2/pre_fare.ex
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/screen_data/parameters.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Set up pre-fare screen back-end](https://app.asana.com/0/1185117109217413/1201522871607744/f)
Left a comment in code but will reiterate here. This will initially use the standard fixed-page builder for flex. We will need to create a new sticky builder for variable page length.
> feature: Create backend for pre fare screens

- assets/css/pre_fare_v2.scss
- assets/css/v2/placeholder.scss
- assets/css/v2/pre_fare/body/normal_left.scss
- assets/css/v2/pre_fare/body/normal_right.scss
- assets/css/v2/pre_fare/header/normal_left.scss
- assets/css/v2/pre_fare/header/normal_right.scss
- assets/css/v2/pre_fare/screen/normal.scss
- assets/css/v2/pre_fare/screen_container.scss
- assets/src/apps/admin.tsx
- assets/src/apps/v2/pre_fare.tsx
- assets/src/components/admin/admin_add_modal.tsx
- assets/src/components/admin/admin_navbar.tsx
- assets/src/components/admin/admin_tables.tsx
- assets/src/components/v2/pre_fare/normal_body_right.tsx
- assets/src/components/v2/pre_fare/normal_header_left.tsx
- assets/src/components/v2/pre_fare/normal_header_right.tsx
- assets/src/components/v2/pre_fare/normal_screen_left.tsx
- assets/src/components/v2/pre_fare/normal_screen_right.tsx
- assets/src/components/v2/pre_fare/top_level_switch.tsx
- assets/src/components/v2/widget.tsx
- assets/webpack.config.js
**Asana task**: [Set up pre-fare screen front-end](https://app.asana.com/0/1185117109217413/1201522871607749/f)
These changes line up with the changes made in https://github.com/mbta/screens/pull/1153. Any changes made during review of that PR will need to be tested with this PR before this is merged.
> feat: Pre-Fare frontend

- assets/src/components/admin/admin_tables.tsx
- lib/screens/config/v2/elevator_status.ex
- lib/screens/config/v2/pre_fare.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Define elevator status widget config](https://app.asana.com/0/1185117109217413/1201621878856244/f)
> feat: define elevator widget config

- assets/src/apps/gl_eink_double.tsx
- assets/src/apps/gl_eink_single.tsx
- assets/src/apps/solari.tsx
> fix: Removed call to sentry hook before Router is active.

- .github/workflows/asana-merged.yml
- .github/workflows/asana-pr-opened.yml
**Asana task**: [Test task for setting up Asana - GitHub integration](https://app.asana.com/0/1185117109217413/1201657995454308)
> Edited Asana integration

- .github/workflows/asana-merged.yml
**Asana task**: [Test task for setting up Asana - GitHub integration](https://app.asana.com/0/1185117109217413/1201657995454308)
> Prompt "merged" action by a different way

- assets/src/components/v2/bus_shelter/normal_body.tsx
- assets/src/components/v2/bus_shelter/sticky.tsx
> POC: sticky widget

- .github/workflows/asana-merged.yml
No ticket, but I didn't realize I was using a non-existent secret name
> Fix Asana integration on merge

- lib/screens/v2/candidate_generator/bus_shelter.ex
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/candidate_generator/widgets/subway_status.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Pre-fare template:  update the candidate_generator with finalized template](https://app.asana.com/0/1185117109217413/1201736552436953/f)
Changed some slots names, added body_takeover for left screen, added flex_zone, moved SubwayStatus instance functions to a neutral folder.
> feat: Finalize pre-fare candidate_generator

- assets/css/pre_fare_v2.scss
- assets/css/v2/pre_fare/body/normal_right.scss
- assets/css/v2/pre_fare/flex/one_large.scss
- assets/css/v2/pre_fare/flex/two_medium.scss
- assets/css/v2/pre_fare/screen_container.scss
- assets/src/apps/v2/pre_fare.tsx
- assets/src/components/v2/pre_fare/body_takeover_left.tsx
- assets/src/components/v2/pre_fare/body_takeover_right.tsx
- assets/src/components/v2/pre_fare/flex/one_large.tsx
- assets/src/components/v2/pre_fare/flex/two_medium.tsx
- assets/src/components/v2/pre_fare/normal_body_left.tsx
- assets/src/components/v2/pre_fare/normal_body_right.tsx
- assets/src/components/v2/pre_fare/normal_screen_right.tsx
- assets/src/components/v2/pre_fare/screen_takeover_left.tsx
- assets/src/components/v2/pre_fare/screen_takeover_right.tsx
- lib/screens/v2/candidate_generator/pre_fare.ex
**Asana task**: [Pre-fare template: implement frontend changes to the screen template](https://app.asana.com/0/1185117109217413/1201736552436957/f)
Some components were missing/not correctly named because we adjusted the template in the backend. This should have all of the pieces we need to plug and play new widgets.
> tweak: Pre-Fare frontend changes to match backend template

- lib/screens/v3_api.ex
Update hardcode api-dev url where applicable
> fix: Change api-dev url

- assets/css/v2/pre_fare/elevator_status.scss
**Asana task**: [[Elevator Footer] Adjust background color](https://app.asana.com/0/0/1201914758246004/f)
Adjusted background color
> tweak: Elevator Status footer color

- assets/src/components/v2/elevator_status.tsx
**Asana task**: [[Elevator Footer] Incorrect phone number](https://app.asana.com/0/0/1201913315187968/f)
Fixed the phone number.
> fix: Elevator Status phone number

- assets/css/v2/pre_fare/body/normal.scss
**Asana task**: [[Template] Make background color of right screen gray  ](https://app.asana.com/0/0/1201907517384552/f)
Gave both pre-fare screens a background color.
> tweak: Pre-Fare body background color

- assets/css/v2/pre_fare/elevator_status.scss
**Asana task**: [[Elevator Header] Font size and color of "Elevator Closures"](https://app.asana.com/0/0/1201934463541777/f)
Font color will be changed in https://github.com/mbta/screens/pull/1259.
> tweak: Elevator header text size

- lib/screens/config/v2/pre_fare.ex
- lib/screens/v2/screen_audio_data.ex
These changes are needed before anyone can start Pre-Fare audio work. Went ahead and made this now to get it out of the way for everyone.
> feat: Enable PreFare audio

- lib/screens/v2/widget_instance/subway_status.ex
- lib/screens_web/views/v2/audio/subway_status_view.ex
- test/screens/v2/widget_instance/subway_status_test.exs
**Asana task**: [Audio implementation: Subway Status Widget](https://app.asana.com/0/1185117109217413/1202035304691542/f)
https://user-images.githubusercontent.com/10713153/161328273-c52b9586-f37f-474b-a25b-7b716c6a369d.mp4
https://user-images.githubusercontent.com/10713153/161328411-560e8943-755a-4b82-9298-20ab422d94d4.mp4
> feat: Subway Status audio

- assets/css/v2/pre_fare/reconstructed_alert.scss
- config/config.exs
- config/test.exs
- lib/screens/dup_screen_data/data.ex
- lib/screens/v2/widget_instance/reconstructed_alert.ex
- lib/screens_web/views/v2/audio/reconstructed_alert_view.ex
- test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**:  Adhoc
Added Govt Center and Maverick to headsign list. Use that for reconstructed alerts on boundaries
> Alert headsigns

- config/config.exs
**Asana task**: [Alert widgets don't handle Green Line suspension Government Center - Copley](https://app.asana.com/0/1185117109217413/1202101924522477)
> Fixed headsign error

- lib/screens_web/views/v2/audio/reconstructed_alert_view.ex
**Asana task**: [Error on fullscreen audio for OL fullscreen alert](https://app.asana.com/0/1185117109217422/1202102359681100/f)
> fix: FreeTextLine audio readout bug

- assets/css/v2/pre_fare/evergreen/image.scss
**Asana task**: [Adjust size/style of evergreen content slot on Pre-Fare](https://app.asana.com/0/inbox/1199335143657941/1202155229252819/1202155830437801)
Quick update for evergreen content to allow ease of testing
> Evergreen CSS should extend to the edges

- assets/css/bus_eink_v2.scss
- assets/css/bus_shelter_v2.scss
- assets/css/dup_v2.scss
- assets/css/gl_eink_v2.scss
- assets/css/pre_fare_v2.scss
- assets/css/solari_large_v2.scss
- assets/css/solari_v2.scss
- assets/css/v2/multi_screen_page.scss
- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/bus_shelter.tsx
- assets/src/apps/v2/dup.tsx
- assets/src/apps/v2/gl_eink.tsx
- assets/src/apps/v2/pre_fare.tsx
- assets/src/apps/v2/solari.tsx
- assets/src/apps/v2/solari_large.tsx
- assets/src/components/v2/multi_screen_page.tsx
- assets/src/components/v2/screen_container.tsx
- assets/src/hooks/v2/use_api_response.tsx
- lib/screens_web/controllers/v2/screen_controller.ex
- lib/screens_web/templates/v2/screen/index_multi.html.eex
**Asana task**: [Create all-screens pages for v2](https://app.asana.com/0/1185117109217413/1201514401502519/f)
Went ahead and did this for v2 DUPs and Solari, even though there are no v2 versions of those screens. The ticket also say not to worry about Pre-Fare, but it was super low effort to implement it for them after the general solution was implemented.
> feat: V2 MultiScreenPage view

- lib/screens/v2/candidate_generator/pre_fare.ex
**Asana task**: [Remove placeholder widgets from pre-fare candidate pool](https://app.asana.com/0/1185117109217422/1202263703593510/f)
> tweak: Remove placeholder widgets from pre-fare screen candidate pool

- lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
**Asana task**: adhoc
Sentry error: https://sentry.io/organizations/mbtace/issues/3268716458/?project=6061747&query=is%3Aunresolved
Handle alerts with more than one nil stop_ids.
> Bugfix: Handle GL delay impacting multiple whole branches

- lib/screens/stops/stop.ex
> tweak: Capitalized M in UMass.

- scripts/connecting_routes.exs
Each rating, we need to determine whether the connecting routes at each subway station has changed (for in-vehicle screens). This script kinda helps with that; still needs some work, but we can update it further during the next rating change, because it's low-priority. For now, the change made here is to add a date filter so that we can compare the transfers that existed during the _old_ rating to those of the _new_ rating, because both ratings can exist in prod at the same time.
> Added date filter to connecting routes script

- lib/screens/stops/stop.ex
- lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
- test/screens/v2/widget_instance/reconstructed_alert_test.exs
Ensure that all routes end at a station for that station to be considered a terminal.
> Govt Center alert bugfix

- .github/workflows/deploy-ecs.yml
.../deploy.yml -> .../deploy-ecs.yml
> fix: Reference correct filename in workflows repo

- assets/src/apps/bus_eink.tsx
- assets/src/apps/dup.tsx
- assets/src/apps/gl_eink_double.tsx
- assets/src/apps/gl_eink_single.tsx
- assets/src/apps/solari.tsx
- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/bus_shelter.tsx
- assets/src/apps/v2/dup.tsx
- assets/src/apps/v2/gl_eink.tsx
- assets/src/apps/v2/pre_fare.tsx
- assets/src/apps/v2/solari.tsx
- assets/src/apps/v2/solari_large.tsx
- assets/src/util/sentry.tsx
**Asana task**: ["Log" to Sentry when initialized](https://app.asana.com/0/1185117109217413/1202570896674728)
Logs a simple message when Sentry is set up for an app, I hope? We haven't worked with captureMessage, so not totally sure what this will look like, or if it will send too many messages... Let's see?
> Added simple Sentry.captureMessage

- .github/workflows/deploy-elasticbeanstalk-dev.yml
(the dev EB environment no longer exists)
> Prevent EB auto-deploy on PR merge

- assets/src/components/dup/dup_screen_page.tsx
- assets/src/components/dup/screen_container.tsx
- assets/src/constants.tsx
- assets/src/hooks/use_api_response.tsx
Added a 20 second refresh to DUP simulations so Screenplay will continue showing updated info.
> fix: Add refresh rate to DUP simulations

- lib/screens/v2/candidate_generator/pre_fare.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
> Revert Experiment 1

- assets/css/v2/pre_fare/body_right/normal.scss
- assets/css/v2/pre_fare/evergreen/image.scss
- assets/css/v2/pre_fare/flex/one_large.scss
- assets/css/v2/pre_fare/flex/paging_indicator.scss
- assets/src/components/v2/pre_fare/flex/one_large.tsx
- assets/src/components/v2/pre_fare/flex/two_medium.tsx
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/widget_instance/elevator_status.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Implement alert experiment: eliminate elevator widget and move subway status and alert widget](https://app.asana.com/0/1185117109217413/1202709465836411/f)
See design mock-up in task.
***This should not be deployed until go-ahead is given by design**
> experiment: Switch upper and lower and remove elevator status

- assets/css/v2/pre_fare/body_right/normal.scss
- assets/css/v2/pre_fare/evergreen/image.scss
- assets/css/v2/pre_fare/flex/one_large.scss
- assets/css/v2/pre_fare/flex/paging_indicator.scss
- assets/src/components/v2/pre_fare/flex/one_large.tsx
- assets/src/components/v2/pre_fare/flex/two_medium.tsx
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/widget_instance/elevator_status.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
> Revert "experiment: Switch upper and lower and remove elevator status"

- assets/src/components/v2/cr_departures.tsx
- lib/screens/v2/widget_instance/cr_departures.ex
- lib/screens_web/views/v2/audio/cr_departures_view.ex
- lib/screens_web/views/v2/audio/departures_view.ex
Also: shortened departures on the backend instead. 
Also: Conditionally show the "via headsign" message on the frontend visuals.
> CR widget audio

- lib/screens/config/v2/cr_departures.ex
- lib/screens/config/v2/pre_fare.ex
Add default to `CRDepartures` config.
> tweak: Added a default to cr_departures.

- assets/src/components/v2/shuttle_bus_info.tsx
- lib/screens/config/v2/shuttle_bus_info.ex
- lib/screens/v2/candidate_generator/pre_fare.ex
Main things:
1. Adjusted Spanish wording.
2. Added `enabled` to config to avoid displaying widget with defaults.
> tweak: shuttle bus polish

- lib/screens/config/v2/cr_departures.ex
- lib/screens/v2/candidate_generator/widgets/cr_departures.ex
Fixes error that happens when config uses defaults.
> fix: ignore cr dept widget if using default

- assets/css/v2/blue_bikes.scss
- assets/src/components/v2/blue_bikes.tsx
> BlueBikes Spanish translation polish + number positioning

- lib/screens_web/views/v2/audio/blue_bikes_view.ex
[Sample audio in slack](https://mbta.slack.com/archives/C039ARUM48H/p1660947267820239)
> feat: BlueBikes widget audio from designs

- assets/src/components/eink/base_departure_time.tsx
- assets/src/components/v2/cr_departures.tsx
- lib/screens/v2/candidate_generator/widgets/cr_departures.ex
- lib/screens_web/views/v2/audio/cr_departures_view.ex
1. Improve pacing in CR audio.
2. Changed CR to grab destination from config instead of fetching it from API.
3. Added an `m` to minute range. (Most changes in that file are from Format on Save...)
> polish: Surge stuff

- lib/screens/config/dup/override.ex
Added some functions so admin tool doesn't error.
> fix: Prevent DUP admin tool error

- assets/css/v2/pre_fare/evergreen/image.scss
Corrected size of full body evergreen for PreFare.
> Fixed CSS for pre-fare full body evergreen.

- assets/css/v2/pre_fare/cr_departures.scss
- assets/src/components/v2/cr_departures.tsx
> fix: CR baseline alignment

- lib/screens/config/v2/evergreen_content_item.ex
- lib/screens/v2/candidate_generator/widgets/evergreen.ex
- lib/screens/v2/widget_instance/evergreen_content.ex
- test/screens/v2/widget_instance/evergreen_content_test.exs
Added configurable priority to evergreen audio.
> feat: Audio priority for evergreen

- lib/screens/v2/widget_instance/audio_only/content_summary.ex
- test/screens/v2/widget_instance/audio_only/content_summary_test.exs
> tweak: skip content summary wellington

- assets/css/v2/blue_bikes.scss
**Asana task**: [Polish: Adjust column widths for Blue Bike bike/docks to match design spec](https://app.asana.com/0/1185117109217413/1202842567354994/f)
Changed the BlueBike station rows column width to match the designs.
> polish: Adjusted column sizes for BlueBikes.

- assets/css/v2/bus_shelter/simulation.scss
- assets/css/v2/pre_fare/simulation.scss
**Asana task**: [Fix sizing of Evergreen content in simulations](https://app.asana.com/0/0/1202857319474140/f)
Added max sizes to evergreen sims to avoid overflow.
> polish: Simulation evergreen sizing

- assets/src/components/v2/cr_departures/overnight_cr_departures.tsx
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/candidate_generator/widgets/cr_departures.ex
- lib/screens/v2/widget_instance/overnight_cr_departures.ex
- lib/screens_web/views/v2/audio/overnight_cr_departures_view.ex
- test/screens/v2/widget_instance/overnight_cr_departures_test.exs
**Asana task**: [CR Widget: Implement overnight audio changes](https://app.asana.com/0/1185117109217413/1202963933316748)
> CR widget overnight audio

- lib/screens/v2/widget_instance/cr_departures.ex
- lib/screens_web/views/v2/audio/cr_departures_view.ex
**Asana task**: [CR Widget: Implement daytime audio changes](https://app.asana.com/0/1185117109217413/1202963933316746)
https://miro.com/app/board/uXjVPfv2P_g=/?moveToWidget=3458764532967523924&amp;cot=14&fromRedirect=1
> Fix audio for new CR widget design

- assets/css/v2/bus_eink/simulation.scss
- assets/css/v2/bus_shelter/simulation.scss
- assets/css/v2/gl_eink/simulation.scss
- assets/css/v2/pre_fare/simulation.scss
Part 1 of 2 for [this polish task](https://www.notion.so/mbta-downtown-crossing/c879496a39fd4e62969fe1d0eecdfa01?v=f7ad0a8b40784aaebb1aaac3d417bb39&p=506626730932486ca5a83e66c2c59ebf&pm=s).
> Added drop-shadow to widgetize screen sims

- assets/css/dup/dup_screen_page.scss
- assets/css/v2/bus_eink/simulation.scss
- assets/css/v2/bus_shelter/simulation.scss
- assets/css/v2/gl_eink/simulation.scss
- assets/css/v2/pre_fare/simulation.scss
[Notion](https://www.notion.so/mbta-downtown-crossing/c879496a39fd4e62969fe1d0eecdfa01?v=f7ad0a8b40784aaebb1aaac3d417bb39&p=8c02d4ddf3e142a4b41e01b0c5549e2d&pm=s). Part 2!
> Simulation scrollbar padding bugfix

- config/dev.exs
- lib/screens/screens_by_alert/self_refresh_runner.ex
Manually tested by switching the job on temporarily.
> tweak: Increase TTLs in local dev, keep running self-refresh job at same interval

- assets/src/components/v2/normal_header.tsx
Adhoc: to be deployed with the other GLX deployments on Sunday night
Reversion of https://github.com/mbta/screens/pull/1568
> Reverting the hardcoded EIG headsign

- assets/src/components/v2/eink/fare_info_footer.tsx
Notion [task](https://www.notion.so/mbta-downtown-crossing/Lowercase-Cash-in-footer-ac73ebb62c5f47a2af2d9d2fd4fdd7bd)
Just made a letter lowercase.
> polish: Make cash lowercase

- lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: [Handle 1/7-1/8 Red Line disruption on both branches](https://app.asana.com/0/1185117109217422/1203650217404208)
Temporarily make alert #478816 an invalid candidate at Porter & Charles/MGH
Once done, I will need to schedule an evergreen widget
> RL Shuttling patch 1/7/23

- assets/src/apps/v2/bus_shelter.tsx
**Asana task**: [Check that all All-Screen URLs work ](https://app.asana.com/0/1185117109217413/1203649321370981/f)
Bus Shelter was the only app that failed consistently, so this fix is specifically for that app. I did catch the Pre-Fare URL breaking in dev-green, but that was actually a config issue. I fixed that config and the URL is working again.
> fix: Bus Shelter all-screens URL

- .github/workflows/deploy-ecs.yml
> fix: File name in workflow

- .github/workflows/deploy-ecs.yml
I forgot that our folders in the `mbta-screens` bucket are prefixed with `screens-`.
> fix: S3 path in workflow

- assets/css/v2/dup/normal_header.scss
- lib/screens/v2/candidate_generator/dup.ex
- lib/screens/v2/widget_instance/normal_header.ex
- test/screens/v2/candidate_generator/dup_test.exs
- test/screens/v2/widget_instance/normal_header_test.exs
**Asana task**: [[Widgetize DUPs] Header widget](https://app.asana.com/0/1185117109217413/1203279317437008/f)
> feat: DUP v2 normal header widget

- assets/css/admin.scss
Make the textareas less eager to show you what they've got.
> fix: Make admin textareas less bouncy

- assets/src/components/v2/simulation_screen_container.tsx
Fixed the data object used for screens not in `alternateView`.
> fix: v2 simulation

- test/screens/v2/widget_instance/elevator_status_test.exs
Just another little fix that I'm pulling out of the DUP v2 alerts backend PR
> Fix test module name to align with file path

- lib/screens/v2/candidate_generator/bus_eink.ex
- lib/screens/v2/candidate_generator/bus_shelter.ex
- lib/screens/v2/candidate_generator/dup.ex
- lib/screens/v2/candidate_generator/gl_eink.ex
- lib/screens/v2/candidate_generator/pre_fare.ex
- lib/screens/v2/candidate_generator/solari.ex
- lib/screens/v2/candidate_generator/solari_large.ex
- lib/screens/v2/candidate_generator/widgets/departures.ex
**Asana task**: [[tech debt] Use sane timeouts for Task calls](https://app.asana.com/0/1185117109217422/1204176045657639/f)
> fix: Use a sane timeout for Task.async_stream calls

- assets/src/components/admin/admin_tables.tsx
> feat: Add Alerts column to DUP v2 config table

- assets/src/components/v2/free_text.tsx
- lib/screens/v2/widget_instance/dup_alert/serialize.ex
**Asana task**: [Delay, any, 1/1](https://www.notion.so/mbta-downtown-crossing/Delay-any-1-1-059b7d9725b549299a78380c1cd6a226?pvs=4)
Changed delay alerts to show clock icon.
> polish: Delay alert icon

- assets/package-lock.json
- assets/package.json
> Revert "build(deps-dev): bump webpack from 5.75.0 to 5.76.0 in /assets"

- assets/package-lock.json
- assets/package.json
> rolling back wepback upgrade because e-ink can't.

- assets/css/v2/dup/departures/route_pill.scss
**Notion task**: [Bus pills are correctly rendered differently](https://www.notion.so/mbta-downtown-crossing/Bus-pills-are-correctly-rendered-differently-93acad6dcb3f4a2e99dd57e52006dabc?pvs=4)
Added shadow to bus pills.
> polish: Bus pill drop shadow

- lib/screens/v2/candidate_generator/dup/alerts.ex
- test/screens/v2/widget_instance/dup_special_case_alert_test.exs
Belated old work. Finally made the Dup special cases tests. One test for each case. They are faux integration tests because they run the candidate_generator code through the serialization.
> tech debt: Made a test for each DUP special case

- lib/screens/v2/candidate_generator/dup/departures.ex
> Corrected parameter name.

- assets/css/v2/dup/free_text.scss
- lib/screens/v2/widget_instance/dup_alert/serialize.ex
**Asana task**: ad hoc-ish
These changes ensure that the issue text never takes up more than 2 lines.
> tweak: Use line pills and adjust bolding in alert issue line

- .gitignore
- assets/src/components/v2/dup/rotation_index.tsx
- assets/src/components/v2/dup/version.tsx
Version bump for first v2 package.
> bump DUP version

- lib/screens/v2/widget_instance/reconstructed_alert.ex
[Slack thread](https://mbta.slack.com/archives/C039ARUM48H/p1683832377453069?thread_ts=1683553807.621649&cid=C039ARUM48H)
> Suppress alert 495152 on Porter & Charles/MGH pre-fare screens

- assets/src/apps/solari.tsx
**Asana task**: [Add Solari logging](https://app.asana.com/0/1185117109217413/1204334459814122/f)
> Add Solari watchdog listener on Solari app root component mount

- lib/screens/v2/widget_instance/reconstructed_alert.ex
New alert ID to suppress for the weekend of 5/19.
> tweak: 5-19 alert suppression

- assets/css/bus_shelter_v2.scss
- assets/src/components/v2/subway_status/lcd_subway_status.tsx
Surprised CI didn't catch this in the original PR...
> Fixed some frontend issues causing deploy to fail.

- assets/css/pre_fare_v2.scss
- assets/css/v2/pre_fare/body_left/flex.scss
- assets/css/v2/pre_fare/body_left/normal.scss
- assets/css/v2/pre_fare/body_left/takeover.scss
- assets/package-lock.json
- assets/src/apps/v2/pre_fare.tsx
- assets/src/components/v2/pre_fare/body_left_flex.tsx
- lib/screens/v2/candidate_generator/pre_fare.ex
- test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Update Pre-Fare template](https://app.asana.com/0/1185117109217413/1204649346992049/f)
> tweak: Add new paged layout variation for pre-fare left body region

- assets/src/components/v2/dup/version.tsx
> tweak: Bump DUP package version

- lib/screens/v2/widget_instance/subway_status.ex
**Notion task**: [Multiple rows show up expanded](https://www.notion.so/mbta-downtown-crossing/Multiple-rows-show-up-expanded-e54526b1088b4074bb06d12b10f8be12?pvs=4)
[Incorrect station name appears](https://www.notion.so/mbta-downtown-crossing/Incorrect-station-name-appears-20c2bc0377ff495fb16b089b768d0139?pvs=4)
Fixed an error that could happen when trying to get stop names for informed entities while serializing station closures.
> polish: Stop names from informed_entities

- assets/css/v2/pre_fare/reconstructed_alert.scss
- assets/src/components/v2/reconstructed_takeover.tsx
**Asana task**: [Pre-Fare Alerts: Update takeover frontend](https://app.asana.com/0/1185117109217413/1204649346992047/f)
Overall, there aren't a ton of changes. Most notable are card bg color, footer, and icons.
>  tweak: Pre-Fare takeover alert layout

- assets/css/triptych_v2.scss
- assets/css/v2/triptych/body/normal.scss
- assets/css/v2/triptych/screen/normal.scss
- assets/css/v2/triptych/screen_container.scss
- assets/src/apps/v2/triptych.tsx
- assets/src/components/admin/admin_add_modal.tsx
- assets/src/components/admin/admin_tables.tsx
- assets/webpack.config.js
**Asana task**: [New screen app: frontend](https://app.asana.com/0/1185117109217413/1204882696236161/f)
Added everything needed for the frontend portion of the new triptych app.
> feat: Triptych setup - Frontend

- assets/css/v2/train_crowding.scss
[Polish](https://www.notion.so/mbta-downtown-crossing/edd94c069e03485ab1c2a266f614dff9?v=88d02f21a705495c8dc56cbf96089690&p=810a5fd735574ddba1a43979049779fb&pm=s)
> Fix header font color for crowding widget

- assets/css/v2/train_crowding.scss
[Polish](https://www.notion.so/mbta-downtown-crossing/edd94c069e03485ab1c2a266f614dff9?v=88d02f21a705495c8dc56cbf96089690&p=f97dfd11c2db4595882926d22b38b8f3&pm=s)
> Bring box-shadow of key to foreground

- lib/screens/v2/candidate_generator/widgets/train_crowding.ex
> [tweak] Added :in_transit_to as a valid vehicle status for crowding

- lib/screens/ol_crowding/logger.ex
> Added translation to logger.

- lib/screens/v3_api.ex
> tweak: Log URL for failed V3 API requests

- assets/src/components/v2/train_crowding.tsx
As requested.
I'm merging this into my existing branch with improvements to the packaging process, since I have been building off of that and am not sure which of those changes we will actually want to keep in the end.
> tweak: Label lowest crowding level as "Seats available"

- lib/screens/v2/widget_instance/reconstructed_alert.ex
New alert suppression at Porter and Charles/MGH.
> tweak: RL Alert Suppression

- test/screens/v2/candidate_generator/widgets/train_crowding_test.exs
**Asana task**: Pre-fare alerts eng QA
Just needed to change how we generate the location context struct for these tests.
> fix: Update location context stop sequences field in TrainCrowdingTest

- lib/screens/v2/screen_audio_data.ex
- lib/screens_web/controllers/v2/screen_api_controller.ex
- mix.lock
**Asana task**: [🤔 Mercury: Audio read-out content](https://app.asana.com/0/1176097567827729/1205748798471858/f)
Added audio SSML to response for `gl_eink_v2`. If the `app_id` is anything but `gl_eink_v2`, the response is unchanged.
> feat: Mercury GL E-Ink audio

- lib/screens/v2/widget_instance/reconstructed_alert.ex
> Log alert ID and screen's home stop when disruption diagram logic fails

- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/gl_eink.tsx
- assets/src/components/admin/admin_tables.tsx
- assets/src/components/v2/elevator_status.tsx
- assets/src/components/v2/widget_page.tsx
- lib/screens/application.ex
- lib/screens/config/state.ex
- lib/screens/departures/departure.ex
- lib/screens/ol_crowding/agent.ex
- lib/screens/ol_crowding/dynamic_supervisor.ex
- lib/screens/ol_crowding/logger.ex
- lib/screens/v2/candidate_generator/dup/alerts.ex
- lib/screens/v2/candidate_generator/widgets/train_crowding.ex
- lib/screens/v2/screen_audio_data.ex
- lib/screens/v2/screen_data.ex
- lib/screens/v2/widget_instance/departures.ex
- lib/screens/v2/widget_instance/reconstructed_alert.ex
- lib/screens_web/controllers/v2/screen_api_controller.ex
- lib/screens_web/controllers/v2/screen_controller.ex
- lib/screens_web/router.ex
- lib/screens_web/templates/v2/screen/index_widget.html.eex
- mix.lock
- test/screens/v2/widget_instance/departures_test.exs
> Merge master into prefare-alerts

- lib/screens/v2/widget_instance/subway_status.ex
Suppressing SubwayStatus at MFA and Heath St for Surge.
> Suppress SubwayStatus at MFA and Heath St for Surge.

- lib/screens/v2/widget_instance/subway_status.ex
Changed suppression to only occur during GL surge.
> Added a date range for SubwayStatus suppressions.

- mix.lock
> chore: Bump screens_config dep version to pick up EvergreenContentItem.to_json fix

- assets/src/components/solari/route_pill.tsx
**Asana task**: [[bug] Fix Solari GL pill](https://app.asana.com/0/1185117109217422/1203899379105553)
> Added GL to the pill map for Solari

- lib/screens/config/state.ex
**Asana task**: [Increase refresh rate of Screens config cache](https://app.asana.com/0/1185117109217413/1205700210661291/f)
> tweak: Change screens config cache refresh rate from 15 sec to 5 sec

- lib/screens/v2/widget_instance/reconstructed_alert.ex
> Added an ID to suppress.

- lib/screens/config/state.ex
This reverts commit ee9eb330a51064d8a335ff6e77acab408a8a6ed9.
> Revert "tweak: Change screens config cache refresh rate from 15 sec to 5 sec (#1936)"

- assets/src/apps/v2/gl_eink.tsx
- assets/src/components/v2/eink/top_and_flex_takeover.tsx
- lib/screens/v2/candidate_generator/gl_eink.ex
- test/screens/v2/candidate_generator/gl_eink_test.exs
Added a new layout needed for the Surge. Puts a takeover on the top body and the flexzone.
> tweak: New GL E-Ink layout

- assets/css/gl_eink_v2.scss
- assets/css/v2/eink/body/flex_zone_takeover.scss
- assets/src/apps/v2/gl_eink.tsx
- assets/src/components/v2/eink/flex_zone_takeover.tsx
- assets/src/components/v2/eink/top_and_flex_takeover.tsx
- lib/screens/v2/candidate_generator/gl_eink.ex
- test/screens/v2/candidate_generator/gl_eink_test.exs
Also need a layout where the top screen is normal and the body screen has a flex takeover.
> tweak: Flex Zone takeover layout

- lib/screens/v2/widget_instance/reconstructed_alert.ex
OIOs will close the current alert and make a new alert that starts Tuesday.
> Added an alert to suppress.

- lib/screens/v2/widget_instance/reconstructed_alert.ex
GLX closures have new IDs too.
> Added GLX IDs.

- lib/screens/stops/stop.ex
- lib/screens/v2/widget_instance/reconstructed_alert.ex
[Notion task](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=4dc2b267ba724abd8a53b4647bbeb3d5&p=0f7979eeee944e258c128e42318fa426&pm=s)
Also tucked in a fix for this [notion task](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=4dc2b267ba724abd8a53b4647bbeb3d5&p=2c3e2b67a4b04748a7371d066b003817&pm=s)
> fix: Prefare Alerts polish -- RL headsigns for branch-only alerts

- lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: [Prepare Screens for GL Feb 20 closure](https://app.asana.com/0/1185117109217413/1206555924032813/f)
Updated alert IDs for upcoming disruption.
> tweak: More alert suppressions

- lib/screens/v2/widget_instance/reconstructed_alert.ex
> Changed alerts to suppress.

- assets/src/apps/v2/bus_eink.tsx
- assets/src/apps/v2/bus_shelter.tsx
- assets/src/apps/v2/dup.tsx
- assets/src/apps/v2/gl_eink.tsx
- assets/src/apps/v2/pre_fare.tsx
- assets/src/apps/v2/triptych.tsx
Adjusted route order so the multi-screen route uses the correct component.
> tweak: Multi-Screen Route order

- assets/css/bus_shelter_v2.scss
- assets/css/busway_v2.scss
- assets/css/v2/bus_shelter/simulation.scss
- assets/css/v2/lcd_common/simulation.scss
- assets/src/apps/v2/busway.tsx
`lcd_common` continues to not be the greatest name for things we're sharing between (only) `busway` and `bus_shelter`, but I haven't thought of anything better yet. See also: https://github.com/mbta/screenplay/pull/332
> chore: Screenplay simulation support for Busway v2

- docs/architecture/widget_framework.md
fixes a couple of broken links i noticed while reading through the docs
> docs: fix broken links in widget_framework.md

- assets/css/v2/lcd_common/departures.scss
- assets/css/v2/lcd_common/departures/later_departures.scss
- assets/css/v2/lcd_common/departures/row.scss
- assets/css/v2/lcd_common/departures/section.scss
- assets/css/v2/lcd_common/simulation.scss
- assets/src/components/v2/departures/later_departures.tsx
See commit messages for details!
---
- https://app.asana.com/0/0/1207495619155889
- https://app.asana.com/0/0/1207495619155909
> Fix Later Departures overflow-related issues

- lib/screens/v2/candidate_generator/dup/departures.ex
I'm still stuck on #2091 but I think this will be helpful in the mean time.
> feat: log error with context on timeout

- lib/screens_web/views/v2/audio/reconstructed_alert_single_screen_view.ex
Addresses: https://mbtace.sentry.io/issues/5540567925/events/77cc8e651b484bce8d941cfa34684520/
> fix: Handle FreeText issues in Pre-Fare audio

- .credo.exs
- lib/screens/v2/widget_instance/departures.ex
RE: https://github.com/mbta/screens/pull/2111#discussion_r1678278595
> chore: disable cyclomatic complexity check

- lib/screens/telemetry.ex
- lib/screens/v3_api.ex
Previously our telemetry logging would show `cached=true` whenever we had a possible value for a request in the cache **not** when we actually used the cache. This was misleading and is corrected in this change.
Being able to return a meta value in a `Screens.Telemetry` span required a new function that expects the same return value as `:telemetry.span/3` which is a tuple where the second element is a map of metadata to include in the `*.stop` event.
> fix: only set cached=true when a 304 is received

- lib/screens/alerts/alert.ex
- test/screens/alerts/alert_test.exs
Reverts the blanket switchover to the Alerts cache
> Revert "feat: switch to in-memory Alerts cache instead of V3 API (#2122)"

- assets/package-lock.json
- assets/package.json
- assets/tsconfig.json
Didn't see a PR from Dependabot so gonna do it myself. Upgrading to v5.
> chore: Update Typescript

- assets/css/v2/eink/fare_info_footer.scss
- assets/src/components/v2/eink/fare_info_footer.tsx
---
- https://app.asana.com/0/0/1208343202037652
> chore: include contactless payments in E-ink copy

- assets/src/components/admin/admin_tables.tsx
**Asana task**: [[Bug] PA/ESS message Screenplay: Minute and AM/PM fields unexpectedly update in Chrome browser](https://app.asana.com/0/1185117109217413/1208573903710847/f)
Description
A follow-up to #2291
> Add admin field for audio interval enabled for bus shelters

- lib/screens/headways.ex
- lib/screens/stops/stop.ex
- lib/screens/v2/rds.ex
- test/screens/v2/rds_test.exs
...plus a couple other minor changes. This should be the last "foundation" task needed before we can finally implement some end-to-end DUP logic on top.
> chore: add headway lookups to RDS logic

- assets/css/v2/elevator/footer.scss
- assets/src/components/v2/elevator/footer.tsx
Footer got a small design update. Because this affects all layouts, putting it in it's own small standalone branch. [Design](https://www.figma.com/design/UG6HV7HIsdR6B6QABOFm01/Elevator-Screens?node-id=2130-37201&node-type=frame&t=T11qgt4IXujdiHPl-0)
> chore: Elevator footer style updates

- lib/screens/v2/candidate_generator/elevator.ex
- test/screens/v2/candidate_generator/elevator_test.exs
I turned my brain off for a sec and didn't catch an issue in the code in #2318. Added a test that would have caught it in the first place.
> Fix: Elevator candidate generation

- assets/src/components/admin/admin_add_modal.tsx
- assets/src/components/admin/admin_tables.tsx
When we added a few additional required fields to elevator screen configuration, we neglected to update the admin UI with these fields.
---
- https://app.asana.com/0/0/1208978498455632
> fix: unable to add elevator screens in admin

- assets/css/v2/elevator/elevator_closures_list.scss
- assets/src/components/v2/elevator/current_elevator_closed.tsx
- assets/src/components/v2/elevator/elevator_closures_list.tsx
- assets/src/components/v2/elevator/types.ts
- lib/screens/alerts/alert.ex
- lib/screens/alerts/parser.ex
- lib/screens/elevator.ex
- lib/screens/v2/candidate_generator/elevator/closures.ex
- lib/screens/v2/widget_instance/current_elevator_closed.ex
- lib/screens/v2/widget_instance/elevator/closure.ex
- lib/screens/v2/widget_instance/elevator_closures_list.ex
- priv/elevators.json
- scripts/format_elevator_data.exs
- test/screens/elevator_test.exs
- test/screens/v2/candidate_generator/elevator/closures_test.exs
- test/screens/v2/widget_instance/current_elevator_closed_test.exs
- test/screens/v2/widget_instance/elevator_closures_list_test.exs
Best reviewed per-commit as there are some chonky changes prior to the "main" one. Commit messages have the details on each change.
---
- https://app.asana.com/0/0/1208677840815949
> Elevator backup summaries

- lib/screens/audio.ex
- lib/screens/cache/owner.ex
- lib/screens/departures/departure.ex
- lib/screens/elevator.ex
- lib/screens/report.ex
- lib/screens/route_patterns/route_direction_stops.ex
- lib/screens/screens_by_alert/memcache.ex
- lib/screens/v2/candidate_generator/dup/alerts.ex
- lib/screens/v2/candidate_generator/dup/departures.ex
- lib/screens/v2/candidate_generator/elevator/closures.ex
- lib/screens/v2/location_context.ex
- lib/screens/v2/widget_instance/audio_only/alerts_intro.ex
- lib/screens/v2/widget_instance/audio_only/alerts_outro.ex
- lib/screens/v2/widget_instance/audio_only/content_summary.ex
- lib/screens/v2/widget_instance/cr_departures.ex
- lib/screens/v2/widget_instance/dup_alert.ex
- lib/screens/v2/widget_instance/serializer/route_pill.ex
- lib/screens_web/controllers/auth_controller.ex
- lib/screens_web/controllers/v2/screen_controller.ex
- To prevent confusion between Log and Logger
- Name suggestions welcome
> Changed Screens.Log to Screens.Report

- lib/screens/alerts/alert.ex
- lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
- lib/screens/v2/localized_alert.ex
- lib/screens/v2/widget_instance/alert.ex
- lib/screens/v2/widget_instance/elevator_status.ex
- lib/screens/v2/widget_instance/reconstructed_alert.ex
- test/screens/alerts/alert_test.exs
Two small refactors of some things I noticed while working on #2443. See commit messages for details!
> refactor: `Alert` functions cleanup

- assets/css/v2/bus_shelter/link_footer.scss
- assets/css/v2/lcd_common/departures/later_departures.scss
- assets/css/v2/lcd_common/departures/time.scss
- assets/css/v2/lcd_common/normal_header.scss
- assets/css/v2/pre_fare/alert-banner.scss
- assets/css/v2/pre_fare/normal_header.scss
- assets/css/v2/pre_fare/prefare_single_screen_alert.scss
- assets/css/v2/pre_fare/reconstructed_alert.scss
- assets/css/v2/pre_fare/shuttle_bus_info.scss
- assets/css/v2/pre_fare/simulation.scss
**Asana task**: [Fix serif font fallback on some screen elements](https://app.asana.com/0/1185117109217413/1209354747944094)
Description
Added Sans-Serif fallback on font-family for bus_shelter, lcd_common and pre_fare styles
> Added Sans-Serif fallback on font-family for bus_shelter, lcd_common and pre_fare styles

- assets/src/util/query_params.tsx
- lib/screens/v2/candidate_generator/on_bus.ex
- lib/screens/v2/screen_data/query_params.ex
- test/screens/v2/screen_data/query_params_test.exs
**Asana task**: [Modify on-bus app parameters](https://app.asana.com/0/1185117109217413/1209437447171224)
Add a new parameter called "vehicle_id" to the on-bus screens app
> chore: Add vehicle_id query param for bus screens

- assets/src/components/v2/eink/bottom_screen_filler.tsx
**Asana task**: [Update wording on E-ink bottom_screen_filler widget](https://app.asana.com/0/1185117109217413/1208948291372834)
Changes wording slightly.
> update wording on bottom_screen_filler widget

- lib/screens/v2/widget_instance/reconstructed_alert.ex
The goal of this change is to introduce a boundary between determining where a ReconstructedAlert is "placed" (dual screen, single screen, or flex zone) and serializing it. This opens the possibility of the same alert being placed differently depending on whether a screen is using the "duo" or "solo" template, though that is not implemented here.
* Introduce `placement/1` which makes the above-mentioned determination. Use this across various public widget functions to ensure consistency.
* Add missing fields to the "serialized response" typespecs.
* Make some functions private which were public but unused outside of this module.
> refactor: ReconstructedAlert placement logic

- lib/screens/v2/candidate_generator/elevator/closures.ex
- test/screens/v2/candidate_generator/elevator/closures_test.exs
**Asana task**: https://app.asana.com/0/1185117109217413/1209609402860537
> chore: disable elevator exiting summaries

- lib/screens/v2/candidate_generator/elevator/closures.ex
- test/screens/v2/candidate_generator/elevator/closures_test.exs
When "this" elevator (the one an elevator screen is associated with) is among the alternate elevators for a closure, and the closed elevator has nearby or in-station redundancy (i.e. "this" elevator is at the same station and the alternative path does not involve travel outside the station), display a unique closure summary that identifies "this" elevator as an alternate.
**Asana task**: https://app.asana.com/0/1185117109217413/1209093626932232
> feat: "this is the backup" elevator closure text

- lib/screens/image.ex
This gives us more control over how screen browsers cache uploaded images, so if we need to fix a mistake in an image, we can simply replace the existing file and be confident that screens will display the new version within a small and well-defined period of time.
Notes:
* This only applies to new uploads going forward — previous uploads will not have the cache-control metadata since this is applied per-object at upload time. We could potentially write a script to batch-apply this to all existing objects, if we think that's valuable, but screens which have already "decided" to cache an image for an extended period of time and aren't checking with the server anyway might not be helped by this.
* For this to work, we need to consistently use the Image Manager rather than manual AWS CLI …
> feat: add caching metadata on uploaded images

- lib/screens/v2/widget_instance/departures.ex
- test/screens/v2/widget_instance/departures_test.exs
* Previously, each section could read out up to 15 departures, without regard for its visual layout. This could result in impractically long readouts due to e.g. only 2 departures fitting on the screen visually, but the audio including 10. To address this, make audio serialization respect the configured maximum/base size of the section visually.
* Ensure audio readouts of sections using destination-based grouping only include one departure per "destination", in line with the visual presentation, instead of two.
---
- https://app.asana.com/0/0/1210225474039152
> chore: improve departures widget audio readouts

- lib/screens/v2/candidate_generator/bus_shelter.ex
> fix: incorrect arity on dependency function

- assets/css/admin/inspector.scss
- assets/css/v2/bus_eink/simulation.scss
- assets/src/components/admin/inspector.tsx
- assets/src/hooks/v2/use_api_response.tsx
- assets/src/hooks/v2/use_refresh_rate.ts
Miscellaneous fixes and QoL for the Inspector. See commit messages for details!
> fix(admin): Just Inspector Things™

- lib/screens/v2/candidate_generator/dup/departures.ex
- test/screens/v2/candidate_generator/dup/departures_test.exs
> [Bugfix] Override overnight section with NoDataSection

- lib/screens/v2/candidate_generator/dup/departures.ex
- lib/screens/v2/location_context.ex
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211034864503121
See commit messages for details. This fixes remaining issues with the DUP presentation of the current Blue Line disruption.
> Fix issues with DUP alert/headway messaging

- priv/elevators.json
- scripts/format_elevator_data.exs
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210675381138619
Adds elevators at Natick Center, Winchester Center, and East Taunton. Fixes a typo in the summary text for a Science Park elevator.
> chore: update elevator redundancy data
