mbta/screens

lib/screens/v2/candidate_generator.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/screen_data.ex, test/screens/v2/candidate_generator/bus_shelter_test.exs, test/screens/v2/screen_data_test.exs
**Asana task**: [Verify backend](https://app.asana.com/0/1185117109217413/1200038952107753)
- Clean up some types in `Screens.V2.ScreenData`
- Rename candidate generator `candidate_templates` -> `candidate_template`
- Define `candidate_template` for `Screens.V2.CandidateGenerator.BusShelter`
- Add header and footer widget instances to `BusShelter.candidate_instances`
- Add missing `Template.slot_combinations` call to `pick_instances`
=> fix: small widget backend fixes

assets/css/v2.scss, assets/css/v2/header/normal.scss, assets/src/components/v2/flex/one_large.tsx, assets/src/components/v2/flex/one_medium_two_small.tsx, assets/src/components/v2/flex/two_medium.tsx, assets/src/components/v2/header/normal.tsx, assets/src/components/v2/screen/normal.tsx, assets/src/components/v2/screen/takeover.tsx, assets/src/components/v2/widget.tsx
**Asana task**: [normal header](https://app.asana.com/0/1185117109217413/1199987812749015/f)
Basic normal header widget with expected props matching the fields of the `NormalHeader` widget instance struct on the backend. It displays the ISO8601 timestamp directly for now rather than formatting it in a human-readable way.
=> feat: Normal header widget

assets/src/components/v2/static_image.tsx, assets/src/components/v2/widget.tsx, lib/screens/v2/candidate_generator/bus_shelter.ex
**Asana task**: [static image (small, medium, large, takeover)](https://app.asana.com/0/1185117109217413/1199987812749027)
Defines a single `StaticImage` component.
Currently the component doesn't do anything to account for the size; the position is determined by the parent, and the size is just determined by the size of the image. When we implement the real templates, we should standardize where the position and size of each widget are defined. Maybe the widget specifies its size and the parent just specifies the positions of its children?
=> feat: StaticImage widget

assets/src/components/dup/destination.tsx, lib/screens/dup_screen_data/request.ex
**Asana tasks**:
- [Add 214/216 to list of custom abbreviations for long headsigns](https://app.asana.com/0/1185117109217413/1200064893145449)
- [Move custom headsign abbreviation mapping to the backend](https://app.asana.com/0/1199892628355780/1200064461121641)
Note: It should be OK to deploy the server-side changes while the current DUP client is still on the screens; once we make the changes on the back-end, none of the front-end replacements will match.
=> feat: move DUP long headsign mapping to backend, add 214/216

lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/gl_eink_double.ex, lib/screens/v2/candidate_generator/gl_eink_single.ex, lib/screens/v2/candidate_generator/solari.ex, lib/screens/v2/screen_data.ex, lib/screens/v2/widget_instance/placeholder.ex, test/screens/v2/candidate_generator/bus_eink_test.exs, test/screens/v2/candidate_generator/bus_shelter_test.exs, test/screens/v2/candidate_generator/dup_test.exs, test/screens/v2/candidate_generator/gl_eink_double_test.exs, test/screens/v2/candidate_generator/gl_eink_single_test.exs, test/screens/v2/candidate_generator/solari_test.exs
**Asana task**: [Backend templates](https://app.asana.com/0/1185117109217413/1200050362904587)
Notes:
- For double-stack e-ink, I only included one medium flex zone (i.e. there's no option for two small ones).
- For the GL single-stack, I considered the "flex zone" which takes over one of the two departures to be part of main content. That is, it doesn't appear in the template. (The same is true for the small inline alert at the bottom of that screen.) That's because these overlap with the footprint of the main content slot, so we wouldn't be able to choose their contents independently.
=> feat: define screen_template in candidate generators for real screen types

assets/css/dup/departure_route.scss
`display: flow` is not a valid property on Chrome. This fix makes the stacked slashed bus route pills display correctly on both Chrome and Firefox. (And hopefully on the DUP screens)
We'll need to make a new zip to get this change in.
=> fix: Use display: block for DUP stacked route pill parts

lib/screens/dup_screen_data.ex, lib/screens/dup_screen_data/data.ex, lib/screens/dup_screen_data/special_cases.ex
**Asana task**: [Support for multiple shuttles at Kenmore](https://app.asana.com/0/1185117109217413/1200132302343957)
In addition to the partial and full-screen alerts specified in the linked Asana task, this PR sets a headway message for the Green Line when all three branches have shuttling (since, in this case, Kenmore is a temporary mid-route terminal and won't have any predictions). This is consistent with other situations where we have DUPs at mid-route shuttle endpoints.
Note: This PR assumes that each line's shuttle has its own alert. I believe this has been true in the past (when working on Beacon Junction outside of Kenmore, the C and D had their own shuttles), and Alerts UI doesn't seem to provide a way to specify stops on multiple routes as a part of the same alert.
=> feat: automatically handle multiple westbound shuttles at Kenmore

lib/screens/dup_screen_data/special_cases.ex
"No (B) Boston College or" already wraps on DUPs, so adding another linebreak after the or was causing issues.
=> fix: remove extra linebreak for kenmore B and D shuttles

assets/src/components/v2/widget.tsx, lib/screens/config/screen.ex, lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/gl_eink_double.ex, lib/screens/v2/candidate_generator/gl_eink_single.ex, lib/screens/v2/candidate_generator/helpers.ex, lib/screens/v2/candidate_generator/solari.ex, lib/screens/v2/widget_instance/alert_header.ex, lib/screens/v2/widget_instance/normal_header.ex, test/screens/v2/candidate_generator/bus_eink_test.exs, test/screens/v2/candidate_generator/bus_shelter_test.exs, test/screens/v2/candidate_generator/dup_test.exs, test/screens/v2/candidate_generator/gl_eink_double_test.exs, test/screens/v2/candidate_generator/gl_eink_single_test.exs, test/screens/v2/candidate_generator/solari_test.exs, test/screens/v2/widget_instance/alert_header_test.exs, test/screens/v2/widget_instance/normal_header_test.exs
**Asana task**: [Backend real headers](https://app.asana.com/0/1185117109217413/1200050362904581)
This PR defines two header widgets:
- `NormalHeader` which has text, an optional icon, and a current time.
- `AlertHeader` which has text and an optional color, accent pattern, icon and current time.
These widgets are split by purpose: Most of the time, we'll use `NormalHeader`. The DUP headers on full screen alerts would use `AlertHeader`. I imagine that the GL e-Ink "Green Line Shuttle" header with a hatched border could, as well (for example).
This PR also modifies all of the screen candidate generators to return `NormalHeader` widgets. We can update them to return `AlertHeader` widgets when appropriate as a part of the future alerts epic.
=> feat: normal header backend

lib/screens_web/controllers/screen_api_controller.ex
**Asana task**: [Log data requests from new Solari screens](https://app.asana.com/0/1185117109217413/1200074998406104)
Once we know what the new user agent is, we can revert this and add it to `ScreensWeb.UserAgent`.
=> feat: temporarily log user agent on solari api requests

lib/screens/gds_data/fetch.ex
We started getting 302 responses which redirect to add this new param.
=> fix: add AspxAutoDetectCookieSupport URL param to GDS API query

lib/screens_web/controllers/screen_api_controller.ex, lib/screens_web/user_agent.ex
**Asana task**: [Log data requests from new Solari screens](https://app.asana.com/0/1185117109217413/1200074998406104)
The new user agent appears to be:
`BrightSign/L2D676000639/6.2.94 (XD232) Mozilla/5.0 (Unknown; Linux mips) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.6.0 Chrome/45.0.2454.101 Safari/537.36`
This PR detects the new user agent and stops logging Solari screen user agents.
=> feat: detect new solari screen user agent

assets/css/dup/free_text.scss, lib/screens/dup_screen_data/response.ex
**Asana tasks**:
* [Update text on alert screen for DUPs during shuttle](https://app.asana.com/0/1199892628355780/1200064893145453)
* [Update text on full screen alert for boundary of shuttle](https://app.asana.com/0/1199892628355780/1200132302343963)
This PR makes two changes to how DUPs describe shuttle (and suspension) alerts:
1. No <line> trains due to <cause> replaces Station Closed due to <cause>
2. No <line> trains to <headsign> replaces No <line> service to <headsign>
Separately, I noticed that the `translateY` transform shouldn't apply to route pills when they're being used as an icon. This is an issue (for example) when we're showing headways on a DUP which has two sections.
=> fix: update dup shuttle alert text

lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/gl_eink_double.ex, lib/screens/v2/candidate_generator/gl_eink_single.ex, lib/screens/v2/candidate_generator/solari.ex, lib/screens/v2/candidate_generator/solari_large.ex
This updates all screens to pass their "draft" templates through `build_template/1` before returning from `screen_template/0`. This has no effect on any template besides the bus shelter one for now, but if/when we add backend paging to more screen types, it will be necessary.
=> Pass all screen templates through Builder.build_template/1

assets/css/bus_shelter_v2.scss, assets/css/colors.scss, assets/css/v2/bus_shelter/departures/crowding.scss, assets/css/v2/bus_shelter/departures/destination.scss, assets/css/v2/bus_shelter/departures/row.scss, assets/css/v2/bus_shelter/departures/time.scss, assets/css/v2/bus_shelter/route_pill.scss, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/bus_shelter.tsx, assets/src/apps/v2/dup.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/apps/v2/solari.tsx, assets/src/apps/v2/solari_large.tsx, assets/src/components/v2/departures/departure_alerts.tsx, assets/src/components/v2/departures/departure_crowding.tsx, assets/src/components/v2/departures/departure_row.tsx, assets/src/components/v2/departures/departure_time.tsx, assets/src/components/v2/departures/departure_times.tsx, assets/src/components/v2/departures/destination.tsx, assets/src/components/v2/departures/normal_departures.tsx, assets/src/components/v2/departures/normal_section.tsx, assets/src/components/v2/departures/notice_section.tsx, assets/src/components/v2/departures/route_pill.tsx, lib/screens/v2/departure.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/departure_test.exs, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [NormalDepartures component](https://app.asana.com/0/1185117109217413/1200233815812793)
We can't yet implement the logic to dynamically determine how many rows fit on the screen, since that relies on rows actually taking up vertical space. We'll add that in once we're done with the rest of the departures front-end.
=> feat: widgetized normal departures component without autosizing

assets/css/bus_shelter_v2.scss, assets/css/v2/bus_shelter/departures.scss, assets/css/v2/bus_shelter/departures/row.scss, assets/css/v2/bus_shelter/flex/page_indicator.scss, assets/css/v2/bus_shelter/link_footer.scss, assets/css/v2/bus_shelter/screen/normal.scss, assets/src/components/v2/bus_shelter/flex/one_large.tsx, assets/src/components/v2/bus_shelter/flex/one_medium_two_small.tsx, assets/src/components/v2/bus_shelter/flex/page_indicator.tsx, assets/src/components/v2/bus_shelter/flex/two_medium.tsx, assets/src/components/v2/departures/normal_departures.tsx
**Asana task**: [NormalDepartures section auto-sizing + Complete Bus Shelter departures](https://app.asana.com/0/1185117109217413/1200292816120184)
This PR adds auto-sizing to to `NormalDepartures`, though for now it only supports departures widgets with a single section. It also adds missing styles for bus shelter screens, including displaying which page is currently visible.
=> feat: departure component autosizing and styles for bus shelter screens

lib/screens/v3_api.ex
Small fix to prevent issues in Splunk with the more detailed API request failure logging.
=> fix: Wrap extra field values in quotes in V3 API error logging

assets/css/bus_eink_v2.scss, assets/css/bus_shelter_v2.scss, assets/css/gl_eink_v2.scss, assets/css/v2/bus_eink/departures/crowding.scss, assets/css/v2/gl_eink/departures/time.scss, assets/css/v2/gl_eink/line_map.scss, assets/css/v2/gl_eink/screen/normal.scss, assets/src/apps/v2/gl_eink.tsx, assets/src/components/admin/admin_tables.tsx, assets/src/components/v2/gl_eink_double/line_map.tsx, assets/src/components/v2/gl_eink_double/normal_screen.tsx, lib/screens/config/v2/gl_eink.ex, lib/screens/config/v2/line_map.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/departure.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/line_map.ex, test/screens/v2/widget_instance/line_map_test.exs
**Asana task**: [GL eink map component](https://app.asana.com/0/1185117109217413/1200281105971705)
This line map should work for arbitrary stops (i.e. it's ok if there are fewer than two downstream stops).
It uses the most typical route pattern for the route and direction to determine the stop order, rather than hard-coding the stop sequence. This is what we're doing in the v1 app line map, and we can continue doing it until we revisit the question of how to get a canonical stop ordering.
=> feat: widgetized Green Line e-Ink line map

lib/screens/v2/widget_instance/alert.ex, test/screens/v2/widget_instance/alert_test.exs
**Asana task**: [determine widget slot name](https://app.asana.com/0/1185117109217413/1200354915858977/f)
Possibly helpful explanation of the big `reduce_while` inside `informs_all_active_routes_at_home_stop/1`: It starts with the set of routes that are actively serving the home stop on the current day as the accumulator. It looks at each informed entity one at a time, and removes any route IDs from the set.
If the set is empty after checking through all the informed entities, then the alert informs all active routes serving the home stop. If not, it does not inform all of them.
Note: I also updated `priority/1` to depend on `slot_names/1`. If `slot_names/1` returns `[:full_screen]`, then `priority/1` returns `[1]` in order to have the alert be placed before other widgets that might …
=> feat: Implement WidgetInstance.slot_names/1 for Alert widget

lib/screens_web/controllers/audio_controller.ex, lib/screens_web/controllers/screen_api_controller.ex, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_api_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/user_agent.ex
**Asana task**: [Log data requests from new Solari screens](https://app.asana.com/0/1185117109217413/1200074998406104/f)
`is_screen_conn?` now takes the screen ID as well. Solari user agents are just standard Ubuntu + latest/recent Firefox now, so I added a check on the requested screen ID to try and filter out as many non-screen requests as possible.
We still will probably get a few false-positive logs (e.g. if Ryan looks at the Solari app on his Ubuntu machine) but there isn't much we can do about that.
=> feat: Log new Solari screen data requests

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/serializer.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex, test/screens/alerts/alert_test.exs, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/serializer/route_pill_test.exs
**Asana task**: [serialize widget](https://app.asana.com/0/1185117109217413/1200354915858979/f)
I tried to factor out the logic for serializing route pills so that we don't have duplicated code for departures, alerts, and other places that use route pills.
There's also some questionably-readable module attributes at the top of the alert widget module now, where I tried to link all of the effect-related hardcoded values together. I'm totally open to making those less of an eyesore if the current approach seems bad.
=> feat: Alert widget serialize function; factored-out route pill logic

lib/screens/screen_data.ex
This changes the order in which the backend checks for the various quick-turnaround states (disabled, needs refresh) before actually fetching data for a screens API request.
Purpose: I want to tell clients pointed at screen 306 to refresh, but with the current server code that's not possible as long as they are disabled.
=> fix: Check whether screen needs refresh before checking if disabled

assets/css/eink/green_line/departures.scss, assets/src/components/eink/green_line/departures.tsx
**Asana task**: [Resolve E-Ink "widget" alert & delay badge overlap](https://app.asana.com/0/1185117109217422/1200603921061799/f)
This is the short-term fix described in the above task. Giving the PSA container a z-index other than `auto` causes it to render above the rest of the content. The `position: relative` is necessary to allow z-index to have an effect; does nothing otherwise.
=> quick fix: Give old GL eink single PSA a z-index to have it render over delay badge

assets/css/bus_shelter_v2.scss, assets/css/v2/bus_eink/departures/time.scss, assets/css/v2/bus_shelter/alert.scss, assets/css/v2/bus_shelter/body/normal.scss, assets/css/v2/bus_shelter/body/takeover.scss, assets/css/v2/bus_shelter/departures.scss, assets/css/v2/bus_shelter/departures/time.scss, assets/css/v2/bus_shelter/flex/one_large.scss, assets/css/v2/bus_shelter/flex/one_medium_two_small.scss, assets/css/v2/bus_shelter/flex/two_medium.scss, assets/css/v2/bus_shelter/link_footer.scss, assets/css/v2/bus_shelter/screen/normal.scss, assets/css/v2/bus_shelter/screen_container.scss, assets/css/v2/bus_shelter/subway_status.scss, assets/css/v2/gl_eink/departures/time.scss, assets/src/components/v2/departures/departure_time.tsx, lib/screens/v2/widget_instance/departures.ex
**Asana task**: [Updates from departures implementation review](https://app.asana.com/0/1185117109217413/1200480000015510/f)
Changes:
- I also fixed the footer, which had a height greater than its slot height.
- I also gave the bus shelter screen container element `overflow: hidden` to ensure that the screen is always 1080x1920, and to hide parts of the main content and footer box shadows that are cast on the flex zone.
=> fix: Visual tweaks for bus shelter screen

lib/screens/config/v2/bus_shelter.ex, lib/screens/config/v2/evergreen_content_instance.ex
**Asana task**: [lib/screens/config/v2/evergreen_content_instance.ex](https://app.asana.com/0/1185117109217413/1200625003989515/f)
One common config shape is used for both images and videos. We'll differentiate images from videos further down the request data flow, wherever it makes sense—might be safe to leave that to the frontend since the behavior of the two media formats doesn't really differ as far as the backend is concerned.
No `schedule` field for now--that will be added soon.
=> feat: Define evergreen content config

assets/css/v2/bus_shelter/subway_status.scss, assets/src/components/v2/subway_status.tsx
JSX was being passed to the `src` attribute of an `<img>` which was causing requests for `<screens app url>/[Object object]`; this changes the hardcoded SVGs to be 0-prop components and uses them appropriately.
=> fix: GL branch icon SVG components in subway status widget

assets/css/v2/bus_shelter/subway_status.scss, assets/src/components/v2/subway_status.tsx, assets/src/hooks/v2/use_api_response.tsx, lib/screens/v2/screen_data.ex, lib/screens/v2/screen_data/parameters.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Update bus shelter data refresh rate to every 20 seconds](https://app.asana.com/0/1185117109217413/1200812598281098/f)
(And change the bus shelter app's refresh rate to 20s, as requested)
V2 app refresh rates are defined in a module on the backend and the appropriate one is passed to the client app via a data attribute, similar to the `lastRefresh` value.
=> feat: Add backend-defined data refresh to V2 apps

assets/css/v2/bus_shelter/subway_status.scss, assets/src/components/v2/subway_status.tsx, assets/src/hooks/use_api_response.tsx, assets/src/hooks/use_interval.tsx, assets/src/hooks/v2/use_api_response.tsx, lib/screens/v2/screen_data.ex, lib/screens/v2/screen_data/parameters.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Update threshold to display failure images on screens](https://app.asana.com/0/1185117109217413/1200598106060756/f)
For up to a minute of consecutive failed data requests, the stale screen state is maintained.
After that, the usual behavior of setting state to `{success: false}` kicks in.
Tested on Solari.
=> feat: All apps wait for 1 minute of consecutive failed requests before showing "no data" screen

assets/css/v2/bus_shelter/subway_status.scss, assets/src/components/v2/subway_status.tsx
My previous fix used the wrong styles for the branch icon in a single-alert GL status row, and also passed a react component as a child of a div rather than actually rendering that component (`{Component}` vs `<Component />`).
This fixes that (and adds type declarations for everything, because I wanted to make sure nothing else was broken).
=> fix: Subway status branch icons for both single & multiple GL alert row types

lib/screens/dup_screen_data.ex, lib/screens/dup_screen_data/request.ex, lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/solari.ex, lib/screens/v2/candidate_generator/solari_large.ex, lib/screens/v2/candidate_generator/widgets/departures.ex
The functions invoked in these tasks always return—no need to add an extra layer of timeouts to confuse things.
=> fix: Remove timeouts from all async_stream calls

lib/screens/v2/widget_instance/alert.ex, test/screens/v2/widget_instance/alert_test.exs
**Asana task**: [Adjust full-screen alert priority to not beat out manually-configured full-screen content](https://app.asana.com/0/1185117109217413/1200865920846202/f)
This prevents automated override content (alerts) from competing with manually configured override content.
(Side note: if you can think of a clearer way of documenting/organizing the various priority values, let me know)
=> fix: Tweak priority of takeover alerts

assets/css/v2/bus_shelter/subway_status.scss, assets/src/components/v2/subway_status.tsx, lib/screens/v2/widget_instance/subway_status.ex
**Asana task**: [Subway status: prevent text overflows from affecting other rows](https://app.asana.com/0/1185117109217413/1200831960721500/f) | [Subway status: drop delay times in GL row](https://app.asana.com/0/1185117109217413/1200663189183711/f) | [Subway status: multiple GL branch disruptions overflow row, even with all shortening measures](https://app.asana.com/0/1185117109217413/1200831960721494/f)
Overall this PR makes some changes to prevent rows from wrapping, in favor of getting clipped at the end of the line.
I also fixed the client to handle non-branch GL statuses, where the list of branches is `null`, and made sure the list of branches for each status doesn't contain duplicates.
Commit messages describe the changes in detail.
=> fix: Subway status visual fixes

assets/css/bus_eink_v2.scss, assets/css/gl_eink_v2.scss, assets/css/v2/bus_eink/evergreen/image.scss, assets/css/v2/gl_eink/evergreen/image.scss, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/gl_eink.tsx, lib/screens/config/v2/bus_eink.ex, lib/screens/config/v2/gl_eink.ex, lib/screens/util/assets.ex, lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/widgets/evergreen.ex, test/screens/v2/candidate_generator/bus_eink_test.exs, test/screens/v2/candidate_generator/bus_shelter_test.exs, test/screens/v2/candidate_generator/gl_eink_test.exs
**Asana task**: [Add evergreen content to bus and green line e-Ink screens](https://app.asana.com/0/1185117109217413/1200928169910241/f)
Evergreen content can now be added to Bus and GL EInk screens. Styles should match resolution requirements for these screens, but please check me on that. Also found that GL EInk did not have a corresponding test file. Went ahead and added that here.
Description
=> feat: Evergreen content for EInk screens

lib/screens/v2/widget_instance/alert.ex
**Asana task**: [Only show alerts now/here on bus screens](https://app.asana.com/0/1185117109217413/1200992643788400/f)
For the time being, v2 bus alerts that do not actively apply to a screen's location will be excluded from candidacy. This is temporary until a better display strategy is decided on for other alerts.
=> temp feat: Only show here and now alerts on bus v2 screens

lib/screens/config/v2/evergreen_content_item.ex, lib/screens/config/v2/schedule.ex, lib/screens/v2/candidate_generator/widgets/evergreen.ex, lib/screens/v2/widget_instance/evergreen_content.ex, test/screens/v2/widget_instance/evergreen_content_test.exs
**Asana task**: [Add ability to schedule evergreen content](https://app.asana.com/0/1185117109217413/1200928169910248/f)
Evergreen content can now have a schedule. Schedule will be a list of objects with a start and end date. Existing Evergreen content will have a default schedule of always (nil for start and end).
=> feat: Schedules for Evergreen content

assets/css/v2/bus_shelter/screen_container.scss, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/bus_shelter.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/components/v2/screen_container.tsx, assets/src/hooks/v2/use_api_response.tsx
**Asana task**: [Investigate how to update pixels to prevent burn in on bus shelter screens](https://app.asana.com/0/1185117109217413/1201010702999846/f)
I found a way to do this without too much extra code complexity within `useApiResponse`. Probably the right way to go as long as the approach seems understandable to reviewer(s)!
=> feat: "blink" element to reduce pixel burn-in, synced to screen data refreshes

lib/screens/v2/candidate_generator/widgets/evergreen.ex, lib/screens/v2/widget_instance/evergreen_content.ex
**Asana task**: [Add ability to schedule evergreen content](https://app.asana.com/0/1185117109217413/1200928169910248/f)
Original code used a default value for now, so DateTime comparisons were not working as expected. Changed from using a default value to a value passed in by the evergreen candidate generator.
=> fix: Fix now value used by evergreen_content

assets/src/apps/v2/bus_shelter.tsx
Bumping the blink time for bus shelter screens to just over 1/30 sec to accomodate 30Hz screens.
=> fix: Make bus shelter blink length 34ms to accomodate 30Hz screens

lib/screens/config/v2/bus_shelter.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, test/screens/v2/candidate_generator/bus_shelter_test.exs
This change was needed in order to let us set bus shelter screen headers directly from config. (So that we can match the stop names Wayfinding has chosen for the physical signage, which don't currently match up with the names the API returns for each stop ID. E.g. 1743 -> "Columbus Ave @ Walnut Ave" ≠ Wayfinding's "Walnut Ave")
An extra `value_from_json/2` clause was temporarily included to prevent the current config from breaking the app, since it's missing the newly-added `type` key that we use to determine which type of header config the screen is using.
=> feat: Allow CurrentStopName config for bus shelter screens

lib/screens/v2/candidate_generator/widgets/departures.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/candidate_generator/widgets/departures_test.exs, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [Update type defs to support "notice rows" in departures list](https://app.asana.com/0/0/1201067686861561/f)
Changed up typedefs. This will allow the front end to display a single `section` with a list of objects that will either be one `notice`, one `notice` and one `departure`, or two `departures`.
A couple of discussions to start here:
1. The section attribute name `departures` doesn't make sense anymore. What would be a better name? `data`? `rows`?
2. Is `type` necessary anymore? Could there be a future need for it? I don't think so but wanted to double check. I know there are conditionals in the front-end that check for it, but they may need to be removed because of the typedefs changes anyway.
=> feat: Modify typedefs for departures

lib/screens/application.ex
Testing out whether GDS logging is somehow causing problems for all HTTP requests. (e.g. maybe there are too many GDS screens now such that it takes more than a minute to do all of the logging we do every minute and it gets backed up? We use a separate Hackney pool for GDS and the APIv3 for that reason, but it's not inconceivable that some other resource is getting exhausted...)
=> test: try disabling vendor logging to see if it fixes timeouts

assets/src/apps/v2/bus_shelter.tsx, assets/src/components/v2/screen_container.tsx, assets/src/hooks/v2/use_audio_readout.tsx, lib/screens/config/v2/audio.ex, lib/screens/v2/screen_audio_data.ex, lib/screens_web/controllers/v2/audio_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/router.ex, lib/screens_web/templates/v2/screen/index.html.eex, test/screens/v2/screen_audio_data_test.exs
This adds some new audio config values and makes it possible to set different volumes daytime and nighttime.
The client now gets its readout volume value from the server every time it requests a new readout, rather than getting a "constant" value on initial page load.
=> feat: Support configurable daytime/nighttime periods, with different readout volumes

lib/screens/v2/screen_audio_data.ex, test/screens/v2/screen_audio_data_test.exs
`now` was not being shifted to Eastern when computing the current audio volume from config. 🤦
=> fix: Shift `now` to Eastern time for all time-based config checking in ScreenAudioData

assets/package-lock.json, lib/screens/v2/widget_instance/subway_status.ex
**Asana task**: [Subway status handling of long term stop closure](https://app.asana.com/0/1185117109217413/1201374936544476/f)
Temporarily re-adding the stops that have been consolidated to the new Amory St stop, so that the subway status widget's presentation of the change aligns with dotcom's.
We will remove these stops from the list again once the alert that mentions them is deleted.
=> chore: Re-add BU West and Babcock St to subway status widget stop list

lib/screens/v2/widget_instance/line_map.ex
**Asana task**: [Increase space between overlapping trains](https://app.asana.com/0/1185117109217413/1201221301197680)
The positions of the vehicle icons (and associated departure prediction labels) are determined by their `index`. This change will guarantee that they differ by at least 0.4, which results in the labels not overlapping with what I hope is a sufficient margin.
=> [fix] GL Line Map: tweak vehicle spacing

assets/src/components/eink/green_line/departures.tsx
**Asana task**: [Invalid headway values on some GL e-ink screens](https://app.asana.com/0/1185117109217413/1201342811286106/f)
This scenario shouldn't happen any time but early morning, but just in case we will check for null.
=> fix: Prevent null headway in front-end

assets/src/apps/v2/bus_shelter.tsx, assets/src/components/v2/screen_container.tsx, assets/src/hooks/use_interval.tsx, assets/src/hooks/v2/use_audio_readout.tsx, lib/screens/config/v2/audio.ex, lib/screens/v2/screen_data/parameters.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Audio Plays at different times for Walnut NB/SB](https://app.asana.com/0/1185117109217413/1201341796500854/f)
- Updated backend config to be handle `interval_offset_seconds` audio config value
- Pass config value to frontend as data attribute
- Update initial audio readout logic to wait until the next 5m interval (plus offset if present) rather than initial page load
- Continue readouts at normal interval after that
=> feat: Add configurable audio offset

config/config.exs, lib/screens_web/endpoint.ex, lib/screens_web/plugs/metadata.ex
**Asana task**: [Add IP address to screen data request logging (both v1 and v2)](https://app.asana.com/0/1185117109217413/1201396741870851/f)
Add custom plug to add request client ip to logger metadata
=> feat: Add client_ip metadata to endpoint logs

assets/css/dup/free_text.scss, lib/screens/dup_screen_data/response.ex
**Asana task**: [DUP partial alert text for Ashmont/Braintree suspension and shuttle](https://app.asana.com/0/1185117109217413/1201010702999849/f)
The word `trains` caused bad wrapping for Ashmont/Braintree alerts. That word has been removed for that case. Also added CSS to prevent other cases from causing the same issue.
=> fix: Prevent text wrapping on DUP partial alert

lib/screens/mercury_data/fetch.ex
**Asana task**: [Update Mercury API logging](https://app.asana.com/0/1185117109217413/1201449270360560/f)
`cms.*` -> `nexus.*`
Tested locally—the desired fields are missing from the new server's responses right now, but Kevin said he will check with Mercury and have them re-add the fields.
=> chore: Change URL that we fetch Mercury device logs from

lib/screens/config/state/s3_fetch.ex
Register `:medium_flex` so that the app doesn't crash when parsing old config that still uses that slot name, which has since been renamed to `:medium` since it lives inside a flex zone now.
=> fix: Register the :medium_flex atom

lib/screens/config/state/s3_fetch.ex
Use the dummy atom in a log to hopefully fool the compiler into thinking it's needed.
=> fix: :medium_flex atom, take 2

README.md
Description:
Encountered a few hurdles when setting up and running the screens application locally for the first time. This PR contains some amendments to the readme that should help future engineers get past those hurdles quickly.
Quick summary of the changes:
- Specify install of autoconf version 2.69 as it looks like latest versions of autoconf are preventing asdf from building erlang
- Include a workaround (a bit hacky) for MacOSX and Erlang configure error
- Include mention of `signs_ui_config.json` file needed for running the app
View a preview of the rendered readme [here](https://github.com/mbta/screens/tree/pk/update-readme#readme)
=> Update screens repo readme file

assets/src/apps/bus_eink.tsx, assets/src/apps/dup.tsx, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/bus_shelter.tsx, assets/src/apps/v2/dup.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/apps/v2/gl_eink_single.tsx, assets/src/apps/v2/solari.tsx, assets/src/apps/v2/solari_large.tsx, assets/src/components/dup/screen_container.tsx, assets/src/components/eink/bus/screen_container.tsx, assets/src/components/eink/green_line/double/screen_container.tsx, assets/src/components/eink/green_line/single/screen_container.tsx, assets/src/components/solari/screen_container.tsx, assets/src/components/v2/screen_page.tsx, assets/src/hooks/use_sentry.tsx
**Asana task**: [Only set Sentry DSN data attribute on page requests from real screens](https://app.asana.com/0/1185117109217413/1201465640055315/f)
Biggest change here was moving the hook call for each app. Needed to be in the Router in order to grab the param.
=> tweak: Initialize Sentry only on real screens

docs/devcontainer_development.md
Docker doesn't support inline comments in env files.
=> doc-fix: Move env file comments to their own line

assets/css/v2/bus_eink/departures/row.scss
**Asana task**: [[Bus e-Ink] Fix vertical position of headsigns which wrap](https://app.asana.com/0/1185117109217413/1201520511503438/f)
=> fix: Adjusted bus eInk dept headsign alignement for wrapped names

lib/screens/v2/widget_instance/subway_status.ex
**Asana task**: [[Subway Status] Handle case where a single alert affects multiple branches](https://app.asana.com/0/1185117109217413/1201514401502521/f)
A single alert on the GL with stops on multiple lines selected was causing the screen to crash. Added a case statement to handle this edge case.
=> fix: Single alert GL multi branch edge case

lib/screens/v3_api.ex
**Asana task**: related to [💳 terraform-ize API and move to ECS](https://app.asana.com/0/584764604969369/1200732284152245)
As part of the ECS migration, we're moving the dev-green API to a new URL: https://api-dev-green.mbtace.com/ from https://green.dev.api.mbtace.com/. I did a search of CTD's repos and found the old URL hardcoded in a few places.
=> chore: Update API dev-green URL

lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Asana task**: [[bug] Subway status ignores GL alerts which affect the entire Green Line](https://app.asana.com/0/1185117109217413/1201804054848498/f)
When an alert that affecting the whole GL exists, the subway status was ignoring it. This was because we only looked for trunk vs. branch alerts. Now, when an alert comes through with all 4 branches in its informed entities, we treat it as a trunk alert.
=> fix: Subway Status with GL alert affecting whole line

assets/src/components/v2/departures/normal_departures.tsx
**Asana task**: [Explore time sorting error on V2 apps](https://app.asana.com/0/1185117109217413/1201453209353026)
Setting React keys on the top-level of the Departures Widget should force a re-mount with each data fetch, preventing wonky departure data from hanging around
=> Added key to top level of normal_departures for v2

lib/screens/v2/departure/builder.ex
**Asana task**: [Explore time sorting error on V2 apps](https://app.asana.com/0/1185117109217413/1201453209353026/f)
https://hexdocs.pm/elixir/Enum.html#sort/2-sorting-structs
I've created a [separate task](https://app.asana.com/0/1185117109217422/1201894802937869/f) to check out other spots where we use `Enum.sort` and make sure they don't need a similar fix.
=> fix: Sort departure times correctly

assets/css/v2/pre_fare/elevator_status.scss, assets/src/components/v2/elevator_status.tsx, assets/src/components/v2/persistent_carousel.tsx, assets/src/components/v2/persistent_wrapper.tsx, assets/src/components/v2/screen_container.tsx, assets/src/hooks/v2/use_api_response.tsx, lib/screens/v2/widget_instance/elevator_status.ex
**Asana task**: [Elevator status widget component - list view](https://app.asana.com/0/1185117109217413/1201621878856262/f)
This adds styles for the elevator status widget's list view. Logic to split up list view pages according to row heights will be added in a separate PR to keep the diff manageable.
I also split out the "persistent carousel" logic into its own HoC that builds on top of the `makePersistent` HoC, allowing the elevator status and other future frontend-paged widgets to skip the boilerplate and state management, and just pass a presentational component to the HoC.
Please let me know if the documentation makes sense!
Screenshots:
An example with multiple elevator closures at stations. Ignore the row overflow at the bottom for now; that will be prevented when we add the logic …
=> Elevator status list view + factor out persistent carousel logic

lib/screens/v2/screen_data.ex, lib/screens/v2/template/builder.ex, test/screens/v2/screen_data_test.exs
**Asana task**: [Pre-Fare:  Allow flex zones to have a variable page number](https://app.asana.com/0/1185117109217413/1201812714325999/f)
This change looks through the selected candidates that are to be placed and removes slots from the layout if it does not have a matching candidate. This allows us to use a maximum page approach to paged slots that use `Screens.V2.Template`.
=> tweak: Allow variable paging on V2 apps

assets/css/pre_fare_v2.scss, assets/css/v2/lcd_common_styles/subway_status.scss, assets/css/v2/pre_fare/subway_status.scss
**Asana task**: [[Subway Status] Adjust footer text and color](https://app.asana.com/0/0/1201914758246007/f)
Adjust the background and text colors for the Subway status widget footer. Also change the font to be unbolded.
Pre-fare:
Bus Shelter:
=> [Subway Status] Adjust footer text and color

assets/css/v2/pre_fare/body_left/takeover.scss, assets/css/v2/pre_fare/body_right/takeover.scss
**Asana task**: [[Evergreen Takeover] Takeover images not full height](https://app.asana.com/0/0/1201896247257218/f)
Height values match design now.
=> fix: Pre-Fare body takeover height

assets/css/v2/pre_fare/normal_header.scss
**Asana task**: [[Header] "Downtown Crossing" is wrapping](https://app.asana.com/0/0/1201896247257224/f)
I picked 1040 to give title the illusion of `padding-right: 40px`. Can't set padding now that one screen uses width of both screens.
=> tweak: Increased header title width

assets/css/v2/pre_fare/elevator_status.scss
**Asana task**: [[Elevator Detail page] All alert text should be cool black ](https://app.asana.com/0/0/1201934463541776/f)
Gave the widget a default text color.
=> tweak: Elevator alert text color

assets/css/v2/pre_fare/elevator_status.scss, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs, test/screens/v2/widget_instance/elevator_status_test.exs
**Asana task**: [Elevator status widget component - list view](https://app.asana.com/0/1185117109217413/1201621878856262/f)
This PR makes some small tweaks to the frontend styles to make the list view exactly match the designs, so that the backend can reliably calculate the height of each row as `100px + 48px * length(closures_at_station)`.
The rest of the code is the backend logic to achieve the page-splitting/fitting logic dictated by the [designs](https://app.abstract.com/projects/c04b5940-4805-11e8-8262-510af7fd49fe/branches/f6705d99-fa8b-4115-a97f-188ea9e01a11/collections/91521734-0e0f-434b-bf25-13516d47b1f3).
It took a lot of test cases to cover all the possible outputs of this logic—sorry for the gigantic test file!
=> feat: Elevator status widget page-splitting/fitting logic

lib/screens/audio.ex, lib/screens/bus_screen_data.ex, lib/screens/departures/departure.ex, lib/screens/dup_screen_data/request.ex, lib/screens/nearby_departures.ex, lib/screens/solari_screen_data.ex, lib/screens/util.ex
**Asana task**: [Check usages of `Enum.sort` for cases where we're incorrectly sorting a list of structs](https://app.asana.com/0/1185117109217413/1201894802937869/f)
Tested all of these after adding the sorter. The new Util function was added because some objects were strings in ISO8601 format. Those need to be converted before the sorter can work.
=> fix: Add sorter for Enum functions with DateTimes

assets/src/components/v2/full_line_map.tsx, lib/screens/v2/widget_instance/full_line_map.ex
**Asana task**: [[Pre-Fare] Line map needs to render in-sync](https://app.asana.com/0/1185117109217413/1201995187651695/f)
This uses the `makePersistentCarousel` higher-order component to sync the FullLineMap widget component's updates with the rest of the components that update based on the `lastSuccess` timestamp.
=> fix: Use `makePersistentCarousel` to have line map widget update in sync with rest of the page

assets/css/v2/pre_fare/elevator_status.scss, assets/src/components/v2/elevator_status.tsx, assets/src/hooks/v2/use_text_resizer.tsx
**Asana task**: [[Elevator Detail page] Use variable text sizes for the alert description](https://app.asana.com/0/0/1201901724848538/f)
This is a proposed general solution to variable text sizing for our v2 apps. Took the existing logic and put it in a custom hook. Definitely open to feedback on whether this is the solution we want going forward.
=> feat: Detail Page alert description variable text sizing

lib/screens/route_patterns/route_pattern.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs
**Asana task**: [[PreFare] Improve performance of get_parent_station_id](https://app.asana.com/0/1185117109217413/1201950331696435/f)
I noticed that we already get the data we need when fetching `stop_sequences`. I took that result and made a map of platform IDs -> parent station name. We can then do a lookup and avoid individual V3 calls.
=> refactor: Improve parent station fetch performance

lib/screens_web/views/v2/audio/reconstructed_alert_view.ex
Needed to fix a variable name. Wrong one was used. But hey, they have similar names.
=> fix: Variable used to generate route text.

lib/screens/route_patterns/route_pattern.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/v2/widget_instance/elevator_status_test.exs
**Asana task**: [[Bug] Elevator Status is not showing active alerts on connecting lines ](https://app.asana.com/0/1185117109217422/1202081351164230/f)
`informed_entities` does not always contain the platforms we expected. I changed `stop_sequences` to be a list of parent station ids. This is an ID that is always in a closure alert. Using that, we can reliably tell what alerts are on a connecting line.
=> fix: Elevator Status connecting lines logic

lib/screens/audio.ex
We've gotten some errors because these are actually strings, not DateTime structs. Sorry to distract from pre-fare work, but I want to sneak this in since I think it's breaking Solari audio.
Representative stacktrace:
```
** (exit) an exception was raised: ** (FunctionClauseError) no function clause matching in DateTime.compare/2 (elixir 1.13.1)
lib/calendar/datetime.ex:1319: DateTime.compare("2022-04-07T15:47:23Z", "2022-04-07T15:55:04Z") (elixir 1.13.1)
lib/enum.ex:3109: anonymous fn/3 in Enum.to_sort_by_fun/1 (stdlib 3.17)
lists.erl:973: :lists.sort/2 (elixir 1.13.1)
lib/enum.ex:3095: Enum.sort_by/3 (screens 0.1.0)
lib/screens/audio.ex:74: Screens.Audio.merge_section_departures/1 (screens 0.1.0)
lib/screens/audio.ex:64: anonymous fn/1 in …
```
=> fix: sort departure strings, not DateTimes

lib/screens/stops/stop.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: [Add Lechmere and Union Square to hard-coded stop sequences](https://app.asana.com/0/1185117109217413/1202042701703726/f)
The DUP at Haymarket actually shows "Northbound", so nothing to change there.
=> fix: Add GLX stops to GL-E lists

assets/css/v2/pre_fare/elevator_status.scss, assets/src/components/v2/elevator_status.tsx
**Asana task**: [[Elevator Detail page] Use variable text sizes for the alert header](https://app.asana.com/0/1185117109217413/1201901724848537/f)
Only two size options for header. [Design spec](https://app.abstract.com/projects/c04b5940-4805-11e8-8262-510af7fd49fe/branches/f6705d99-fa8b-4115-a97f-188ea9e01a11/commits/034d0d23528534baf767a758d27d7ff4157657d0/files/898fa222-8d26-4cae-b816-2678d1aeba53/layers/8E829759-D03F-4505-861B-3A0B31658265?collectionId=91521734-0e0f-434b-bf25-13516d47b1f3&collectionLayerId=49adba0f-1109-48c5-81e2-8e59d15b2e83&mode=build&selected=root-5AA37D8F-FD00-48A0-8251-A73A530FAC99&sha=latest)
=> tweak: Elevator Alert header variable text size

assets/css/v2/pre_fare/normal_header.scss, assets/src/apps/v2/pre_fare.tsx, assets/src/components/v2/lcd/normal_header.tsx, assets/src/components/v2/normal_header.tsx
**Asana task**: [[Bug] Pre-fare screen header text not auto-resizing](https://app.asana.com/0/1185117109217413/1201945334732260/f)
Header was actually working. The wrong `NormalHeader` component was being rendered for Pre-Fare so the `maxHeight` was greater than it should have been. I went ahead and change the header to use the text resizer hook.
=> fix: PreFare header text size

lib/screens/v2/screen_audio_data.ex, test/screens/v2/screen_audio_data_test.exs
I made a small oversight in the original PR and didn't filter audio-only instances by their `audio_valid_candidate?/1` return value. This fixes that.
I also took the opportunity to make the code hopefully more readable.
=> fix: Filter audio-only widgets by `audio_valid_candidate?`

lib/screens_web/views/v2/audio/reconstructed_alert_view.ex
**Asana task**: [Government Center audio error](https://app.asana.com/0/1185117109217422/1202100266982551/f)
GL alerts that affect the whole line no longer have a key for branches. Tweaked some filtering to look for key instead of checking the length of a value that doesn't exist.
=> fix: Reconstructed Alert audio bug for whole GL alerts

lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/widget_instance/audio_only/alerts_intro.ex, lib/screens/v2/widget_instance/audio_only/content_summary.ex, lib/screens_web/views/v2/audio/alerts_intro_view.ex, test/screens/v2/candidate_generator/pre_fare_test.exs, test/screens/v2/widget_instance/audio_only/alerts_intro_test.exs
**Asana task**: [Audio implementation: Audio-only widgets](https://app.asana.com/0/1185117109217413/1202035304691540/f) (Part 2 of a 3-part trilogy)
This defines the alerts intro widget.
=> feat: Alerts intro audio-only widget

lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/widget_instance/audio_only/alerts_intro.ex, lib/screens/v2/widget_instance/audio_only/alerts_outro.ex, lib/screens_web/views/v2/audio/alerts_outro_view.ex, test/screens/v2/candidate_generator/pre_fare_test.exs, test/screens/v2/widget_instance/audio_only/alerts_outro_test.exs
**Asana task**: [Audio implementation: Audio-only widgets](https://app.asana.com/0/1185117109217413/1202035304691540/f) (Part 3 of a 3-part trilogy)
This branch is off of the alerts intro widget branch. Will re-point at the master branch once that one is merged (or maybe GitHub does that automatically?)
=> feat: Alerts outro audio-only widget

config/config.exs, config/test.exs, lib/screens/dup_screen_data/data.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: Adhoc
Headsigns for Govt Center north should be "North Station & North" for PreFare but "Northbound" for DUPs. Split out the data into two config values.
=> Fixed headsigns. Diverges from DUP headsigns

lib/screens/v2/candidate_generator/widgets/elevator_closures.ex
**Asana task**: [Elevator status breaks when there are no elevator alerts](https://app.asana.com/0/1185117109217422/1202101532752129)
When there are no elevator closures, the app breaks. This handles the "nil" value.
=> Handle "no elevator closures" state

lib/screens/v2/widget_instance/audio_only/alerts_outro.ex, test/screens/v2/widget_instance/audio_only/alerts_outro_test.exs
**Asana task**: [Add CTA to end of full-screen takeover audio](https://app.asana.com/0/1185117109217413/1202101941603426/f)
=> fix: Include alerts outro in readout even for takeover alerts

lib/screens/route_patterns/route_pattern.ex
**Asana task**: [Subway Status and Alert widgets don't handle Green Line suspension Lechmere - Government Center](https://app.asana.com/0/1185117109217422/1202101924522475)
=> When fetching station sequences, get them in same direction

assets/src/components/v2/elevator_status.tsx, assets/src/hooks/v2/use_text_resizer.tsx
Text was not resizing properly for some detail pages that show after list pages. Changing the hook used helps with this issue.
=> fix: Text resizing issue for some detail pages.

lib/screens_web/views/v2/audio/elevator_status_view.ex
**Asana task**: [Elevator alert audio not reading periods](https://app.asana.com/0/1185117109217413/1202110379846298/f)
Polly (or the SSML spec, really) does not allow for nested `<s>` (sentence) elements. Internally, Polly converts period-delimited text inside SSML to sentence elements. This means that if you drop a full paragraph of text into a sentence element, it would be interpreted something like `<s><s>first sentence</s><s>second sentence</s>...</s>` which is not valid SSML. To avoid this, Polly silently ignores periods inside of `<s>` elements and we end up with a crazy run-on: `<s>first sentence second sentence ...</s>`.
This means we need to avoid putting the PIO-provided alternate route text inside of an `<s>` element to have it get read out as expected. This change makes that …
=> fix: Move elevator closure alternate route description outside `<s>` tag to allow expected pronunciation of punctuation

lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
This adds an additional check to the `relevant?` predicate to filter out alerts that aren't currently active.
=> fix: Only create reconstructed alert widgets for active service alerts

lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Restrict reconstructed alert widgets to active alerts only](https://app.asana.com/0/1185117109217413/1202112353590269/f)
=> test: Reconstructed alerts candidate generator filters out non-active alerts

assets/src/hooks/v2/use_api_response.tsx, lib/screens/log_screen_data.ex, lib/screens_web/controllers/v2/screen_api_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex
**Asana task**: [Log screen side (left vs right) for Pre-fare screens](https://app.asana.com/0/1185117109217413/1202116831580952/f)
Added `screen_side` to the map we log for requests. Will only exist if `screen_side` is a param in the request, so Pre-Fare will be the only screen that logs it at the moment.
=> tweak: Add screen_side to request logs

lib/screens/v2/widget_instance/departures_no_data.ex, test/screens/v2/widget_instance/departures_no_data_test.exs
**Asana task**: [[Bug] DeparturesNoData throwing error for Bus Shelter screens](https://app.asana.com/0/1185117109217413/1202123170003797/f)
The DeparturesNoData widget was looking for `stop_id` in the header but we do not always put it there. In each V2 config, we place a `stop_id` in the `alerts` section, so I changed it to look there instead.
This solution does fix backend issues for eInk apps, but this widget is still not registered to those components in the front-end. That will be fixed in [this task](https://app.asana.com/0/1185117109217422/1202131702864644/f).
=> fix: DeparturesNoData server error

lib/screens/log_screen_data.ex, lib/screens/screen_data.ex, lib/screens_web/controllers/screen_api_controller.ex, lib/screens_web/controllers/v2/screen_api_controller.ex
**Asana task**: [Log successful API responses](https://app.asana.com/0/1185117109217413/1202116831580950/f)
v1 was already _kinda_ doing this, but was always logging responses with message `[screen api response success]`. I changed that to say the status of the response instead. 
v2 was not doing response logging at all so that was a straightforward addition to the controller logic.
=> feat: Log successful API responses

lib/screens/log_screen_data.ex, lib/screens_web/controllers/v2/screen_api_controller.ex
Didn't think about how `Map.put` returns the updated map and doesn't update map in place, so it wasn't actually doing anything. Also added `screen_side` to response logging.
=> fix: screen_side logging

lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
=> Hotfix: If no stop_ids on an alert, don't try to calculate stations

lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/common/base_alert.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [[Pre-fare] Terminal suspension/shuttle alerts should be full screen](https://app.asana.com/0/1185117109217413/1202176930559885/f)
The way I did this feels messy, so I'm open to suggestions if you agree. I tested this pretty heavily and everything is working as it should, so there may not be any need for changes.
=> tweak: Change boundary shuttle/suspensions at terminals to takeover

lib/screens/log_screen_data.ex
**Asana task**: [🐞 Protocol.UndefinedError: protocol String.Chars not implemented for %{force_reload: false, status: :success, success: false...](https://app.asana.com/0/1185117109217413/1202253017694183/f)
Removed a function clause. Only status is needed so matching to other keys is unnecessary.
=> fix: Response logging error

assets/src/components/v2/elevator_status.tsx
**Asana task**: [[Pre-fare] Inconsistent dates in elevator alert detail view](https://app.asana.com/0/1185117109217413/1202230640868854)
Use LA timezone to shift an "end of service" date on an elevator closure to the previous day.
=> bugfix: Elevator closure timestamp for upcoming events

.github/pull_request_template.md, config/config.exs, config/dev.exs, config/test.exs, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/pre_fare.ex, test/screens/v2/candidate_generator/bus_shelter_test.exs, test/screens/v2/candidate_generator/gl_eink_test.exs, test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [[tech debt] Prevent V3 API (and other external) requests during unit testing](https://app.asana.com/0/1185117109217413/1202094695278057)
Added atom `default_api_v3_url` to force an error whenever an API request is made in a test.
Investigated preventing all HTTPoison requests from occurring during tests, but seems like adding ExVCR is the better solution, which would be a different task from this one.
Fixed tests that were relying on the API.
ALSO test failures were logging to Sentry, so fixed that.
=> Prevent V3 API requests from being added to tests; fixed tests

lib/screens/stops/stop.ex
**Asana task**: [🐞 CaseClauseError: no case clause matching: :error](https://app.asana.com/0/1185117109217413/1202253122085480/f)
When the V3 call fails when fetching routes at a station, the icon list will now just be empty instead of breaking the screen.
=> fix: Elevator route icon map bug

.credo.exs, lib/screens/alerts/alert.ex, lib/screens/bus_screen_data.ex, lib/screens/checks/untestable_datetime.ex, lib/screens/config.ex, lib/screens/departures/departure.ex, lib/screens/dup_screen_data.ex, lib/screens/dup_screen_data/special_cases.ex, lib/screens/gl_screen_data.ex, lib/screens/line_map.ex, lib/screens/psa.ex, lib/screens/solari_screen_data.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/widgets/evergreen.ex, lib/screens/v2/departure.ex, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, mix.exs, test/screens/checks/untestable_datetime_test.exs
**Asana task**: [[tech debt] Prevent creation of "now" and similar values in function bodies](https://app.asana.com/0/1185117109217413/1202112353590272/f)
This adds a custom Credo check that flags usages of `DateTime.utc_now/0` and similar within function bodies, and suggests how to change the code to be testable.
=> chore: Add custom credo check to prevent untestable `now` values in functions

mix.exs
**Asana task**: [[tech debt] Prevent creation of "now" and similar values in function bodies](https://app.asana.com/0/1185117109217413/1202112353590272/f)
While we don't actually use credo in the prod application, the `Credo.Check` module is now required in order to compile our custom check definition in lib/checks/
=> fix: Add credo to prod dependencies so that custom credo check can compile (even though it is not used by the application)

assets/src/components/v2/subway_status.tsx, lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Asana task**: [[Bug] Subway status: abbreviate delays consistently](https://app.asana.com/0/1185117109217413/1202306188159487/f)
`minutes` is now always abbreviated to `m`.
=> tweak: SubwayStatus minutes abbreviations

assets/src/components/dup/README.md
Clarify that first step of DUP packaging instructions is more of a "double check that this is already done" thing
=> Update DUP app packaging README

lib/screens/stops/stop.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
Alerts that affect an entire line were failing to get endpoints and causing screens to error. This changes the logic to return `nil` in those scenarios instead of looking for the endpoints.
=> fix: Recon alerts bug with alerts affecting all stops on a line

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
Wellington station issue:  the code for getting the issue text for an outside suspension attempted to get a destination description, but that doesn't make sense for outside alerts. For example:
With a suspension between North Station and Back Bay, we only want to say "No trains between North Station and Back Bay" at Wellington, not "No North Station trains between..." or vice versa (unless the suspension is only happening in one direction, which is very unlikely.)
Tests updated.
=> Wellington alert bugfix

.github/workflows/deploy-ecs.yml
**Asana task**: [Migrate Screens to ECS](https://app.asana.com/0/1185117109217413/1199929177825008/f)
Created from the `deploy-ecs.yml` [GitHub Action template](https://github.com/mbta/screens/new/master?filename=.github%2Fworkflows%2Fdeploy-ecs.yml&workflow_template=deploy-ecs), with no additional changes.
=> ci: Add "deploy to ECS" GitHub Action config

lib/screens/v3_api.ex
**Asana task**: adhoc
I believe this should increase hackney's checkout_timeout threshold (which we want to be double connect_timeout)
=> Increase checkout_timeout to double the connect_timeout

lib/screens/application.ex
The default size, which we were using previously, was 50. This doubles it to 100.
=> tweak: Increase V3 API connection pool size

assets/src/hooks/use_api_response.tsx, assets/src/hooks/v2/use_api_response.tsx, assets/src/util/sentry.tsx
**Asana task**: [Manually send a Sentry log from client when switching to/from no-data state](https://app.asana.com/0/1185117109217413/1202527610604013/f)
Added a manual Sentry log when a screen enters and leaves a NoData state. This will not trigger when the NoData state appears on page log.
=> feat: log NoData state

assets/css/dup/dup_screen_page.scss, assets/src/apps/dup.tsx, assets/src/components/dup/dup_screen_page.tsx, assets/src/hooks/use_current_dup_page.tsx, assets/src/hooks/use_outfront_station.tsx
**Asana task**: [Set up simulation endpoint in Screens](https://app.asana.com/0/0/1202629970306547/f)
This endpoint will be used by Screenplay to show simulations for DUPs. One change to existing code was needed. Grabbing ad data in DUP and Outfront hooks is not allowed in an iframe. To solve this, I wrapped the variable assignment in a try/catch. This should only impact browser code, but even that has little impact because `mraid` would be undefined there anyway.
=> feat: DUP simulation endpoint

lib/screens/route_patterns/parser.ex, lib/screens/route_patterns/route_pattern.ex
**Asana task**: adhoc
[This error](https://sentry.io/organizations/mbtace/issues/3281205710/?environment=screens-dev-green&project=6061747&query=is%3Aunresolved) appeared in Sentry while testing screen 216 on dev-green. I believe this is due to spotty data in dev-green, but added a handler for it anyway. 
[This error](https://sentry.io/organizations/mbtace/issues/3281204701/?environment=screens-dev-green&project=6061747&query=is%3Aunresolved) also occurs in the same section of code (which re-affirms the idea that this issue is a problem with the dev-green data.) Handled that as well.
=> Bugfix: Sentry MatchError appeared in dev-green

lib/screens/stops/stop.ex
**Asana task**: [Add full-length "Cleveland Circle" name for reconstructed alerts](https://app.asana.com/0/1185117109217422/1202661980135928/f)
I didn't work directly on this code, so I might be missing some context around why these two stops are abbreviated in two different ways rather than the first string in the tuple being unabbreviated like the rest of the entries. Please let me know if there was a reason for this!
(:thinking: Also, should the abbreviation for Washington Square be Wash Sq? Or keep it as-is (Washington))
=> fix: Use full station names where we expect them for Clev Circ, Wash Sq

assets/src/apps/v2/bus_shelter.tsx, assets/src/components/dup/dup_screen_page.tsx, assets/src/components/dup/header.tsx, assets/src/components/eink/bus/header.tsx, assets/src/components/eink/green_line/header.tsx, assets/src/components/eink/screen_page.tsx, assets/src/components/solari/header.tsx, assets/src/components/v2/multi_screen_page.tsx, assets/src/components/v2/pre_fare/viewport.tsx, assets/src/hooks/use_api_response.tsx, assets/src/hooks/v2/use_api_response.tsx, assets/src/hooks/v2/use_audio_readout.tsx, assets/src/util/dataset.tsx, assets/src/util/sentry.tsx, assets/src/util/util.tsx, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/screen/index.html.eex, lib/screens_web/templates/v2/screen/index.html.eex
This PR does the following:
- adds JS utility functions to easily get values from data attributes on the `#app` div, in much the same way that we use `Application.get_env` on the server
- this includes a function, `fetchDatasetValue`, that throws an error if a given key is not present, so that we can avoid ending up with `NaN` (from `parseInt(undefined)`) and other bad values that silently cause problems
- uses the new functions throughout the client code, replacing any JS logic that looks at URL query params in the process
- has the server set new data attributes for `is_real_screen` and `screen_side`.
The overall goal is to standardize our approach to passing values from the server to the client, when the values are constant for the lifetime of the client.
Since …
=> feat: Standardize on using data attributes on `#app` div for "frontend env vars"

assets/css/v2/pre_fare/evergreen/video.scss, assets/src/components/v2/screen_container.tsx
Pre-fare evergreen videos in the large slot were not being given the correct dimensions. Changed it so it fills the whole slot.
=> fix: Adjust CSS for PreFare large evergreen videos.

assets/css/v2/bus_eink/simulation.scss, assets/css/v2/bus_shelter/simulation.scss, assets/css/v2/gl_eink/simulation.scss, assets/css/v2/pre_fare/simulation.scss
**Asana task**: [📺▶️ : 🇵🇱 | Make "speech bubble" around widgets match Figma](https://app.asana.com/0/1185117109217413/1202728175921081/f)
This one was a doozy but I think I got it. Some of the CSS in the existing background was not right/not at all written well so I corrected what I saw. The angled background is done in the `:before` part of the CSS files.
=> polish: Widget sim background

assets/src/util/sentry.tsx
After Sentry is initialized, if screen is a dup, only send logs between 8-8:10am. DUPs will log every time the app appears, which will overload Sentry. Instead, logging only once a day will ensure that Sentry is working as expected.
=> Tweak for DUP Sentry

lib/screens/v2/candidate_generator/pre_fare.ex, test/screens/v2/candidate_generator/pre_fare_test.exs
**Asana task**: [Implement alert experiment: switch left and right pre-fare screens](https://app.asana.com/0/1185117109217413/1202709465836408/f)
See design mock-up in task.
***This should not be deployed until go-ahead is given by design**
=> experiment: Switch sides for pre-fare content

lib/screens/config/v2/pre_fare.ex, lib/screens/config/v2/shuttle_bus_info.ex, lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/widget_instance/shuttle_bus_info.ex, lib/screens_web/views/v2/audio/shuttle_bus_info_view.ex, test/screens/v2/widget_instance/shuttle_bus_info_test.exs, test/screens/v2/widget_instance/shuttle_bus_info_text.exs
**Asana task**: [Create new Shuttle Bus pre-fare widget](https://app.asana.com/0/1185117109217413/1202791356936896/f)
This adds the backend for a new Shuttle Bus widget. Most of the widget will be static text that will live in the frontend. Boarding instructions will be stored in the config along with the arrow icon to use, the minute range, and the destination of the shuttle.
=> feat: Shuttle Bus Widget Backend

lib/screens/config/v2/pre_fare.ex, lib/screens/config/v2/shuttle_bus_info.ex
This change allows PreFares screens to work even if they do not have the shuttle bus widget config.
=> fix: Remove requirement for shuttle bus config

assets/css/pre_fare_v2.scss, assets/css/v2/pre_fare/body_right/normal.scss, assets/css/v2/pre_fare/body_right/surge.scss, assets/src/apps/v2/pre_fare.tsx, assets/src/components/v2/pre_fare/flex/one_large.tsx, assets/src/components/v2/pre_fare/surge_body_right.tsx, lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/widget_instance/shuttle_bus_info.ex, test/screens/v2/candidate_generator/pre_fare_test.exs, test/screens/v2/widget_instance/shuttle_bus_info_test.exs
**Asana task**: [Add new slots to pre-fare template](https://app.asana.com/0/1185117109217413/1202809139605053/f)
Added a new slot for OL Surge widgets: `orange_line_surge_upper` and `orange_line_surge_lower`. Right now, each slot takes up half of the space under the header. If any widget in the `body_right_normal` group has a higher priority, it will not show these new widgets.
=> feat: OL Surge PreFare Slots

config/config.exs, lib/screens/dup_screen_data.ex, lib/screens/dup_screen_data/data.ex
**Asana task**: [DUP: Preserve CR/SL predictions](https://app.asana.com/0/1185117109217413/1202809139605042/f)
The code for this was there, but we needed to change how we determine if a stop has multiple lines. It originally was hardcoded and only Haymarkey met the criteria. Now, it just looks at the number of `sections` in the `primary` of the config. If there is more than one section, show a partial alert on screen 1 and a fullscreen alert on screen 2.
=> tweak: Show partial alerts on DUP screen 1 if configured for CR/SL

lib/screens/config/v2/evergreen_content_item.ex, lib/screens/v2/candidate_generator/widgets/evergreen.ex, lib/screens/v2/widget_instance/evergreen_content.ex, lib/screens_web/views/v2/audio/evergreen_content_view.ex, test/screens/v2/widget_instance/evergreen_content_test.exs
**Asana task**: [Audio equivalence for evergreen content widgets](https://app.asana.com/0/1185117109217413/1202815198320926/f)
This adds audio equivalence to evergreen content. `audio_valid_candidate?/1` will only return true if the widget config actually has a string value. For now, evergreen audio will always have the lowest priority.
=> feat: Audio for evergreen content

assets/css/connection_error.scss, assets/css/screen_container.scss
There was a tiny bit of overflow on the v1 eink screens that was causing a scrollbar to be visible in the Screenplay simulations. Hiding the overflow removes that scrollbar.
=> fix: hide overflow for v1 e-ink

lib/screens/config/dup.ex, lib/screens/config/dup/override.ex, lib/screens/dup_screen_data.ex
**Asana task**: [DUP: Add config option to show a partial alert on the secondary departures (bus) page](https://app.asana.com/0/1185117109217413/1202809139605045/f)
This adds the ability to override the secondary departures screen on DUPs. Right now, only partial alerts can be added. This also changes the config so that we no longer need to override all screens at the same time. A value of `null` can be added for a screen override if we do not need an override for that rotation.
=> tweak: Add overrides for DUP secondary departures

lib/screens/v2/candidate_generator/widgets/alerts.ex
At the moment, the API is having issues with the E branch so our alerts code is failing when getting the stop_sequences for E branch stations. Adding this function clause will allow us to get local alerts even when we cannot get downstream stops from the stop_sequences.
=> fix: Alerts CandidateGenerator function for nil stop_sequences 

lib/screens/config/dup/section.ex, lib/screens/dup_screen_data/request.ex
**Asana task**: [DUP: Config option to filter by direction_id](https://app.asana.com/0/1185117109217413/1202841301882262)
If direction config provided, filter departures by that direction.
I started writing a test, but then didn't see how a test would be useful here, where the direction_id is simply passed as a param to the API query... thoughts on that?
=> Add direction filter config for DUPs

lib/screens/dup_screen_data/request.ex
**Asana task**: [DUP: Abbreviate new long headsigns with "via"](https://app.asana.com/0/1202777352373945/1202809139605048)
I ran through and tested this list (courtesy of Christian).
> Back Bay:
> "Needham Heights via Forest Hills"
> "South Station via Forest Hills"
> "South Station via Ruggles"
> "South Station via Back Bay"
> "Wickford Junction via Ruggles"
> "Providence via Ruggles"
> "Stoughton via Ruggles"
> "Providence & Needham via Forest Hills"
> "Norwood Central via Ruggles"
> "Framingham via Back Bay"
> "Foxboro via Back Bay"
> "Foxboro via Ruggles"
> "Walpole via Ruggles"
> "Forge Park/495 via Fairmount"
> "Forge Park/495 via Ruggles"
> "Worcester via Back Bay"
> "Stoughton via Forest Hills"
> "Wickford Junction via Forest Hills"
> "Providence via Forest Hills"
> 
> Malden …
=> fix[dup]: add new OL surge commuter rail headsign abbreviations

assets/css/dup/dup_screen_page.scss, assets/css/v2/bus_eink/simulation.scss, assets/css/v2/bus_shelter/simulation.scss, assets/css/v2/gl_eink/simulation.scss, assets/css/v2/pre_fare/simulation.scss, assets/src/components/dup/dup_screen_page.tsx, assets/src/components/v2/simulation_screen_container.tsx
**Asana task**: [📺▶️ : 🇵🇱 | Scrollbar in simulations](https://app.asana.com/0/1185117109217413/1202736912335100)
At first, using `margin-left: auto` on the simulation__full-page and `margin-right: auto` on simulation__flex-zone looked to work beautifully, but that margin-right didn't translate to Screenplay through the iframe. This was the result:
So had to get a little fancier with nested containers:  the outer container handles centering; the inner container handles the scroll.  This was applied to all "wide" screen types:  Prefare, Bus Shelter, V2 E-inks, DUPs. The design only shows scrollbars for screens with flex zones, but even the e-inks and DUPs could render weird if the user zooms in even slightly.
=> Custom scrollbar on screen sims

lib/screens/stops/stop.ex
**Asana task**: adhoc
For now, will the whole norther part of the GL is all in-line, PIOs can create alerts that are non-branch-specific, and we can show the endpoints for that alert. For example, shuttling on the D and E starting at Govt Center and northward? We can and show endpoints for that, as if Science Park, Lechmere, and Union Sq are all a part of the GL "trunk" (even though they kinda aren't). When Medford branch pops up, then we'll need to remove these stops.
=> Include the GLX in trunk

assets/css/v2/bus_eink/departures/time.scss
**Asana task**: [[Bus E-Ink] Prediction sizes are consistent with V1](https://app.asana.com/0/1185117109217413/1201542162358586/f)
During migration, the departure time for bus_eink_v2 was decrease by mistake. Bumped it up to match designs.
=> fix: Increase departure time font size for bus_eink_v2

lib/screens/v2/departure/builder.ex
Why didn't we update this sort_by earlier? Was that a tech debt task? I don't see how this would adversely impact the departures on other screens, but also I don't know why we didn't see this bug earlier!
=> Cr departures: Enum.sort_by to look at DateTime

assets/css/connection_error.scss, assets/css/v2/eink/no_data.scss, assets/src/components/eink/no_connection_single.tsx, assets/src/components/eink/no_connection_top.tsx, assets/src/components/v2/eink/no_data.tsx
**Asana task**: [[E-Ink] Add a clock to full screen fallback image](https://app.asana.com/0/1185117109217413/1202593548281747/f)
This should be all places that were missing a clock. `OvernightDepartures` components in v1 and v2 and the v1 `FullScreenTakeover` component already had it.
=> tweak: Add clock to eInk no data state.

assets/css/bus_eink_v2.scss, assets/css/gl_eink_v2.scss, assets/css/v2/eink/departures_no_data.scss, assets/css/v2/eink/no_data.scss, assets/css/v2/gl_eink/body/top_takeover.scss, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/components/v2/eink/departures_no_data.tsx, assets/src/components/v2/gl_eink_double/top_takeover_body.tsx, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/widget_instance/departures_no_data.ex, test/screens/v2/candidate_generator/gl_eink_test.exs, test/screens/v2/widget_instance/departures_no_data_test.exs
**Asana task**: [[E-ink] Add DeparturesNoData component to eInk front-end apps](https://app.asana.com/0/1185117109217413/1202131702864644/f)
Based on the [these designs](https://share.goabstract.com/5961689f-1714-4a37-bcfc-bee55d876aa7?collectionLayerId=42bf6e24-c328-4146-95ec-e1d579e765d1&mode=design). I needed to add to the GlEink template to accommodate a top body takeover.
=> feat: Add DeparturesNoData component to v2 eink

lib/screens/departures/departure.ex, lib/screens/v2/departure.ex, lib/screens/v2/departure/builder.ex, test/screens/v2/departure/builder_test.exs
This was discovered when working on the CR widget updates. When a train is late, the schedule is booted from the list of filtered schedules. So when we merge the schedule with the prediction, the schedule is always `nil`. While we only want to show upcoming schedules in the departures list, late predictions need to be matched with a past schedule. 
Josh Fabian also noticed that Solari screens have the same issue (he captured a clip [here](https://mbta.slack.com/archives/C03K6NLKKD1/p1662042194604599?thread_ts=1662041513.854729&cid=C03K6NLKKD1)). That's the reason for the v1 change.
=> fix: Headsigns for late trains

lib/screens/v2/widget_instance/shuttle_bus_info.ex, test/screens/v2/widget_instance/shuttle_bus_info_test.exs
**Asana task**: [Shuttle Bus Widget: Our travel time estimates for peak / non-peak are not showing up at the scheduled time](https://app.asana.com/0/1185117109217413/1202901200468413/f)
Slight timezone shifting issue. We need to find the time for the service day, so the day we look at is correct. The time we look at should be local time though. Just need to have two separate shifts for date and time.
=> fix: Shuttle Bus time schedules

assets/src/components/v2/cr_departures/cr_departures_table.tsx
Adhoc. [Slack message](https://mbta.slack.com/archives/C039ARUM48H/p1662753971428869?thread_ts=1662749168.276069&cid=C039ARUM48H)
The Spanish for the CR "next train" header needed a fix.
=> Updated the CR "next departure" Spanish header

assets/src/components/v2/cr_departures/cr_departure_time.tsx
When a prediction is valuable (exists and has an assigned vehicle) and it is more than 60 minutes out, we show the clock time instead of a timestamp. Existing logic assumed all predictions are timestamps. Adding a conditional type check helps us determine what to show.
=> fix: CR prediction departure time when time is a string.

assets/src/components/admin/admin_tables.tsx, lib/screens/config/screen.ex
**Asana task**: ad hoc / Screenplay polish
This adds a per-screen boolean field that has no corresponding logic in the Screens app, but lets us hide screens from the listing in Screenplay.
Reasons for hiding a screen include test screens, as well as ones we've configured for non-MBTA locations like stores and libraries.
=> feat: Add per-screen `hidden_from_screenplay` config field

lib/screens/v2/candidate_generator/gl_eink.ex
**Asana task**: [v2 GL e-ink: Switch to headway mode if we fail to fetch departures](https://app.asana.com/0/1185117109217413/1202527610604015/f)
When we fail to get departures from the API, we will now show the headway instead of not showing anything.
=> tweak: gl_eink_v2 show headway on departures API error

lib/screens/v2/candidate_generator/gl_eink.ex
**Asana task**: [🐞MatchError: no match of right hand side value](https://app.asana.com/0/1185117109217413/1202561076967107/f)
Bug in the Sentry link pointed to an API error when getting data for the line map. Changed that function to use a `with/else` so we can allow line map to fail without making the screen go into a no-data state.
=> fix: Prevent crash when line map API fails

assets/src/hooks/use_api_response.tsx, assets/src/hooks/v2/use_api_response.tsx, lib/screens/log_screen_data.ex, lib/screens_web/controllers/screen_api_controller.ex, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_api_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/screen/index.html.eex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Update Splunk E-Ink logging so there are not 2 'source' fields](https://app.asana.com/0/1164574158255689/1203166122404934/f)
There is already a `source` field in E-Ink Splunk logs, so we need to rename the key we use. `requestor` use a suggestion in the original task so I went with that. Open to other ideas though.
=> tweak: Rename source to requestor in logs.

lib/screens_web/controllers/screens_by_alert_controller.ex, lib/screens_web/router.ex, test/screens_web/controllers/screens_by_alert_controller_test.exs
**Asana task**: [Add new screens_by_alert endpoint to Screens server](https://app.asana.com/0/1185117109217413/1203086969471681/f)
This adds the endpoint Screenplay will need to retrieve `ScreensByAlert` data. Endpoint path is `api/screens_by_alert`. Takes a query param `ids` that contains a comma separated list of `alert_ids`. If no param is given or the param is empty, it returns an empty list. Otherwise, it will return a list of `AlertID: ScreenID[]` objects.
=> feat: ScreensByAlert endpoint

lib/screens/log_screen_data.ex, lib/screens_web/controllers/screen_api_controller.ex
**Asana task**: [Specify in logs which DUP screen page we're loading](https://app.asana.com/0/1164574158255689/1203081402939552/f)
Added DUP rotation index to DUP data request logs. The term `page_number` was used in the ticket so I went with that instead of `rotation_index`. Happy to stay consistent if anyone feels strongly about it.
=> feat: Add DUP rotation index to data request logs.

assets/src/util/sentry.tsx, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/screen/index.html.eex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [[Screens] New parameter `disable_sentry` for the 4 first-gen EIGs](https://app.asana.com/0/1164574158255689/1202958313810860/f)
Added option for `disable_sentry` param to be added to URL in order to prevent Sentry from starting in React. If a DSN is present AND it's a real screen AND the param is absent or false, Sentry will run like normal. If `disable_sentry` is true, Sentry will not initialize.
=> feat: disable_sentry query param

lib/screens/v2/alert_widget_instance.ex, lib/screens/v2/screen_data.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Update cached alert => screens data on every v2 screen data request](https://app.asana.com/0/1185117109217413/1203111452890186/f)
Cache will now be updated automatically while a screen is open. Right now, I just have the list of widgets we should cache in a module attribute. I picked this mostly because there are not many right now, and adding to the list is super easy. Feel free to suggest another way to hold this info.
=> feat: Add cache update to framework

config/config.exs, config/test.exs, lib/screens/application.ex, lib/screens/config/screen.ex, lib/screens/config/state.ex, lib/screens/screens_by_alert.ex, lib/screens/screens_by_alert/behaviour.ex, lib/screens/screens_by_alert/gen_server.ex, lib/screens/screens_by_alert/memcache.ex, lib/screens/screens_by_alert/self_refresh_runner.ex, lib/screens/v2/screen_data.ex, lib/screens_web/controllers/screens_by_alert_controller.ex, test/screens/screens_by_alert_test.exs, test/screens_web/controllers/screens_by_alert_controller_test.exs, test/support/mock_v2_screen_data.ex
**Asana task**: [Implement screens-by-alert "self-refresh" mechanism](https://app.asana.com/0/1185117109217413/1203086969471679/f)
The job uses `screens_ttl_seconds` as its run interval.
On each run, it does the following:
1. Get a list of all v2 screen IDs in config that are not hidden from Screenplay,
2. Find which of those have not been updated in the last `screens_ttl_seconds` seconds,
3. Take up to the 20 oldest of those,
4. And run the widget logic on each, concurrently, to update the cache with new data.
I needed to make some changes to the existing screens-by-alert code to allow requesting info on multiple alert IDs, screen IDs, so that we don't overload the cache-interfacing process with messages on each job run, or make separate cache GETs for each ID.
I also added a new …
=> feat: Screens-by-alert self-refresh job runner

lib/screens/application.ex
Disabling the job so it doesn't put unnecessary load on dev or otherwise before other necessary logic is ready.
=> Temporarily disable screens-by-alert self-refresh job until other code is ready

lib/screens_web/controllers/screens_by_alert_controller.ex, test/screens_web/controllers/screens_by_alert_controller_test.exs
We don't want any list of strings to be passed to `ScreensByAlert`, only a list of strings that are valid integers. If any string in the list is not an integer, a status code of 400 is returned.
=> tweak: Validate screens_by_alert query param

assets/src/components/v2/elevator_status.tsx
**Asana task**: [[Pre-fare] Inconsistent dates in elevator alert detail view](https://app.asana.com/0/1185117109217413/1202230640868854/f)
This was fixed a while ago for upcoming alerts, but the problem still occurs on active alerts that end after the current day. Adjusting the end date on active alerts fixes the issue. I also changed how hours are adjusted for end dates. Instead of using LA timezone, I just used moment's `subtract` function.
=> fix: Active Elevator alert end date

assets/src/components/v2/normal_header.tsx
Ad-hoc: When the GLX is deployed in the new GTFS later today, there is one screen that will start using the new destination name (Medford/Tufts) before we want that to be visible. So here's a hardcoded fix that we'll revert Sunday evening (along with deploying other changes)
=> Temporary override for Heath St Sign

lib/screens/stops/stop.ex
We don't seem to need to add anything for these stops to the config.exs file, because none of these new stops have DUPs or Pre-Fare screens.
~Stops were added to stop.ex. Untested, but needs the stops to be assigned to trips in dev-green.~ Has been tested at this point.
To be deployed later, before the opening.
=> Added Medford branch stations to stop.ex

lib/screens/v2/widget_instance/alert.ex
Notion [link](https://www.notion.so/mbta-downtown-crossing/Say-Shuttle-buses-instead-of-Shuttle-in-alert-header-83f8977a055a4bd89551adc87076576b)
The header for shuttle alerts now say `Shuttle Buses` instead of just `Shuttle`.
=> polish: Change header for shuttle alerts.

assets/src/components/v2/gl_eink_double/line_map.tsx
Notion [task](https://www.notion.so/mbta-downtown-crossing/Consider-putting-Washington-Square-on-two-lines-if-possible-c9ac6d354ae940cabd4eedad3d5996b2)
Adjusted max label length because longer stop names look a little crowded.
=> polish: Adjust max label length for line map stop names

lib/screens/v2/screen_data.ex
Notion [task](https://www.notion.so/mbta-downtown-crossing/Bus-alerts-always-show-0-places-even-when-screen-count-is-more-than-0-d860bb7e91fd4756b994ab100d07d312)
For screens refreshing on their own, we were not checking if it is hidden from screenplay before caching. With this check, counts will be more accurate on the Alerts page in screenplay.
=> polish: Prevent caching for hidden screens

lib/screens/v2/widget_instance/alert.ex, test/screens/v2/widget_instance/alert_test.exs
Notion [task](https://www.notion.so/mbta-downtown-crossing/GL-boundary-upstream-and-boundary-downstream-disruptions-should-be-full-screen-not-flex-zone-0828fcf012a54dc581fa26716628e759)
For `gl_eink_v2`, we need boundary suspensions alerts to show if the current stop is inside or on the boundary of the affected stops.
=> polish: gl_eink_v2 takeover alert candidates

lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/widget_instance/departures_no_data.ex, test/screens/v2/candidate_generator/gl_eink_test.exs, test/screens/v2/widget_instance/departures_no_data_test.exs, test/screens/v2/widget_instance/departures_no_service_test.exs
Notion [task](https://www.notion.so/mbta-downtown-crossing/E-Ink-V2-Polish-Punchlist-12bc6f522850471ca01770802a009d97?p=99cf9f899b064ff096d385f2ffad6973&pm=s)
GL e-ink takeover alerts (which replace main content: the departures list and the line map) were not causing the bottom screen to show the "filler" content instead of the usual flex zone.
This was because the GL e-ink template has an extra layout variant intended for the DeparturesNoData widget to be displayed alongside the flex zone. The framework was choosing this variant over the one with the bottom screen takeover/filler content, because the filler widget has a lower priority than any flex zone widget.
As a "surgical" fix, I separated the two cases by having DeparturesNoData use a different slot name. We may want to revisit this …
=> fix: Pair takeover alerts with bottom screen filler on GL e-ink

assets/css/v2/eink/route_pill.scss, assets/src/components/v2/departures/departure_row.tsx, assets/src/components/v2/departures/route_pill.tsx
Notion [task](https://www.notion.so/mbta-downtown-crossing/Reduce-route-pill-text-size-for-higher-number-routes-and-routes-with-letters-cb3119572b7f4a7f81f20fe006a824dc)
If a bus route is > 200 or contains letters, reduce the size to 112px.
=> polish: bus route pill font-size

lib/screens/v2/widget_instance/alert.ex
Notion [task](https://www.notion.so/mbta-downtown-crossing/Alerts-don-t-appear-when-the-home-stop-is-on-the-boundary-of-a-disruption-ecf8d22084c64bf08f7c69bf731507f7)
For V2 bus, we always want to show `boundary_downstream` alerts and want to show `boundary_upstream` alerts for all effects except `:suspension`.
=> polish: Show boundary_downstream/upstream alerts V2 bus

lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/serializer/route_pill_test.exs
Notion [task](https://www.notion.so/mbta-downtown-crossing/Alerts-alway-show-this-branch-as-the-one-impacted-even-if-it-s-an-issue-that-affects-more-than-just--c6ae955d3fc640fabbf0df3da84a7b0c)
For gl_eink_v2 screens, we now show a large GL pill if 3 or 4 branches are affected. If 1 or 2 branches are affected, show small branch pills.
=> polish: Shows GL pill if more than 2 affected branches

lib/screens/v2/widget_instance/departures.ex
Notion [task](https://www.notion.so/mbta-downtown-crossing/E-Ink-V2-Polish-Punchlist-12bc6f522850471ca01770802a009d97?p=e6bd655be398472fb593218f98ef91c1&pm=s)
=> fix: Limit departures widget backend to send up to 15 departures to the client

lib/screens/dup_screen_data/request.ex
**Asana task**: [Add new DUP headsign abbreviation for "Middleborough/Lakeville"](https://app.asana.com/0/1185117109217413/1203658337706587/f)
Instead of adding a new case for every headsign with a `/`, I added a `String.replace` call that looks for a `/` without spaces around it. Needed to use regex to make it happen, but this should keep us from needing a task for each new headsign.
=> tweak: DUP headsign replacement

lib/screens/config/state/s3_fetch.ex
Just a little cleanup.
This reverts a change made a while back to address a temporary issue. I've confirmed that the slot name `medium_flex` is no longer used anywhere in our config.
See #1144, #1145
=> Remove unneeded log/atom

lib/screens/v2/candidate_generator/widgets/alerts.ex, lib/screens/v2/widget_instance/alert.ex, test/screens/v2/candidate_generator/widgets/alerts_test.exs, test/screens/v2/widget_instance/alert_test.exs
**Asana task**: [[GL E-Ink V2] Filter out upcoming alerts](https://app.asana.com/0/1185117109217413/1203637230901491/f)
This PR changes the Alerts widget logic a bit so that we don't get upcoming alerts from the API. Upcoming alerts should not show on any screen, so there is no need for the CandidateGenerator to create a candidate for them. This means that a lot of logic in the `WidgetInstance.Alert` could be removed. We no longer need any conditional checking if the alert is active. It always will be. 
This is version 2 of this task. [Part 1](https://github.com/mbta/screens/pull/1599) used a API filter but that filter is buggy at the moment (see [thread](https://mbta.slack.com/archives/GP5QJM98A/p1674145757579809?thread_ts=1674145440.912979&cid=GP5QJM98A)). To avoid leaving off alerts, I …
=>  tweak: Filter upcoming alerts for Alerts widget

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/screens_by_alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Suppress alert widgets for two alerts weekends of 1/28-29 and 2/4-5](https://app.asana.com/0/1185117109217413/1203840359759366/f)
Tweaked the added function to prevent a couple more alerts. Will show as static content.
=> tweak: Prevent alerts from showing as ReconstructedAlerts

assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/eink/normal_header.tsx, assets/src/components/v2/lcd/normal_header.tsx, assets/src/components/v2/normal_header.tsx, assets/src/components/v2/pre_fare/normal_header.tsx, assets/src/util/util.tsx, lib/screens/v2/widget_instance/normal_header.ex
I did some cleanup while working on the DUP header task, and thought it would be easier to review in a separate PR.
This adds type annotations to the base `NormalHeader` component, and updates related code that uses it.
TypeScript still complains about the `ref` prop on some internal components—I wasn't able to resolve this without making a mess of the code, so I'm leaving it alone.
One small "bug" the new type annotations revealed: the base component does not support `"x"` as an icon name, but the e-ink header component permitted it. I double checked, and this icon isn't used anywhere, so I removed it from the permitted values.
=> Add type annotations to v2 app header components

lib/screens/v2/alert_widget_instance.ex, lib/screens/v2/screen_data.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/elevator_status.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens/v3_api.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/elevator_status_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Add elevator closure alerts to Screenplay](https://app.asana.com/0/1185117109217413/1203785095165730/f)
The Elevator Status widget now reports the IDs of all alerts that make it onto its limited number of pages.
Since Elevator Status has a kind of mini-version of the overall page serialization logic, where some content gets "cut" under certain conditions, we're forced to serialize the widget a second time to get an accurate picture of which alerts it's showing.
---
Due to recent changes that came from Screenplay, I needed to adjust the V3Api module to standardize how it builds the API's url. It now properly forms the url even when the base URL doesn't have a trailing `/`.
=> feat: Report elevator closure alerts to screens-by-alert

assets/css/v2/dup/normal_header.scss, assets/src/apps/v2/dup.tsx, assets/src/components/v2/dup/dup_free_text.tsx, assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/dup/partial_alert.tsx, assets/src/components/v2/dup/takeover_alert.tsx, assets/src/components/v2/normal_header.tsx, docs/tech_specs/dup_v2_alert_widget_backend.md
**Asana task**: [[DUP v2] Partial + Takeover Alerts Frontend](https://app.asana.com/0/1185117109217413/1203830054341502)
To visually test, need to:
- In lib/screens/v2/candidate_generator/dup.ex, need to comment out departures and header instances. Add `%Placeholder{slot_names: [:full_rotation_one], color: :blue}` to the placeholder instances array.
- Make dummy data in lib/screens/v2/widget_instance/placeholder.ex. I added:
```
def serialize(%Placeholder{color: :blue}), do: %{
text: FreeTextLine.to_json(%FreeTextLine{icon: :warning, text: ["No", %{format: :bold, text: "Ferry service"}, "due to dock repairs"]}),
remedy: FreeTextLine.to_json(%FreeTextLine{icon: :shuttle, text: [%{format: :bold, text: "Resumes Oct 12"}]}),
header: %{
text: "Long Wharf South",
color: :teal # | :orange | …
```
=> DUP V2 alerts frontend, phase 2: Partial & Takeover components

assets/css/pre_fare_v2.scss, assets/css/v2/pre_fare/evergreen/image.scss, assets/css/v2/pre_fare/evergreen/video.scss, assets/css/v2/pre_fare/screen/split_takeover.scss, assets/src/apps/v2/pre_fare.tsx, assets/src/components/v2/pre_fare/screen_split_takeover.tsx, lib/screens/v2/candidate_generator/pre_fare.ex, test/screens/v2/candidate_generator/pre_fare_test.exs
We didn't end up needing this layout option for this weekend's disruption, but I already added the code and we might need it in the future! ...Maybe!
=> feat: Add pre-fare layout for two side-by-side full-screen takeovers

config/config.exs, config/dev.exs, config/test.exs, lib/screens/config/v2/departures/headway.ex, lib/screens/signs_ui_config/state/local_fetch.ex, lib/screens/util.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/fixtures/signs_ui_config.json, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/candidate_generator/dup_test.exs, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [[DUP v2] Add headway mode to departures](https://app.asana.com/0/1185117109217413/1203876538101493/f)
This is part 1 to the task above. Only backend is implemented here. This includes test. Two important config values needed here are in the `headway` map of each `section`. One is `headway_id`. This maps to the headway values in `signs_ui_config.json`. The other is `pill`. This is a new value and is used to determine what route pill to show in the headway message. 
As usual, feel free to reach out if you need help testing.
=> feat: DUP V2 Headway Mode - Backend

assets/css/dup_v2.scss, assets/css/v2/dup/simulation.scss, assets/src/apps/v2/dup.tsx, assets/src/components/v2/dup/normal_screen.tsx, assets/src/components/v2/simulation_screen_container.tsx, assets/src/components/v2/simulation_screen_page.tsx
**Asana task**: [[DUP v2] Make v2 DUP screens show up correctly in Screenplay](https://app.asana.com/0/1185117109217413/1203885464554557)
Adjusted the SimulationPage component to watch for an `alternateView` option, which adjusts the type of the widget from `screen_normal` to `simulation_screen_normal`. Might come in handy with other screens in the future.
This is the main work of the task, and there will be a small Screenplay task to follow.
=> Updated DUP simulation for v2

assets/css/dup_v2.scss, assets/css/v2/dup/debug.scss, assets/css/v2/dup/empty_state.scss, assets/src/apps/v2/dup.tsx, assets/src/components/v2/dup/no_data.tsx, assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/dup/page_load_no_data.tsx, assets/src/components/v2/dup/takeover_alert.tsx
**Asana task**: [[DUP v2] No data and disabled states](https://app.asana.com/0/1185117109217413/1204081228664132)
- Added 2 frontend states: loading & disabled/failure states.
- Carried over some functionality from DUP v1: the "debug by printing console logs to the screen" feature and the maintenance code feature (though we aren't using either right now).
- When adding LinkArrow to one of the components, I noticed the LinkArrow in takeover_alert needed fixing.
=> Empty states for DUPs

assets/src/components/admin/devops.tsx, lib/screens/config/devops.ex, lib/screens/solari_screen_data.ex, lib/screens/util.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/departures_no_data.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex, test/fixtures/config.json, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/widget_instance/departures_no_data_test.exs, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [[DUP v2] Handle unreliable predictions (devops checkboxes)](https://app.asana.com/0/1185117109217413/1204081228664130/f)
Spec [link](https://www.notion.so/mbta-downtown-crossing/Departures-Widget-Specification-20da46cd70a44192a568e49ea47e09ac?pvs=4#cb82633f5d314bcfa8974b721d249bd1)
**Backend only**
This PR adds logic for handling the disabled modes checkboxes in the admin tool. This required a departure (heh) from the way we normally render a no data state for the departures widget.
All other V2 screen types display a single section in its departures widget, and that one section only ever contains one mode. DUPs can have multiple sections and each section can be any mode (but never more than one). This means we do not always want to show a full `DeparturesNoData` widget …
=> feat: DUP v2 handle unreliable predictions - Backend

lib/screens/config/v2/departures/section.ex, lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Asana task**: [[DUP v2] Add ability to configure bidirectional departures](https://app.asana.com/0/1185117109217413/1204083894737787)
`"bidirectional": true,` can be an attribute on a primary_departure section. The RL is easiest to test with, because you'll frequently see an Ashmont train back-to-back with a Braintree train, or two Alewife trains back-to-back. But the bidirectional feature only works for 2-row sections, not 4-row. So you'll need to make a fake configuration. (Just copy the secondary bus departures from the Broadway screen to the bottom of the primary_departures screen.)
=> Bidirectional departure sections (for DUP)

assets/css/v2/pre_fare/cr_departures/cr_departures_table.scss, assets/src/components/v2/cr_departures/cr_departures_table.tsx, assets/src/components/v2/cr_departures/overnight_cr_departures.tsx, lib/screens/v2/candidate_generator/widgets/cr_departures.ex, lib/screens/v2/widget_instance/overnight_cr_departures.ex, lib/screens_web/views/v2/audio/cr_departures_view.ex
Minimal changes were needed to get the widget working at Porter. Main changes are bringing in CR-Fitchburg to fetch params and adjusting alignment (Porter won't ever show `via...`). There are still some open design questions, but I wanted to put the changes on someone's radar while we wait for answers.
=> tweak: Update CR widget to support Porter departures

lib/screens/v2/alert_widget_instance.ex, lib/screens/v2/alerts_widget.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/screen_data.ex, lib/screens/v2/single_alert_widget.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/common/base_alert.ex, lib/screens/v2/widget_instance/elevator_status.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
This adds a new protocol for widgets that model a single alert.
The BaseAlert functions now access widget properties exclusively through these functions, so that it has a clearly defined set of requirements for its input values.
The `SingleAlertWidget` and `BaseAlert` protocol & module pair can be thought of as analogous to elixir's [`Enumerable` and `Enum`](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/enum.ex)—the protocol defines the contract for what types of values the module can work with.
=> refactor: Define new SingleAlertWidget protocol and refactor BaseAlert to use it

assets/css/v2/dup/free_text.scss
CSS had a lot of duplicated styles and one unused CSS class. Moved things around so it's a bit more organized. Also fixed some styling with text pills for headway mode on rotations with one section.
=> polish: Cleanup DUP FreeText CSS

lib/screens/config/v2/dup.ex, lib/screens/v2/candidate_generator/dup.ex, test/screens/v2/candidate_generator/dup_test.exs
WTC and Tufts overflow into the time when in the 12 o'clock hours. To prevent this, the header config can now be the string to display on the screen instead of just a `stop_id`. This gives us the flexibility needed to abbreviate words to make headers fit.
=> polish: Add header types DUP v2

lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Asana task**: [[DUP v2] Implement overnight mode for rail](https://app.asana.com/0/1185117109217413/1203876538101495/f)
Minimal changes were needed to get this working for rail. Biggest change is needing to group predictions by their stop _and_ direction. With these, we get a more accurate understanding of what is in overnight mode.
=> feat: DUP v2 Rail Overnight Mode no alert

lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex
A follow-up fix from the DUP alert backend changes!
=> fix: Use route type atoms, not integer IDs, in all API query filters

config/config.exs
**Asana task**: ad-hoc (https://mbta.slack.com/archives/C039ARUM48H/p1679976317919639)
A shuttle alert from Wellington to North Station is crashing the screen because we don't have a headsign matcher for that station. Adding this allows the alert to show correctly with the proper headsign.
=> fix: Add headsign matcher for Wellington.

assets/css/v2/dup/departures/no_data_section.scss, assets/css/v2/dup/free_text.scss, assets/src/components/v2/dup/departures/no_data_section.tsx
Contents of `no_data_section`s were misaligned. Tweaked some CSS so everything renders as designed.
=> polish: No Data Section alignment

assets/src/components/admin/admin_tables.tsx, lib/screens/config/v2/dup.ex, lib/screens/v2/candidate_generator/dup/alerts.ex
**Notion task**: [Long station name “Tufts Medical Ctr” is abbreviated correctly](https://www.notion.so/mbta-downtown-crossing/Long-station-name-Tufts-Medical-Ctr-is-abbreviated-correctly-dbe9b4057bcb4320afd97bdece726907?pvs=4)
Header config was missing from admin tool.
I also fixed the DUP v2 header config so it can use `stop_name`. `CandidateGenerator.Dup.Alerts` was assuming the header config was always given a `stop_id` (which was true when that task was started). Now that it can be a `stop_name`, it needs to check which is being first.
=> polish: DUP v2 admin header config

assets/src/apps/v2/dup.tsx, lib/screens/v2/candidate_generator/dup.ex
**Asana task**: [All placeholder widgets have been removed](https://www.notion.so/mbta-downtown-crossing/All-placeholder-widgets-have-been-removed-87451c0e9dff445483d0a6d0e2750cfa?pvs=4)
Now that we have widgets for every slot, don't need to create placeholders.
=> polish: Remove Placeholder widget

assets/css/v2/dup/normal_header.scss
**Asana task**: [Environment name is displayed on dev and dev-green, and not on prod](https://www.notion.so/mbta-downtown-crossing/Environment-name-is-displayed-on-dev-and-dev-green-and-not-on-prod-8a7cbd1eae6a411f9fe40103f85d5fd1?pvs=4)
Small tweak to make text more readable and not push down other elements.
=> polish: DUP v2 Header Environment Name

assets/css/v2/dup/free_text.scss, assets/css/v2/dup/normal_header.scss, assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/free_text.tsx, assets/src/components/v2/normal_header.tsx, lib/screens/v2/widget_instance/dup_alert/serialize.ex
[Polish](https://www.notion.so/mbta-downtown-crossing/4b67fc8f4ef04868901d85a412cdd48f?v=8c5d6c5153b443a58cedcf0d8b9838d7&p=e39ce62f5a69401bb88dfd633b262aba&pm=s)
When an alert affects multiple station lines and yellow is used, the svg and fonts are dark.
=> Polish: Yellow DUP alerts

lib/screens/v2/widget_instance/dup_alert.ex
**Asana task**: [Page 3/3 layout should match that of page 1/3 when there are no secondary departures configured](https://www.notion.so/mbta-downtown-crossing/Station-closure-inside-1-1-f46b843e4eb842ba9043f3623a420dc6?pvs=4)
[Relevant slack thread](https://mbta.slack.com/archives/C02SXM166N8/p1680186465521599)
I moved the special case for delay alerts, as well as this, into one function to try and avoid confusion.
I'm very open to suggestions on how to organize this logic better, though—does the table approach no longer make sense since the layout for page 2/3 is always full-screen, and the layout for page 3/3 is handled specially?
=> polish: Make DUP 3rd rotation layout depend on whether secondary departures are configured

lib/screens/stops/stop.ex
~~Our `Agent` seems to be saving an empty list at times. When this happens, we still use the `if-modified-since` header which causes the empty list to persist until the response does change. Conditionally adding the header should allow the `Agent` to get back to a good state it somehow saves bad data.~~
Went a different direction. The original logic would still always fail once because we never try again when we get an empty list. New logic adds retries to the fetch. It only retries for empty lists (`v3_api` already has retry logic for failures) up to 3 times. If it's still an issue, we log and the function will still return an empty list. It will not save that empty list to the Agent so in the next refresh it will try fetching again.
=> Add retry logic to routes fetch

lib/screens/v2/candidate_generator/dup/alerts.ex
[Polish](https://www.notion.so/mbta-downtown-crossing/4b67fc8f4ef04868901d85a412cdd48f?v=8c5d6c5153b443a58cedcf0d8b9838d7&p=1c9efef552b3449195de4dd64b9909b9&pm=s)
Kenmore case allows either multiple alerts that affect single branches or one alert that affects multiple branches.
Before:
After:
=> Kenmore case allows alert with multiple branches

lib/screens/departures/departure.ex, lib/screens/util.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/util_test.exs
**Notion task**: [Outstanding issues with overnight mode](https://www.notion.so/mbta-downtown-crossing/Outstanding-issues-with-overnight-mode-040f5c0849ee446d9135409871b50674?pvs=4)
When we change service day at 3am, we were incorrectly switching to a no data state instead of continuing to display overnight mode. To correct this, an extra conditional has been added to check that `now` is before the first schedule of the day.
=> polish: Overnight for early morning

assets/css/v2/dup/departures/no_data_section.scss, assets/css/v2/dup/departures/row.scss, assets/css/v2/dup/departures/section.scss
**Asana task**: [Typical partial alerts are rendered correctly](https://www.notion.so/mbta-downtown-crossing/Typical-partial-alerts-are-rendered-correctly-38f9c0f09f564cb9af5085d435775e0a?pvs=4)
Changed up dividers so they do not show next to a partial alert.
=> polish: departure row dividers

lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
[Main task](https://www.notion.so/mbta-downtown-crossing/4b67fc8f4ef04868901d85a412cdd48f?v=8c5d6c5153b443a58cedcf0d8b9838d7&p=c2a4d8f16e04413b88339f371ce82814&pm=s) and small [added task](https://www.notion.so/mbta-downtown-crossing/4b67fc8f4ef04868901d85a412cdd48f?v=8c5d6c5153b443a58cedcf0d8b9838d7&p=fa794a94178b4582b420a7f83a0241dc&pm=s)
Deciding to show headway or not is decided in the departures candidate_generator, by fetching relevant Alerts for that station, only choosing the first one, and looking at the informed entities. Problem is, we don't simply choose the first alert in the special case at Kenmore; we do some complex logic in the `alert_instances` function. So I could have executed that function again in departure_instances, but I tried something different...
The only …
=> DUP Polish: if all branches have no service, show trunk headways

lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Notion task**: ad-hoc
For GL (mainly Prudential), I noticed that overnight was kicking in when there are no departures and vehicles are still serving trips. This was because we were formatting routes too early. I moved that logic to the `widget_instance` so it is formatted just before sending a response.
=> polish: GL overnight with alert

lib/screens/v2/widget_instance/dup_alert.ex
**Notion task**: [End of disrupted subway service is detected correctly](https://www.notion.so/mbta-downtown-crossing/End-of-disrupted-subway-service-is-detected-correctly-c86eb01642774ae9a93b43e2249bf34a?pvs=4)
When we are overnight but there is an active alert to show on screen, we want widget priority to be fullscreen alert > overnight > partial alert.
=> polish: dup_alert priority

assets/css/dup_v2.scss, assets/src/components/v2/dup/departures/destination.tsx
**Notion task**: [No headsigns overflow 1024px / overlap with the following morning’s schedule time](https://www.notion.so/mbta-downtown-crossing/No-headsigns-overflow-1024px-overlap-with-the-following-morning-s-schedule-time-3344c4da7bf744d3b19f71688a3a6495?pvs=4)
An incorrect CSS class was causing text wrapping on some headsigns. Fixing this class fixed the paging issues. 
I also went ahead and change v2 DUPs to use local Inter files.
=> polish: destination headsign paging fix

assets/src/apps/v2/dup.tsx
**Notion task**: ad-hoc
`responseMapper` was missing in the `MultiScreenPage` props, which was causing some layout issues. Adding it renders the page correctly.
=> polish: DUP v2 all screen URL

assets/css/v2/dup/free_text.scss, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [Multi-line headways accommodate the longest destination](https://www.notion.so/mbta-downtown-crossing/Multi-line-headways-accommodate-the-longest-destination-7de73f5f45064fbbb609d760fb65af66?pvs=4)
Headway messages are too long when headsign is Ashmont/Braintree. Fixed this by condensing `minutes` to `m` for just that headsign. Also fixed some alignment issues for headway pills.
=> polish: ashmont braintree headway message

lib/screens/v2/widget_instance/dup_alert/serialize.ex
**Asana task**: [The smaller alert text size (110) isn’t used anywhere](https://www.notion.so/mbta-downtown-crossing/The-smaller-alert-text-size-110-isn-t-used-anywhere-b38b594224514c25a858218e7f3a320a?pvs=4)
=> fix: No small text in v2 DUP alerts

assets/css/v2/dup/free_text.scss
**Notion task**: [2 sections / both directions done matches design spec](https://www.notion.so/mbta-downtown-crossing/2-sections-both-directions-done-matches-design-spec-eb0cfc74fb0446899d38f304368d72fa?pvs=4)
The scope of this task was text pill alignment (which is fixed), but I see that the text in `overnight-section`s is not in line with the pill. `margin-top: 24px` is actually in the design, so just something that was missed in the original implementation.
Before:
After:
=> polish: overnight-section text margin

assets/src/components/v2/dup/departures/normal_section.tsx
**Notion task**: [Empty section takes up two rows](https://www.notion.so/mbta-downtown-crossing/Empty-section-takes-up-two-rows-9cc6df8eb1284285a0878464bb8abb3c?pvs=4)
Instead of playing with height values for empty sections, we can just not render it if there is nothing to show.
=> polish: Empty section height

assets/css/v2/dup/departures/no_data_section.scss, assets/css/v2/dup/free_text.scss
**Notion task**: [headway_section and no_data_section should only take up one line](https://www.notion.so/mbta-downtown-crossing/headway_section-and-no_data_section-should-only-take-up-one-line-a1d8471b90f14df8bc1a30b28d6b2386?pvs=4)
CSS selectors were not selecting the correct class, so styles were not being applied. I also changed some of the styles so the row matches design.
=> polish: no-data-section CSS

lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/widget_instance/dup_alert/serialize.ex
**Asana task**: [Shuttle, boundary, 1/2](https://www.notion.so/mbta-downtown-crossing/Shuttle-boundary-1-2-911e04408bda44fcaa16ea00db43ed53?pvs=4)
We don't think these types of alerts can happen, but if they do and the directional alert "ends" at a station with a DUP screen, it causes the code for that screen to raise due to not finding an appropriate headsign. (Also, we're not sure what we should display for directional alerts ending at a station since riders can still board trains in both directions there.)
For now, we will have Sentry tell us if this scenario happens, but ignore the alert to be safe. If it does happen IRL, we'll come back and adjust the code to handle directional alerts.
=> Detect, log to Sentry, and discard directional shuttle/suspension alerts

assets/css/v2/dup/alert/partial_alert.scss, assets/css/v2/dup/departures/headway_section.scss, assets/css/v2/dup/free_text.scss, assets/src/components/v2/dup/takeover_alert.tsx, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/dup_alert/serialize.ex, test/screens/v2/widget_instance/departures_test.exs
Adhoc.
Ok, tried to make styles for FreeText more robust for DUPs, but not sure whether it is clearly cleaner. Thoughts?
Adjacent changes:
- Removed styles from other files that refer to DUP free text
- Added line breaks to free text in cases where we want it, instead of doing it with css (more brittle)
- Added border to partial alert because someone noticed it was missing (turns out it was a later change, but oh well, it's added now.)
- Made "seek alternate route" unbold (another late change, but I didn't realize that until I updated it)
=> Making FreeText styles more concise for DUPs

assets/css/v2/dup/departures/headway_section.scss, assets/css/v2/dup/free_text.scss, assets/src/components/v2/dup/departures/headway_section.tsx, assets/src/components/v2/dup/departures/normal_departures.tsx, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
When the change was made to conditional render sections that have something to show, it broke headway `only-child` CSS selectors. When a `headway-section` is displayed with a blank section on the same page, incorrect styles were being applied. I added a new prop to `headway_section`s so we are more confident which style of headway we are showing.
=> fix: headway-section only-child styling

lib/screens/v2/widget_instance/dup_alert/serialize.ex
We thought the boldness was a recent change to the design spec, but it's possible it was just missed in implementation
=> Polish: Might as well bold the dup issue!

.gitignore, assets/src/components/v2/dup/rotation_index.tsx
My change [here](https://github.com/mbta/screens/pull/1719) compiled locally, but not in CI after merge. File is needed because it is referenced in `util.tsx`.
=> fix: React compile error

lib/screens/predictions/parser.ex, lib/screens/stops/parser.ex, lib/screens/stops/stop.ex
**Asana task**: [[fix] Use `platform_code` field on stop data to get CR track number](https://app.asana.com/0/1185117109217432/1204204347671395/f)
Description
This change makes it so that we parse the track number using the `platform_code` field rather than parsing it out of the stop_id.
=> Use platform code to get CR track number

lib/screens/v2/widget_instance/subway_status.ex, lib/screens_web/views/v2/audio/subway_status_view.ex
**Asana task**: [🐞[Screens] Polly announces "meters" instead of "minutes"](https://app.asana.com/0/1185117109217432/1203713399498235/f)
Description
Adds essentially an override for the status readout for the subway status widget.
=> Make Polly read 'minutes', not 'meters'

lib/screens_web/views/v2/audio/cr_departures_view.ex
Hotfix to address Sentry alert caused by attempt to call `Integer.to_string/1` on a string
=> Hotfix: Stop trying to convert track number from integer to string

assets/src/components/v2/simulation_screen_page.tsx
**Asana task**: [Configure Fullstory to capture iframes](https://app.asana.com/0/1185117109217413/1204351329872461/f)
Added this to Screenplay, but misread the docs saying it also needs to be in the app showing in the `iframe`. This is only set in prod on simulation pages, so live screens won't have it.
=> Added window property for js capture in iframes.

lib/screens/v2/widget_instance/serializer/route_pill.ex
**Asana task**: [Fix track numbers](https://app.asana.com/0/1185117109217413/1204606306810793/f)
This changes the route pill display logic to only show track numbers for commuter rail routes, which fixes an issue where some subway routes were inadvertently showing track numbers.
=> Changed track_number to only display for CR.

assets/package-lock.json, assets/package.json, assets/src/apps/solari.tsx, assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/bus_shelter.tsx, assets/src/apps/v2/dup.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/apps/v2/pre_fare.tsx, assets/src/components/v2/simulation_screen_page.tsx, assets/src/util/fullstory.tsx, config/releases.exs, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/router.ex, lib/screens_web/templates/v2/screen/index.html.eex
**Asana task**: [Configure Fullstory to capture iframes](https://app.asana.com/0/1185117109217413/1204351329872461/f)
I believe I misunderstood the docs. Fullstory needs to be initialized in the iframe source domain with the new window attribute. The attribute doesn't do anything on it's own. In order to make sure it is not initialized on live screens, I only add the org ID to `conn.assigns` from the `simulation` endpoint and prevent the frontend from attempting the init on real screens. 
This [PR](https://github.com/mbta/devops/pull/951) must be merged before this one.
=> feat: Fullstory initialization

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/candidate_generator/widgets/alerts.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/v2/candidate_generator/widgets/alerts_test.exs, test/screens/v2/widget_instance/elevator_status_test.exs
**Asana task**: [Explore using a Behaviour to enforce CG naming conventions](https://app.asana.com/0/0/1204505661047502/f)
We decided not to go the `behaviour` route, but there were some useful changes in that PR. This PR isolates those changes so I don't have to go through that branch and remove the `behaviour`.
=> refactor: Alerts CandidateGenerator functions

assets/src/hooks/v2/use_text_resizer.tsx
This allows components using the hook to know when they can apply styles for the "finalized" div, e.g. hiding overflow.
=> feat: useTextResizer indicates when it is done resizing

lib/screens/v2/candidate_generator/dup/alerts.ex
The field needs a type of `list(%{route_id: String.t(), active?: boolean}`, but we were passing a `list(String.t())`.
=> fix: Pass expected type to DupAlert subway_routes_at_stop field

lib/screens/v2/single_alert_widget.ex
The typing for `routes_at_stop` had it returning lists of `%{route_id:, active?:}`, but we actually have more keys in the list's maps, including `type`. This means the seeming error at [this line](https://github.com/mbta/screens/blob/master/lib/screens/v2/widget_instance/common/base_alert.ex#L114) was only due to inaccurate typing.
=> fix: Update typing for SingleAlertWidget.routes_at_stop

lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
E-Ink data needs to be a tad different than LCD. Each route is able to show up to two alerts at all times. Any time an `:extended` alert would be shown, we show a header instead. This means we need to only condense alerts for a route if there are 3+ alerts instead of 2+ alerts.
=> tweak: E-Ink Subway Status backend

lib/screens_web/views/v2/audio/subway_status_view.ex
**Asana task**: [[Subway Status 2.0] Audio implementation](https://app.asana.com/0/1185117109217413/1204531586392668/f)
⚠️ NOTE TO REVIEWER
The last commit significantly complicates the code in order to make the readout more natural sounding. If it seems like too much compared to the branch diff before that commit, let me know and I'll revert.
The "natural" readout generally has about the same playback time as the "non-natural" one—the pauses are just replaced by words.
---
I would also recommend reviewing with the split layout, because I did a from-scratch rewrite of the file. Any code shared with the original is just a coincidence.
=> feat: Updated subway status audio equivalence

lib/screens/alerts/alert.ex, lib/screens/routes/route.ex, lib/screens/stops/stop.ex, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/candidate_generator/widgets/alerts.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/localized_alert.ex, lib/screens/v2/location_context.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/common/base_alert.ex, lib/screens/v2/widget_instance/dup_alert.ex, lib/screens/v2/widget_instance/dup_alert/serialize.ex, lib/screens/v2/widget_instance/elevator_status.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/localized_alert_test.exs
Replaces https://github.com/mbta/screens/pull/1737. Added fetch_location_context to all alert CGs, refactored WidgetInstances to use that context and interact with BaseAlert. 
I marked some ideas for future work with TODO, which I know breaks credo. My question there is, should that work be done now, or can it wait for the future? If it can wait, I'll have credo ignore the line. (I don't think it's a problem to keep TODOs in code as a reminder for future work, but I still want to keep the credo check so it helps catch TODOs we did NOT want to intentionally leave there.)
Tests are in a separate PR: https://github.com/mbta/screens/pull/1743
Needs:
=> Alerts refactor, step 2: Add location context to all WidgetInstances

lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Notion task**: [Extended alerts are shown when ≤1 alert on each line](https://www.notion.so/mbta-downtown-crossing/Extended-alerts-are-shown-when-1-alert-on-each-line-4557e7101c3749b58cafa354fc9b6158?pvs=4)
The logic for serializing a non-GL route with 2 alerts was not quite right when an alert existed on another line. I changed up the conditional so we correctly map each scenario to the correct serialization logic.
=> polish: non-GL multi alert logic

lib/screens/stops/stop.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Notion task**: [Shuttle / extended / part of route](https://www.notion.so/mbta-downtown-crossing/Shuttle-extended-part-of-route-ba411313c5ce4f719f77b4f0d2a8b825?pvs=4)
When a branch alert starts on the trunk, the endpoint logic had a hard time figuring out what branch to look up for stop sequences. I added a `Green` function that just goes through each branch until it finds the correct range of stop sequences.
=> polish: GL Trunk Endpoint Logic

assets/src/components/v2/screen_container.tsx
While working on another task, I noticed that the new error boundary does not play nicely with packaged DUPs. Because Outfront is constantly reloading these pages, I think it's ok to just remove it from DUPs. Open to alternatives though.
=> fix: Prevent Error Boundary on packaged DUPs

assets/src/hooks/v2/use_api_response.tsx, lib/screens_web/controllers/v2/screen_api_controller.ex
**Asana task**: [[DUP v2] Log page numbers](https://app.asana.com/0/1185117109217413/1204606315677357/f)
In the v2 migration, we accidentally removed `page_number` from DUP logs. This PR adds it back.
=> fix: DUP V2 rotation_index logging

assets/src/apps/v2/dup.tsx, assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/normal_header.tsx, assets/src/hooks/use_outfront_player_name.tsx
**Asana task**: [Modify DUP app to use unique screen IDs](https://app.asana.com/0/1185117109217413/1204742012101948/f)
Decided to keep the old hook just so I didn't have to worry about v1 for now. None of those are live anyway. When we tear down the v1 app, we can remove the hook then.
I also created a script for replacing the v2 DUP screens in the config. Would that be useful to check in? I don't foresee needing it again after the first time we use it.
=> tweak: v2 DUP screen IDs

assets/src/components/v2/dup/README.md
The instructions needed to be tweaked a bit now that we no longer reference stations in DUP screen IDs.
=> fix: Updated DUP package README

assets/css/v2/lcd_common_styles/subway_status.scss
**QA task**: [Incorrect type size used for location](https://www.notion.so/mbta-downtown-crossing/Incorrect-type-size-used-for-location-e75cf20a6a08493a8e09df1ee0250fb6?pvs=4)
When the location shares a line with the status, it has a font-size of 27px, not 32px.
=> fix(subway status): Use smaller font-size for contracted alert location text

lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Notion tasks**: [Multiple rows show up expanded](https://www.notion.so/mbta-downtown-crossing/Multiple-rows-show-up-expanded-e54526b1088b4074bb06d12b10f8be12?pvs=4)
[Incorrect station name appears](https://www.notion.so/mbta-downtown-crossing/Incorrect-station-name-appears-20c2bc0377ff495fb16b089b768d0139?pvs=4)
Total alert count logic was off when there was an alert that affected multiple routes. The function now looks at total affected routes and total unique alert IDs and returns the max of the two counts. This allows `:extended` vs `:contracted` logic to pick the correct type.
=> polish: Alert count logic

assets/css/v2/eink/subway_status.scss, assets/src/components/v2/subway_status/eink_subway_status.tsx
**Notion tasks**: [Bypassed station unnecessarily summarized](https://www.notion.so/mbta-downtown-crossing/Bypassed-station-unnecessarily-summarized-5885f654f43e43adb4f33f37c48967dc?pvs=4)
[Suspension bounds unnecessarily omitted](https://www.notion.so/mbta-downtown-crossing/Suspension-bounds-unnecessarily-omitted-927085aa49ab444c9d05b84bfbb38cbd?pvs=4)
[Unnecessary abbreviation on e-Ink](https://www.notion.so/mbta-downtown-crossing/Unnecessary-abbreviation-on-e-Ink-1ba31ff6786d4c5c91c00b189d06550b?pvs=4)
[Delays missing duration](https://www.notion.so/mbta-downtown-crossing/Delays-missing-duration-86f2035c055a4d6ab633b103cf4a00e3?pvs=4)
The `rowHeight` for E-Ink text resizing was a little too small. Increasing it keeps some statuses from being unnecessarily summarized.
=> polish: E-Ink Subway Status text resizing rowHeight

lib/screens/stops/stop.ex, lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Notion task**: [Fix GL branch vs trunk alert](https://www.notion.so/mbta-downtown-crossing/Fix-GL-branch-vs-trunk-alert-d5a287156e734f3d960580ade8591a38?pvs=4)
Our previous branch vs trunk logic was causing some confusion when a branch alert included a stop on the trunk (i.e. GL-C shuttle starting at Kenmore). In summary, the new logic is:
A station closure is a trunk alert if any closed station is on the trunk. Shuttles and suspensions are trunk if the list of affected stops fits in more than one branch. A delay with no stop range is a trunk alert if it affects all branches. Otherwise, it uses the same logic as shuttles and suspensions.
=> polish: branch vs trunk logic

assets/src/components/v2/subway_status/eink_subway_status.tsx
**Notion task**: ad-hoc
Conditional was a touch off. We know we don't need inline pills if the alert is `extended`.
=> polish: inline branch pills

lib/screens/v2/widget_instance/subway_status.ex
I found another edge case 😄 If you have 1 branch alert and 1 multi-line alert that affects GL trunk, it was not being counted as 3 alerts. This was causing the non-GL route to show as `extended` because all GL alerts were counted as affecting a single route. Now, the logic looks at all unique affected routes and recognizes that trunk and branch alerts need to be counted separately.
=> polish: Total alert logic

assets/css/v2/bus_shelter/normal_header.scss, assets/css/v2/eink/normal_header.scss, assets/css/v2/pre_fare/normal_header.scss
Changed positioning to `absolute` so it does not push down the stop name in the header.
=> polish: environment name positioning

docs/tech_specs/0004_store_screen_responses.md
**Asana task**: [[timebox 1d] Evaluate technical options & make go/no-go decision](https://app.asana.com/0/1185117109217413/1204496091984220)
This is a condensed RFC to outline our approach to recording screen responses in S3 and break down the possible budgetary burden. This was generated after loose brainstorming with #ctd-engineering [here](https://mbta.slack.com/archives/GP5QJM98A/p1685559879489779), and then a detailed discussion with @paulswartz. 
Primary goal of making this a shortened RFC is just determining whether the budgetary burden is acceptable to @ryan-mahoney and the CTD Infra team. (I'll have Ryan look first before bugging the Infra team.) If it's not, then we'll need to iterate on alternatives.
=> RFC: Logging screen responses to S3

assets/css/v2/lcd_common_styles/subway_status.scss, assets/src/components/v2/subway_status/lcd_subway_status.tsx, lib/screens/v2/widget_instance/subway_status.ex
**Asana task**: [GL multi-branch station closures omit stops](https://www.notion.so/mbta-downtown-crossing/GL-multi-branch-station-closures-omit-stops-867ac83ee89b4feaa9c1d80386e3d1e6?pvs=4) and ad-hoc
3 big things:
1. Fixed `max-width` so that it adjusts as more branch pills are added.
2. Alert count logic was still a little off. If an alert affects GL at all, count it as 1 alert. No need to only consolidate when all branches are affected.
3. Changed a GL serializer function so that we show the full list of multi-branch station closures.
=> polish: Last minute misc fixes

lib/screens/v2/widget_instance/reconstructed_alert.ex
These alerts will have static images instead of `ReconstructedAlert`s.
=> Added suppression for 4 GL alerts at Gov't Ctr.

lib/screens/application.ex
Adhoc: Erlang VM is crashing, and I'm seeing a lot of Sentry errors related to this. Hopefully this will resolve the crashing.
=> [hotfix] Turn off blue bikes (process is failing)

lib/screens/config/screen.ex, lib/screens/config/v2/ol_crowding.ex, lib/screens/config/v2/triptych.ex, lib/screens/v2/candidate_generator/triptych.ex, lib/screens/v2/screen_data/parameters.ex, test/screens/v2/candidate_generator/triptych_test.exs
**Asana task**: [New screen app: backend](https://app.asana.com/0/1185117109217413/1204882696236162)
Checklist: https://www.notion.so/mbta-downtown-crossing/New-Screen-App-Checklist-dd8a2678ba294af6ac07d7a2508e49ff
=> [app setup] Basic files for new triptych app

lib/screens/route_patterns/route_pattern.ex, lib/screens/stops/stop.ex, lib/screens/v2/candidate_generator/widgets/alerts.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/location_context.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/route_patterns/route_pattern_test.exs, test/screens/v2/candidate_generator/widgets/alerts_test.exs, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs, test/screens/v2/localized_alert_test.exs, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/dup_special_case_alert_test.exs, test/screens/v2/widget_instance/elevator_status_test.exs, test/screens/v2/widget_instance/reconstructed_alert_property_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
This stores some extra data in the `LocationContext` struct, which is useful for disruption diagrams for now, and maybe other things in the future.
Code expecting the original, untagged list of stop sequences can now get it by calling `LocationContext.stop_sequences(location_context)` if it's already inside the struct, or `RoutePattern.untag_stop_sequences(tagged_stop_sequences)` if handling the tagged sequence map directly.
=> In LocationContext, tag stop sequences by their routes

assets/tsconfig.json
This stops vscode from incorrectly, and inconsistently, flagging various aliased imports as duplicate-imports, and other confusing behavior.
This fix is purely "cosmetic"—the webpack config to resolve aliases was already correct so the code was being compiled/bundled correctly; this just fixes the TS counterpart so that our editors don't raise false alarms all over the place.
=> fix: Tweak config so vscode can consistently resolve aliased import paths

assets/css/v2/pre_fare/simulation.scss, assets/src/apps/v2/pre_fare.tsx, assets/src/components/v2/pre_fare/simulation_screen_container.tsx, assets/src/components/v2/pre_fare/simulation_screen_page.tsx, lib/screens/v2/screen_data.ex
**Asana task**: [[Pre-Fare Alerts] "New look" in Screenplay](https://app.asana.com/0/1185117109217413/1205259333913109/f)
Now that there are two different "flex zones" on PreFare screens, a little tweaking was needed so users can see all pages on both screens. To make things simpler, PreFare has its own set of simulation components and CSS. A single server change was needed so grouping logic did not incorrectly group pages with the same page number of different screens.
=> tweak: PreFare simulations

assets/src/apps/admin.tsx, assets/src/components/admin/admin_navbar.tsx, assets/src/components/admin/admin_tables.tsx
**Asana task**: [Triptych: Add to admin tool](https://app.asana.com/0/1185117109217413/1205259332301425/f)
This just adds the usual textarea columns for the two config fields we have so far in the triptych app: train crowding and local evergreen sets.
(`local_evergreen_sets` will replace `evergreen_content` in the config definitions soon, in Hannah's PR)
A column for configuring the "version+player name displayer" will be added in the PR that adds that feature.
=> feat: Add admin config columns (thus far) for triptych app

lib/screens/log_screen_data.ex
Little fix for an issue I noticed while poking around. This change lets the server properly log data requests from unrecognized screens, and send back 404s.
=> fix: Handle unrecognized screen IDs in `screen_name_for_id`

assets/src/hooks/v2/use_api_response.tsx, lib/screens/log_screen_data.ex, lib/screens_web/controllers/v2/screen_api_controller.ex
**Asana task**: [Include version param in data requests from OFM client apps](https://app.asana.com/0/1185117109217413/1205368149479985/f)
Quick 'n simple 😎
=> feat: Send and log version in data requests from OFM clients

lib/screens/log_screen_data.ex, lib/screens_web/controllers/v2/screen_api_controller.ex
**Asana task**: ad hoc?
This just adds and uses a `log_unrecognized_triptych_player` function. The rest of the changes are from my adding an alias + the formatter adjusting indentation.
=> Add a new log fn for unrecognized triptych player name

assets/src/components/v2/train_crowding.tsx
**Asana task**: ad hoc / polish
Prettier made some formatting changes. The only real change is "D" -> "d" on line 250.
=> fix: Lowercase "d" in "No data" label

assets/src/components/v2/triptych/triptych_three_pane.tsx
Panes besides the displayed one now only render the identifiers, just in case something has gone really wrong and we're seeing those for some reason. (Plus, they aren't expensive to render)
Screenshot 👇 notice that the `.left-pane` and `.right-pane` elements have no children since they are outside the viewport.
=> tweak(triptych): Do not render slots outside the viewport when using the 3-slot split layout

assets/src/components/v2/triptych/README.md, assets/src/util/outfront.tsx
Ah! OFM tags are in the form `Triple_Left` instead of with a hyphen.
=> [bug] OFM tags use underscore instead of hyphen

lib/screens/v2/candidate_generator/widgets/train_crowding.ex
I forgot to check `next_train_prediction` for `nil` when logging. This is causing a good amount of errors overnight when all predictions are `nil`.
=> fix: nil check in logging conditional

lib/screens/v2/candidate_generator/dup/departures.ex
**Asana task**: [[DUP v2] Timebox: Investigate slowness fetching data](https://app.asana.com/0/1185117109217413/1204606315677361/f)
Added a conditional that checks if there is room for overnight rows before running the logic. The logic itself is slow (Part 2 of this task is improving that overall) so we should avoid running it unless we think we need to.
=> tweak: Improve DUP overnight performance pt 1

lib/screens/config/screen.ex, lib/screens/config/state.ex, lib/screens/screens_by_alert/self_refresh_runner.ex, lib/screens/v2/screen_data/parameters.ex
In preparation for triptychs appearing in Screenplay, this prevents the screens-by-alert self refresh job from wasting effort on triptychs since they never show alerts and are likely to load less frequently than the cache TTL.
👉 I tried to put the list of non-alert-showing screen types in a high visibility spot, since we'll need to keep it manually updated. (I couldn't think of a simple programmatic way to determine whether a given screen can show alert widgets.)
I'm very open to suggestions on this, though. Either a way to make the list even more visible, or a way to automatically determine this screen type trait.
=> tweak: Exclude triptychs from self-refresh job; Move unrelated logic out of Screens.Config.State

scripts/build_triptych_config.ts
**Asana task**: [Synthesize Outfront + station survey docs into draft triptych screen configs](https://app.asana.com/0/1185117109217413/1205368149479989/f)
I wrote this script to help me avoid some typos/mistakes while building the triptych config.
I figured it might be worthwhile to save this for later, in case we need to mass-configure the triptychs on another subway line in the future.
=> Add script used to assist with building triptych screen config

lib/screens/log_screen_data.ex, lib/screens_web/controllers/screen_api_controller.ex, lib/screens_web/controllers/v2/screen_api_controller.ex
This will help us match up logs with real screens, and make sure that the placement of each player matches up with what OFM's station maps said.
=> tweak: Include triptych player name in data request logs

lib/screens_web/controllers/v2/screen_api_controller.ex, lib/screens_web/router.ex
**Asana task**: ad hoc / triptych app troubleshooting
Changes:
- Add `/log_frontend_error` to endpoints reachable by OFM clients
- Add some basic defensive logic to it since it's more permissive now, and accepts data from clients
- Add a function to handle the "preflight" OPTIONS requests that clients fire before sending their POST requests—another part of the CORS protocol
Tested manually with a client package that POSTs to this endpoint.
=> tweak: Adjust routes/endpoints to accept error logs from OFM clients

lib/screens/ol_crowding/dynamic_supervisor.ex, lib/screens/ol_crowding/logger.ex, lib/screens/screens_by_alert/memcache.ex, lib/screens/screens_by_alert/self_refresh_runner.ex, lib/screens/util.ex
Child processes of Task.Supervisors do not expire, even if they are meant to be temporary. We need to explicitly end the process if it's running too long. At the moment, the timeout is set for 10s.
=> [fix] Explicitly expire child processes of a Task.Supervisor

lib/screens/v2/widget_instance/reconstructed_alert.ex
Tweaked the logic so we do not show an alert for the Haymarket closure on Tufts and Back Bay Pre-Fare screens.
=> Changed temporary override logic.

lib/screens/v2/widget_instance/reconstructed_alert.ex
Putting the alert back on shortly after the GM demo.
=> Revert "Changed temporary override logic."

lib/screens/v2/widget_instance/dup_alert.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: ad hoc?
The two alerts are "two sides of the same coin"—one informs southbound trips and the other northbound, because using a single alert for both directions caused problems for JFK countdown clocks.
=> tweak: Suppress automated alerts on pre-fares & DUPs, for October RL maintenance diversion

lib/screens/ol_crowding/logger.ex, lib/screens/util.ex, lib/screens/v2/candidate_generator/widgets/train_crowding.ex, lib/screens/v2/widget_instance/train_crowding.ex, lib/screens/vehicles/carriage.ex, lib/screens/vehicles/parser.ex, test/screens/v2/widget_instance/train_crowding_test.exs
**Asana task**: [OL Crowding: Crowding Level Adjustments](https://app.asana.com/0/1185117109217413/1205660768175007/f)
Updated crowding level translation to use `occupancy_percentage` when there is data.
=> tweak: Crowding level translation

test/screens/v2/disruption_diagram_test.exs
**Asana task**: Pre-fare integration QA (not linking it because I don't want the Asana integration to move the task to "in review", since there will be many other PRs associated with it.)
This was actually working as intended already, [see comments on the issue.](https://www.notion.so/mbta-downtown-crossing/diagram-backend-Diagram-omitting-incorrect-station-f1b83657936e436897b0e0635bd2d33c?pvs=4)
I've added a unit test for this scenario, with comments marking the different regions of the diagram.
=> test: D. diagram unit test for RL trunk station closure with home stop at Ashmont

assets/css/v2/pre_fare/prefare_single_screen_alert.scss, assets/src/components/v2/pre_fare_single_screen_alert.tsx
**Notion task**: [[alert, frontend] alert card missing top margin when banner is omitted](https://www.notion.so/mbta-downtown-crossing/alert-frontend-alert-card-missing-top-margin-when-banner-is-omitted-5969b6cfd32d4dd599bff01d43cfd230?pvs=4)
Added padding to layout if there is no banner.
=> Added padding-top to layout when there is no banner.

lib/screens/route_patterns/route_pattern.ex, lib/screens/stops/stop.ex
**Notion task**: [[regression] Possible regression for DUP backend / RoutePattern stop sequence functions](https://www.notion.so/mbta-downtown-crossing/regression-Possible-regression-for-DUP-backend-RoutePattern-stop-sequence-functions-55e3dc918a4d421baed00c94057c9c73?pvs=4)
This fixes a couple silly mistakes I made in my changes to the stop-sequence-fetching functions:
1. When the new `canonical_only?` argument was a non-Boolean, it was setting the query params to `nil` since the `if` didn't have an `else` clause.
2. For DUP and triptych apps, we were passing `false` for `canonical_only?`, which caused the V3 API to only return _non-canonical_ route patterns. So, just the weird ones that we don't want.
=> fix: Make stop sequence fetch work again for non-pre-fare apps

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
**Asana task**: [[diagram, frontend] “to KENMORE & WEST” label split onto 2 lines](https://www.notion.so/mbta-downtown-crossing/diagram-frontend-to-KENMORE-WEST-label-split-onto-2-lines-ab8547b13035453aa9fb82871fd15366?pvs=4)
Changed label to one line.
=> Changed label to display on a single line.

assets/css/v2/pre_fare/disruption_diagram/disruption_diagram.scss
**Notion task**: [[diagram, frontend] “to” in destination arrow labels should not be bold](https://www.notion.so/mbta-downtown-crossing/diagram-frontend-to-in-destination-arrow-labels-should-not-be-bold-4e863fd5b7cc479ea27117ee5e6d00b1?pvs=4)
Removed bolding of `to` in arrow labels.
=> Removed bolding of 'to' from arrow labels.

lib/screens_web/views/v2/audio/reconstructed_alert_fullscreen_view.ex
**Notion task**: [[audio] Banner readout omits “line”](https://www.notion.so/mbta-downtown-crossing/audio-Banner-readout-omits-line-4716f29b47e14a8c96b414ed61cb6418?pvs=4)
`Line` was missing in audio.
=> Added missing word.

lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: [[frontend] Terminal station closure causes JS errors](https://www.notion.so/mbta-downtown-crossing/frontend-Terminal-station-closure-causes-JS-errors-7f00d9f3653d43d4a048c2be61328044?pvs=4)
This ended up being a server issue. When building the banner, we use the `North Station & North` icon in the banner but the headsign was only `North Station`. Because the key was missing, the svg filename was `nil`.
=> Fixed D branch headsign.

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
**Notion task**: [[diagram, frontend] Incorrect symbol for “you are here” + “shuttled” combo](https://www.notion.so/mbta-downtown-crossing/diagram-frontend-Incorrect-symbol-for-you-are-here-shuttled-combo-ddf95fe7475b4357883ed13b4046d040?pvs=4)
See title.
=> Fixed icon display when current stop is affected.

lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [Mercury: Departures in Epoch Time](https://app.asana.com/0/1176097567827729/1205730972991228/f)
Added `time_in_epoch` to serialized response for e-ink. The addition of the attribute does not affect any of our client code.
=> tweak: E-Ink departure_time in epoch

lib/screens/alerts/informed_entity.ex, lib/screens/stops/stop.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Notion task**: [[alert, frontend] Inconsistency? With affected stop range description](https://www.notion.so/mbta-downtown-crossing/alert-frontend-Inconsistency-With-affected-stop-range-description-9571590061054c859e4b0d0d3f95555b?pvs=4)
I ended up making a relatively narrow change to `get_endpoints` for this, instead of actually changing the widget struct's data directly.
The idea is that this is presentational in the same way as formatting a DateTime is. The logic can still work under the assumptions that all stop sequences are in direction ID 0 order, and we only flip it, as needed, when "presenting" it in the serialized response.
=> feat: Consistent description of disrupted stop ranges throughout pre-fare alerts

assets/src/components/admin/admin_tables.tsx
Adhoc, to make my life easier!
=> Added audio column to GL & PreFare in admin table

assets/src/components/v2/elevator_status.tsx
Slack thread for context: https://mbta.slack.com/archives/C4K7CFULT/p1699306126326219
Tl;dr: Some elevators do not have posted numbers. In those cases, a fake ID is assigned. We need to make sure that the ID is actually a number before displaying it.
=> fix: Add filter to make sure ID is a number.

config/config.exs, lib/screens/v2/widget_instance/reconstructed_alert.ex
We were using a destination string with a backslash ("No trains to Ashmont/Braintree") instead of with an "&" as [designed](https://www.figma.com/file/l4AZl8UXyKLAFI8OtultQk/Pre-Fare-%E2%80%94-Alerts-V2?type=design&node-id=562-13987&mode=dev), and it was messing up the issue formatting.
=> Pre-fare alert fix: Ashmont & Braintree string formatting

assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/gl_eink.tsx, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/router.ex
Phoenix normally expects a CSRF token with any POST requests to an endpoint that uses the `:browser` pipeline.
The widget endpoint is an exception, since it's basically an HTML page GET request, but we can't pass a body with a GET request.
This removes CSRF protection from the widget endpoint.
---
I also got the GET version of the endpoint working again with some fiddling! Wasn't sure how to directly test it otherwise, besides manually inspecting HTML received in Postman.
You can test the GET version with URLs like so:
```
localhost:4000/v2/widget/gl_eink_v2?widget={%22mode_cost%22:%22$2.40%22,%22mode_icon%22:%22subway-negative-black.svg%22,%22mode_text%22:%22Subway%22,%22text%22:%22For%20real-time%20predictions%20and%20fare%20purchase%20locations:%22,%22type%22:%22f …
```
=> fix: Skip CSRF protection on /widget POSTs since they really fetch a new HTML page

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
For some reason, Firefox is consistently leaving `isDone` as `false`. This means that the `visibility` on the svg stays `hidden` even after resizing is done. I think this is because Firefox needs updated dimensions each time the hook executes. After making this change, FF is now flipping `isDone` after resizing work is complete.
**This PR seems much bigger than it is because of formatting. The only change that was made to logic is in commit `a1390ee9beaa78b8df2fc919507f5877c3c07df9`. The second commit only includes formatting changes.
=> polish: Recalculate dimensions in hook

lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex
**Asana task**: [Screens behavior in preparation for the GL surge](https://app.asana.com/0/1185117109217413/1205920140277912/f)
Added Gov't Ctr suppressions for the GL surge. Will be replaced with a full screen image on the left.
=> Added suppressions for GL Surge.

lib/screens/signs_ui_config/state/parse.ex
We won't do anything for now when signs are in that mode; this change just prevents the parsing logic from failing on it.
=> tweak: Accept `temporary_terminal` mode in signs UI config

lib/screens/signs_ui_config/state/parse.ex
Prevent new sign modes from breaking signs UI parser, since we really only care if the mode is "headway" or not.
=> tweak: Prevent new sign modes from breaking signs UI parser

lib/screens/route_patterns/route_pattern.ex, lib/screens/v2/candidate_generator/dup/departures.ex
When the current station is closed, there are no active routes at that station. This trips up location context code a little because we always assumed that at least one route would be active. Added a new case to catch that and return `:error` so logs will show what happened while allowing the screen to load.
=> fix: current station is closed and has no active routes.

lib/screens/v2/candidate_generator/bus_eink.ex, lib/screens/v2/candidate_generator/bus_shelter.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/candidate_generator/solari.ex, lib/screens/v2/candidate_generator/solari_large.ex, lib/screens/v2/candidate_generator/triptych.ex
elixir-lang/elixir#11760
We're on elixir 1.13 in our deployment environments, and it seems to still suffer from this bug.
Removing `ordered: false` shouldn't make a difference here--the number of tasks spawned is small and the stream is immediately passed to `Enum.flat_map`, which needs to get the full list of resulting widget instance structs before it can return anything anyway.
=> tweak/fix: Remove `ordered: false` from Task.async_stream calls to avoid process leak

lib/screens/v2/widget_instance/normal_header.ex, test/screens/v2/widget_instance/normal_header_test.exs
**Asana task**: [[Mercury] Remove clock from takeovers](https://app.asana.com/0/1185117109217413/1206070378353406/f)
Relevant Slack link: https://mbta.slack.com/archives/C059FPCQBNG/p1701294833473189
Their client solution for the header is to render their clock instead of ours. That works for widgets that calculate time in the client, but times sent from the server need to be removed. I believe `NormalHeader` is the only widget these screens use that gets its time from the server. I added a pattern for `vendor: :mercury, app_id: :gl_eink_v2` that will send the same response as before with the time removed. The missing data does not produce any errors, just prevent time from rendering. For this to work, we need to make sure `vendor` is set correctly on the screen configs.
=> tweak: Remove clock on Mercury E-Ink screens.

assets/css/v2/pre_fare/alert-banner.scss, assets/css/v2/pre_fare/prefare_single_screen_alert.scss, assets/src/components/v2/pre_fare_single_screen_alert.tsx
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=13aa9bc00369477387eea57175a34294&pm=s)
During implementation, it was assumed that all alerts would need to have font resized, but it seems that really it's only explicitly designed for station closures. All other fonts are static.
Also, it turns out the max height for the text is also [defined in the design](https://www.figma.com/file/l4AZl8UXyKLAFI8OtultQk/Pre-Fare-%E2%80%94-Alerts-V2?type=design&node-id=558-14241&mode=dev), and we don't need to do all those funky calculations with bannerHeight, etc.
=> fix: Pre-fare polish -- Text only resizes for bypassed stations

assets/css/v2/pre_fare/alert-banner.scss, assets/css/v2/pre_fare/prefare_single_screen_alert.scss, assets/css/v2/pre_fare/reconstructed_alert.scss, assets/src/components/v2/pre_fare_single_screen_alert.tsx
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=25d66d44207748ce955a5b90501f89c4&pm=s)
Small, easy fix for the text wrapping
=> fix: Pre-fare polish -- Station closed takeover text wrapping

lib/screens/v2/widget_instance/reconstructed_alert.ex
Updated IDs to suppress at Gov't Ctr during the surge.
=> 2024 GL Surge alert suppressions

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
[Notion task](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=6271faa6312e49b8952ea243ff73fc5a&pm=s)
Before:
After:
=> fix: Pre-fare polish -- Downstream shuttle endpoint should be a circle

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=0d9a7ffb8efb48adae436848340585e9&pm=s)
Lol, I'm definitely the one who messed this up! All better now
=> fix: Pre-fare polish -- Fix Medford/Tufts & Union Sq label

lib/screens/v2/widget_instance/reconstructed_alert.ex
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=477e30f7b8444c129eb27be7a2642150&pm=s)
=> Prefare headsigns in config is "Ashmont & Braintree" not "Ashmont/Braintree"

assets/css/v2/pre_fare/reconstructed_alert.scss
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=505c4dc5144c46c79472a8da02a2a545&pm=s)
=> fix: Prefare polish -- Sub-header for takeover alert is now regular weight

assets/css/v2/pre_fare/free_text.scss, assets/src/components/v2/reconstructed_takeover.tsx, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens_web/views/v2/audio/reconstructed_alert_fullscreen_view.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=0f0b87cc98f349e3a4469b7d6849bca9&pm=s)
😐 ok maybe this is janky a little, but maybe it still works??
=> fix: Prefare polish -- Use FreeText to prevent station text wrapping in subheaders

assets/src/components/solari/screen_container.tsx, assets/src/components/solari/section.tsx, assets/src/components/solari/section_list.tsx, assets/src/components/solari/section_list_container.tsx
**Asana task**: [GL Surge - swap departures language for Solari screens](https://app.asana.com/0/1185117109217413/1206288246229604/f)
At the request of OIOs, we need to temporarily change the GL row text at Haymarket to `Service Suspended`. I hardcoded the date range so we won't need another deploy (unless dates change for some reason).
=> temp: Change NoDeparturesMessage for Haymarket during surge.

lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens/v2/widget_instance/subway_status.ex, lib/screens_web/views/v2/audio/content_summary_view.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs, test/screens/v2/widget_instance/subway_status_test.exs
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=cab9f47a242e4d7e9d878c8f9cf76dab&pm=s)
=> fix: Prefare polish -- Reorder audio with alerts before subway status

assets/src/components/v2/disruption_diagram/disruption_diagram.tsx
[Notion](https://www.notion.so/mbta-downtown-crossing/fd75b83b5904405fbc71ffbcdd0cec47?v=d4971a59c7eb45ae9841e522c53ad368&p=2c3e2b67a4b04748a7371d066b003817&pm=s)
Only abbreviate station names if they are a part of a short list of stations. 
Along the way, this fixed also revealed a situation where I noticed the diagram was getting mis-sized, and a long station name was getting cut off. Turns out that the font can take so long to render Inter that the useEffect hook thinks the diagram is smaller than it is and scales it up too much. Added a lil setTimeout on the whole hook to delay it a tiny bit longer so the font can render.
=> fix: Prefare polish -- New abbreviation rule

lib/screens/v2/widget_instance/line_map.ex
**Asana task**: [[Mercury] Add epoch time to vehicles on line diagram](https://app.asana.com/0/1185117109217413/1206443958613162/f)
Added `time_in_epoch` to line map vehicles for Mercury. Will only be used in their code.
=> tweak: add time_in_epoch to line map vehicles

assets/css/v2/pre_fare/simulation.scss, assets/src/components/v2/disruption_diagram/disruption_diagram.tsx, assets/src/components/v2/pre_fare/simulation_screen_container.tsx, assets/src/components/v2/pre_fare_single_screen_alert.tsx, assets/src/components/v2/reconstructed_takeover.tsx
[No task]
Gosh this was a wonky thing to fix. It was most complex in situations where there were two diagrams in the simulation for multiple disruption pages. I tried to clear things up with comments, but now the file is so so full of comments that it might be a bit overzealous. Let me know what you think!
=> fix: Prefare alerts polish -- Screenplay sim sizing / page layout

assets/css/bus_eink_v2.scss, assets/css/bus_shelter_v2.scss, assets/css/dup/dup_screen_page.scss, assets/css/dup_v2.scss, assets/css/gl_eink_v2.scss, assets/css/pre_fare_v2.scss, assets/css/triptych_v2.scss, assets/css/v2/bus_shelter/simulation.scss, assets/css/v2/dup/simulation.scss, assets/css/v2/gl_eink/simulation.scss, assets/css/v2/pre_fare/simulation.scss, assets/css/v2/simulation_common.scss, assets/css/v2/triptych/simulation.scss
Task: [[Perm config] Pending screen page](https://app.asana.com/0/1185117109217413/1205973195471510/f)
The Pending page uses a darker background color for its screen simulations, than that used by the Places page.
Screen simulations previously assumed they would always have a #3d5366 background color--this changes things so that they use a transparent background. Tested and working properly in Screenplay on Firefox & Chrome.
This approach seemed more straightforward than adding support for a `?background_color=_` param on /simulation urls.
=> tweak: Give screen simulations transparent backgrounds for better integration with Screenplay UI

.devcontainer/Dockerfile, .tool-versions, Dockerfile
This is required to allow development on Apple Silicon hardware, since Node 14 is old enough that it can't be compiled (and has no precompiled binaries) for `arm64`.
This version of Node is unfortunately still past its End-of-Life (see https://github.com/nodejs/Release), but it is the newest version that works with our current frontend dependencies, in particular Webpack 4.
---
To get some confidence this won't impact anything, I built two Docker images locally, one with the Node 16 change in the `Dockerfile` and one without, then extracted and diffed their `/root` directories (where the app is built). They were identical except for the Phoenix asset digest, which only had differences in the timestamp field; this seems to record the time the asset was built, so the difference is expected.
=> chore: upgrade to Node 16

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Bug: GL text can appear on RL pre-fare alerts](https://app.asana.com/0/1185117109217413/1206815194782600)
It's a little tricky figuring out which RL destination sign to show when the alert affects both the RL trunk and branch. So here are the cases we need to support
- issue is downstream, JFK - Ashmont and no Braintree stations included: should say riders to Ashmont
- issue is downstream, Broadway - Ashmont: should say riders to both branches
- issue is downstream, JFK - Braintree and no Ashmont stations included: should say riders to Braintree
Omitting the branching node (JFK) helps us decide whether the trunk/branch is affected
=> Skip node station when determining which RL branches are affected by alert

.github/workflows/asana-pr-opened.yml
Two small changes:
* Add an explicit action version, as the `latest` tag is apparently not being updated to consistently point to the actual latest version.
* Add a conditional so the job doesn't attempt to run (and fail) if there is no Asana link in the PR. Taken from this suggestion: https://github.com/Asana/create-app-attachment-github-action/issues/14
=> ci: update Asana attachment workflow

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
Improved the pattern a bit so when only pair the widgets when CR is enabled. Can be used as a safeguard if the widget is disabled but the `pair_with_alert_widget` is not switched to `false` for the CR widget config.
=> tweak: Only pair alert with CR if CR enabled

test/screens/v2/template_test.exs
The return of `Template.slot_combinations/1` is produced by iterating over a map, which does not happen in a well-defined order as of OTP 26, causing the tests to sometimes fail. (I never saw this happen on CI, but at one point it was happening consistently on my local machine.)
=> test: fix assert relying on map ordering

config/config.exs
There was no headsign matcher for Maverick, so the current BL shuttle alert was breaking the screen. Adding this will allow us to properly render the alert.
=> fix: Added a DUP headsign matcher for Maverick.

assets/package-lock.json
Looks like a Dependabot PR didn't rebase properly and I forgot to run `npm ci` locally. This update should fix it.
=> Fixed lockfile sync issue.

assets/src/components/solari/route_pill.tsx
The refactor of this logic to address type errors in 1f411cb was incorrect and ended up breaking text route pills (e.g. bus numbers, commuter rail track numbers). The variable mistakenly named `routeImg` here was intended to be an image-or-string.
=> fix: missing route pills on Solari screens

lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/widgets/departures.ex, lib/screens/v2/departure.ex, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/candidate_generator/widgets/departures_test.exs
Best reviewed per-commit, as there is a non-trivial refactoring and also a sneaky extra feature here (filtering by time, which is used primarily in `include_schedules` sections to avoid showing schedules too far in the future — we didn't have a standalone Asana task for this).
Note the frontend still doesn't support multiple sections, so converted Solari configs (e.g. using #2030) will continue to have odd behavior. Bidirectional mode and time filtering do work correctly on single sections, if you trim down a config to use only one section.
---
- https://app.asana.com/0/0/1206932080790888
=> Bidirectional mode and time filtering

config/config.exs
**Asana task**: [[DUPs] Add South Station, Aquarium, Kendall to DUP headsign matchers](https://app.asana.com/0/1185117109217413/1207153943656494/f)
Have DUPs being installed at these stations soon so need these config changes for alert/headway headsigns to display correctly.
=> Added DUP headsign matchers for South Station and Kendall.

lib/screens/v2/candidate_generator/widgets/train_crowding.ex, test/screens/v2/candidate_generator/widgets/train_crowding_test.exs
When looking at alerts in the crowding app CG, we were not filtering out upcoming. This means `any_alert_makes_this_a_terminal?/2` was returning true if an upcoming alert made the stop a terminal.
=> fix: Crowding App alert logic

lib/screens/v2/widget_instance/line_map.ex, test/screens/v2/widget_instance/line_map_test.exs
**Asana task**: [[Screens 🐞] Gracefully handle no departures for Line Map](https://app.asana.com/0/1207094698667699/1206864414986293/f)
Handles the case when there fewer than two departures with predictions but also no departures _without_ a prediction.
- Previously this code would pass `nil` to `Screens.V2.Departure.time/1` which raised an exception 
- Refactors counting of departures with predictions to use a single `Enum.count/2`
- I'm happy to remove this if you all feel like it is out-of-place in this changeset
This doesn't eliminate all possible errors related to the `nil`ability of departures and the arrival and departure fields within schedules and predictions but is instead focused on the specific error reported to Sentry. A refactor to account for that class of errors would have …
=> Gracefully handle no departures for Line Map

assets/src/util/util.tsx, assets/webpack.config.js
The Triptych graphics are a little special in that they are always named after the panel they display on. The existing file-loader config didn't pull in parent folder so there was a conflict between the different PSA folders. Breaking out these files and adding `[folder]` to the `name` will allow the images to coexist.
=> fix: resolve webp file-loader warnings

lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
Quick fix for DUPs. None of the `serialize_section` patterns were matching because the header was missing from the map. Added an empty struct similar to how `Layout` is handled.
=> fix: DUP Section header support

assets/css/connection_error.scss, assets/css/dup/screen_container.scss, assets/css/dup/section.scss, assets/css/eink/loading.scss, assets/css/fonts/inter_font_face.scss, assets/css/v2/blue_bikes.scss, assets/css/v2/bus_eink/departures/time.scss, assets/css/v2/bus_shelter/link_footer.scss, assets/css/v2/dup/departures/route_pill.scss, assets/css/v2/eink/departures/alert.scss, assets/css/v2/eink/departures/overnight.scss, assets/css/v2/eink/link_footer.scss, assets/css/v2/eink/no_data.scss, assets/css/v2/eink/normal_header.scss, assets/css/v2/eink/page_load_no_data.scss, assets/css/v2/eink/route_pill.scss, assets/css/v2/gl_eink/departures/time.scss, assets/css/v2/gl_eink/line_map.scss, assets/css/v2/lcd_common/departures/alert.scss, assets/css/v2/lcd_common/departures/time.scss, assets/css/v2/lcd_common/normal_header.scss, assets/css/v2/lcd_common/route_pill.scss, assets/css/v2/pre_fare/alert-banner.scss, assets/css/v2/pre_fare/normal_header.scss, assets/css/v2/pre_fare/prefare_single_screen_alert.scss, assets/css/v2/pre_fare/reconstructed_alert.scss, assets/css/v2/pre_fare/shuttle_bus_info.scss, assets/css/v2/pre_fare/simulation.scss, assets/css/v2/solari_large/normal_header.scss, assets/stylelint.config.mjs
This reverts the specific changes in 83d806c that added generic font fallbacks, and disables the Stylelint rule that required them. We found this caused problems with (at least) DUP and Bus e-Ink rendering on real hardware.
=> fix: revert addition of generic font fallbacks

lib/screens_web/controllers/auth_controller.ex
Every once in a while, we get a Sentry error like [this](https://mbtace.sentry.io/issues/5046527403/events/0be23ee4507a4079bf7d2d99198dc695/) one. Adding this fallback will prevent an error while also keeping out unauthorized requests.
=> fix: Auth request fallback

assets/src/components/admin/admin_add_modal.tsx, config/config.exs
**Asana task**: [Add Park Street and Arlington to DUP headsign configs](https://app.asana.com/0/1185117109217422/1207171583176322/f)
<details>
<summary>Non-exhaustive examples 🖼️</summary>
</details>
=> Add Park Street and Arlington to DUP headsign configs

assets/css/v2/dup/free_text.scss
**Asana task**: [Fix DUP route pill font weights](https://app.asana.com/0/1185117109217413/1207447516868331/f)
Route pills within free text were not bold. This fixes that.
| Before | After |
| - | - |
| ![Screen Shot 2024-05-30 at 08 05 16](https://github.com/mbta/screens/assets/1699281/1eb5b99b-1a67-4cb4-819a-3b69aaf739e5) | ![Screen Shot 2024-05-31 at 12 46 05](https://github.com/mbta/screens/assets/1699281/7d880cb7-abb8-4752-919e-fe217da2362b) |
| ![Screen Shot 2024-05-30 at 08 04 26](https://github.com/mbta/screens/assets/1699281/cf7af9ae-e924-4687-8a2d-83efdb8da4d7) | ![Screen Shot 2024-05-31 at 12 37 42](https://github.com/mbta/screens/assets/1699281/96e96853-27da-4a0d-a7a0-550c862a5136) |
| ![Screen Shot 2024-05-30 at 08 00 …
=> Fix DUP route pill font weight

assets/css/colors.scss, assets/css/v2/lcd_common/departures.scss, assets/css/v2/lcd_common/departures/later_departures.scss, assets/css/v2/lcd_common/route_pill.scss, assets/src/components/v2/departures/later_departures.tsx, assets/src/components/v2/departures/normal_departures.tsx, assets/src/components/v2/departures/normal_section.tsx, assets/src/components/v2/departures/route_pill.tsx, assets/src/components/v2/departures/section.ts, assets/src/components/v2/multi_screen_page.tsx, assets/src/components/v2/screen_page.tsx, assets/src/hooks/v2/use_api_response.tsx, assets/src/hooks/v2/use_refresh_rate.ts, assets/src/hooks/v2/use_screen_id.tsx, assets/src/util/util.tsx, assets/tests/components/v2/departures/factories.ts, assets/tests/components/v2/departures/section.test.ts
**Asana task**: [Departures: Widgetize "Later departures"](https://app.asana.com/0/1207094698667699/1206645864760369/f)
- Tracks `trimmedRows` in sections layout helpers
- Renders `trimmedRows` in a "Later Departures" component when `include_later === true`
<details>
<summary>Recordings 📹</summary>
https://github.com/mbta/screens/assets/1699281/dc5cb717-7cdf-4fb2-b51b-5c8030c078d9
https://github.com/mbta/screens/assets/1699281/884fb4be-4b9c-4e61-87d6-57111ac245db
</summary>
=> Widgetize Later Departures

lib/screens/route_patterns/route_pattern.ex
[Asana](https://app.asana.com/0/1185117109217413/1207496878226131/f)
fixes Sentry issue [SCREENS-80](https://mbtace.sentry.io/issues/5039566709/?project=6061747&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=1)
Looking at the history of this file I think this was just a mistake. This `with` used to be a `case` with a `_ -> :error` match: https://github.com/mbta/screens/commit/7679cc6d1bb7d905e94db4874ace652f8b124d4a#diff-e96db1e1a5ac37886d83f672f7378fd59a409425061ee9e90232002b4fd223dbL34
=> fix: expand match in `RoutePattern.stops_by_route_and_direction/2`

lib/screens/v2/candidate_generator/widgets/departures.ex, test/screens/v2/candidate_generator/widgets/departures_test.exs
**Sentry issue**: [SCREENS-A5](https://mbtace.sentry.io/issues/5459051453/)
**Asana:** [Fix crash on MUL-108](https://app.asana.com/0/1207094698667699/1207495619155907/f)
Updates `case` to take any non-empty list and return the first value and return `nil` for anything else.
---
- https://app.asana.com/0/0/1207495619155907
=> fix: expand patterns to prevent CaseClauseError

lib/screens/v3_api.ex
Caching is working, these are really noisy. Just removes them. We can always add logs of hits, misses, size, etc. using [`Nebulex.Stats`](https://hexdocs.pm/nebulex/2.6.1/Nebulex.Stats.html) and probably [`:telemetry_poller`](https://hexdocs.pm/telemetry_poller/readme.html) or something
<details>
<summary>😵‍💫</summary>
```
info] [api_v3_get_json] response not modified, using cache
[info] [api_v3_get_json] response not modified, using cache
[info] [api_v3_get_json] response has been modified, updating cache
[info] [api_v3_get_json] response has been modified, updating cache
[info] [api_v3_get_json] response has been modified, updating cache
[info] [api_v3_get_json] response has been modified, updating cache
[info] [api_v3_get_json] response has been modified, updating cache
[info] …
```
=> chore: remove v3 api cache logging

assets/src/components/v2/pre_fare_single_screen_alert.tsx, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [title](https://app.asana.com/0/1185117109217413/1206489686303752/f)
- Prevents line breaks in station names by using free text with a `format: :nowrap` when sending station names
<details>
<summary>Non-exhaustive examples</summary>
</details>
=> [Prefare Alerts] Station names should not split across lines

assets/src/components/v2/alert.tsx, assets/src/components/v2/departures/departure_row.tsx, assets/src/components/v2/departures/later_departures.tsx, assets/src/components/v2/departures/route_pill.tsx, assets/src/components/v2/dup/overnight_departures.tsx, lib/screens/v2/widget_instance/serializer/route_pill.ex, test/screens/v2/widget_instance/departures_test.exs, test/screens/v2/widget_instance/serializer/route_pill_test.exs
"Route abbreviations" (formally named in this changeset) are short text codes that stand in for the names of routes which would otherwise be represented by a "mode icon" in route pills. Currently this only applies to Commuter Rail, though could conceivably apply to ferry in the future.
Previously, whether a "route abbreviation" was used was controlled at the time the route pill was serialized — the result from the client's perspective would either be an "icon pill" with the mode icon or a "text pill" with the abbreviation. However, the "Later Departures" feature requires that the client know both of these pieces of information at once, since which one is used depends on context that is not known until the widget is rendered.
Accordingly, this adds a field `route_abbrev` to the serialized …
=> fix: use CR abbreviations in Later Departures

.github/workflows/ci.yml, assets/src/components/v2/departures/header.tsx, assets/src/components/v2/departures/later_departures.tsx, assets/src/components/v2/departures/normal_departures.tsx, assets/src/components/v2/departures/normal_section.tsx, assets/src/components/v2/departures/section.ts, assets/tests/components/v2/departures/factories.ts, assets/tests/components/v2/departures/section.test.ts
We may not always want to display "Later Departures" even when it is enabled and some rows have been trimmed, because the carousel itself can take up more space than just displaying the departures normally would have.
The "magic constant" 3 is an imperfect guess that errs on the side of not introducing Later Departures unless it will almost certainly save space (it also happens to be the same constant used in the v1 Solari logic). Using layout effects to measure how much space is actually taken up by each approach is left as a potential future improvement.
At some point I was convinced that to do this correctly, the section component would need access to the _original_ departure rows, without the destructive trimming applied. That prompted a refactor where the trio of original rows, …
=> fix: use Later Departures when it saves space

assets/css/v2/busway/departures/header.scss, assets/stylelint.config.mjs
* Use a smaller font size for headers, such that most existing headers don't wrap onto a second line.
* Respect embedded line break characters (`\n`) in headers, allowing manual control over wrapping when the natural wrapping creates an awkward split.
The rule that `//` comments must be preceded by a blank line interacts poorly with the rule that enforces property ordering, making it difficult to comment on a specific property without breaking the properties into two visual "groups" (misleadingly, as the break has no real meaning). As an example, consider what would happen if the comment introduced in this PR were a bit longer, forcing it to be on its own line:
```scss
.departures-header {
box-sizing: border-box;
display: flex;
flex-direction: row;
align-items: center;
justify-content: …
```
=> Tweaks for Sectional headers

assets/package-lock.json
The `phoenix_html` elixir package was upgraded. This updates the `package-lock.json` to reflect the new JS package version
=> fix: update version of phoenix_html JS package

scripts/add_dup_headsign_config.exs
**Asana task**: [[Retro] Document DUP headsign config and adding new route to PA/ESS](https://app.asana.com/0/1185117109217413/1207495619156084/f)
In attempting to document how to add new stations to the DUP alert headsign configuration I realized that the process required **A LOT** of complicated, easy to mess up cross-referencing of V3 API requests. While working on #2056 I imported static GTFS into a sqlite database to join across the required relations but that was a bit much to document.
I figured a script that output the correct config for you was probably just as helpful if not more so!
---
- https://app.asana.com/0/0/1207348699397552
=> feat: Automate `dup_alert_headsign_matchers` configuration generation

assets/src/components/v2/screen_page.tsx
Huh, that's weird... why is the screen page 1939.2px tall, rather than 1920px?
Nothing seems out of place here...
Wait... zoom in...
THERE
=> fix: rogue semicolon on screen pages

assets/css/v2/dup/free_text.scss, assets/css/v2/lcd_common/free_text.scss, assets/css/v2/pre_fare/free_text.scss, assets/src/components/v2/free_text.tsx, lib/screens/routes/route.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/widgets/departures.ex, lib/screens/v2/disruption_diagram/builder.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex
Includes a separate refactor commit. This allows the "no departures" message on Sectionals to correctly display an "M" pill instead of falling back to an "RL" pill.
---
- https://app.asana.com/0/0/1207633106220713
=> fix: support Mattapan line in no-data states

assets/src/components/v2/cr_departures/cr_departures_header_free.tsx, assets/src/components/v2/dup/departures/departure_row.tsx, assets/src/components/v2/reconstructed_alert.tsx
passes the correct props to remaining `<RoutePill />` instances following #2072
=> fix: replace remaining prop spreads into RoutePill

lib/screens/alerts/alert.ex, lib/screens/application.ex, lib/screens/routes/route.ex, lib/screens/stops/stop.ex, lib/screens/telemetry.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v3_api.ex, mix.exs
Instrument most portions of DUP candidate generation. includes start & stop events, duration in ms, generated span_ids, parent_ids, correlation_ids, and links to request_id when possible. also supports logging additional metadata
<details>
<summary>Example output</summary>
```
[info] GET /v2/api/screen/DUP-AIR-DUP-002
[debug] Processing with ScreensWeb.V2.ScreenApiController.show/2
Parameters: %{"id" => "DUP-AIR-DUP-002", "last_refresh" => "2024-06-26T12:16:18.630529Z"}
Pipelines: [:redirect_prod_http, :api, :browser]
[info] event=screens.v2.candidate_generator.dup.header_instances.start request_id="F9yM_aesq1sJfV0AAApE" span_id="OOq9TkXnrcFsJD5O" parent_id="mNf25ySqPZ0tM29t" correlation_id="ZE2s3j5XzDPJpHou" 
[info] event=screens.stops.stop.fetch_stop_name.start …
```
=> feat: add logging/spans around DUP candidate generator

lib/screens/v2/widget_instance/serializer/route_pill.ex, test/screens/v2/widget_instance/serializer/route_pill_test.exs
This also changes the logic to omit the abbreviation and log a warning instead of crashing when it encounters a Commuter Rail route we haven't heard of, since the fallback of showing a CR icon is reasonable and this issue should not prevent the whole screen/section from working.
---
- https://app.asana.com/0/0/1207678749880387
=> fix: missing CR route abbreviation for Foxboro

lib/screens/v2/widget_instance/reconstructed_alert.ex
The Alewife platform is being bypassed this weekend. The alert was created using a new Alerts UI feature that the Pre-Fare screens cannot handle yet. We will use a static image in its place.
Note: the scenario we are testing here is suppressing the above alert and letting another shuttle alert render normally. There is a flex zone alert bug keeping this branch from displaying the alert properly. That is being resolved in #2094.
=> tweak: Suppress Alewife platform closure alert.

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
When I reviewed #2068, I didn't think about flex zone alerts. Because of the limited space on those, we should allow station names to wrap. Tweaked function a bit so that it returns a string for flex zone alerts.
=> fix: Allow line wrapping on flex zone alerts.

assets/package-lock.json, assets/package.json, config/dev.exs
Phoenix expects watcher processes to exit when it sends an EOF to their stdin, but tools like Webpack and `tsc` don't have this behavior by default and will keep running in the background, piling up over time. [`exit_on_eof`](https://github.com/ntilwalli/exit_on_eof?tab=readme-ov-file) is a package developed specifically to bridge this gap.
(Webpack actually has a `--watch-options-stdin` flag for this, but since `tsc` lacks such an option, we would need to use the package anyway.)
=> dev: fix Phoenix assets watcher not exiting

lib/screens/v2/widget_instance/reconstructed_alert.ex
When a delay is a single page alert, it will try to serialize the diagram. Problem is that the diagram will always consider delays an invalid effect and spams Splunk with warnings for it. Since we know delays never produce a diagram, we can prevent `DisruptionDiagram.serialize(t)` from being called at all.
Note: I left [validate_effect/1](https://github.com/mbta/screens/blob/6f253595c7caa582b15be1996954e37ff18754c9/lib/screens/v2/disruption_diagram/validator.ex#L26) alone because this code is organized in such a way that other widgets can call it. Didn't want to make a `ReconstructedAlert` assumption in the module because of that. Feel free to push back on that though.
=> tweak: Prevent delays from serializing diagrams.

lib/screens/v2/departure/builder.ex, test/screens/v2/departure/builder_test.exs
When displaying departures, we show the arrival time if there is one, and the departure time if not. When fetching departures, however, we were sorting by departure time if there was one, and arrival time if not (unless also fetching scheduled stop times, in which case sorting used the same logic as displaying!). This created some situations where departures would appear "out of order".
---
- https://app.asana.com/0/0/1207678749880386
=> fix: inconsistent departure sorting

assets/src/components/v2/pre_fare_single_screen_alert.tsx, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens_web/views/v2/audio/reconstructed_alert_single_screen_view.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
This reverts commits 19125d8, 9ffd4b4, and 5aff537, pending investigation on how we can accomplish this without causing overflow when a destination is too long to fit on one line.
See discussion on: https://app.asana.com/0/1185117109217422/1207688110481364
=> revert: no-wrap station names in prefare alerts

assets/src/components/v2/departures/destination.tsx
In general we're okay with the overflow behavior of destinations being ellipsized ("..."), but in the specific case of Government Center as a Green Line destination, we already have a standard abbreviation we use in other places (such as `NormalHeader`), and this would otherwise be rendered as "Government Cen..." on Sectional screens. Per Dave/Betsy review, we should just add this specific abbreviation for now, and revisit the larger topic of abbreviation consistency and thoroughness later.
---
- https://app.asana.com/0/0/1207678749880384
=> feat: abbreviate v2 departure destinations

assets/src/components/v2/departures/section.ts, assets/tests/components/v2/departures/section.test.ts
The `max` field is intended as a hard limit: a higher number of rows should never be displayed (aside from Later Departures). However, if the layout already fit on the screen without overflowing on the initial render, we would never trim sections at all, including to their max.
This makes the initial conversion of a section to a "folded" section also perform the trim-to-max.
---
- https://app.asana.com/0/0/1207647901798680
=> fix: sections not always respecting layout `max`

lib/screens/v2/widget_instance/cr_departures.ex
Every once in a while, the Porter Pre-Fare screen crashes with the following error 
```
7c59130100be ** (FunctionClauseError) no function clause matching in Screens.V2.Departure.select_arrival_time/1
7c59130100be (screens 0.1.0) lib/screens/v2/departure.ex:255: Screens.V2.Departure.select_arrival_time(nil)
```
If I'm following the code correctly, this only happens when `schedule == nil`. This should not happen though, so I think this is a data problem. Before suggesting something is wrong, I want to try to catch the departure data when it happens next.
=> Add log to catch nil CR schedule.

lib/screens/v2/departure.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
compares the vehicle's stop to the prediction's stop and only shows "BRD" if they match. this prevents "BRD" from showing when stops are very close to each other (such that a prediction is within the "BRD" window) and a vehicle is boarding at the previous stop
**Asana task**: [Fix "BRD" when vehicle is boarding at a previous stop](https://app.asana.com/0/1185117109217422/1207697513391322/f)
Description
=> fix: show "BRD" only if the vehicle is at the stop

lib/screens/v2/widget_instance/reconstructed_alert.ex
Refactors `select_direction_and_route/1` to use pattern mattern more heavily and handle cases when the passed argument is an empty list.
This handles the case when the direction and route for the informed entities of an alert are empty or otherwise filtered down to an empty list (e.g. only contain JFK). Additionally this is perhaps slightly more idiomatic Elixir code.
Fixes [SCREENS-AM](https://mbtace.sentry.io/issues/5591310217/)
=> fix: prevent crash on empty list

assets/src/apps/v2/bus_eink.tsx, assets/src/apps/v2/bus_shelter.tsx, assets/src/apps/v2/busway.tsx, assets/src/apps/v2/dup.tsx, assets/src/apps/v2/gl_eink.tsx, assets/src/apps/v2/solari_large.tsx, assets/src/components/v2/departures.tsx, assets/src/components/v2/departures/departure_row.tsx, assets/src/components/v2/departures/departure_time.tsx, assets/src/components/v2/departures/departure_times.tsx, assets/src/components/v2/departures/header.tsx, assets/src/components/v2/departures/normal_section.tsx, assets/src/components/v2/dup/departures.tsx, assets/src/components/v2/dup/departures/departure_row.tsx, assets/src/components/v2/dup/departures/departure_time.tsx, assets/src/components/v2/dup/departures/departure_times.tsx, assets/src/components/v2/dup/departures/destination.tsx, assets/src/components/v2/dup/departures/headway_section.tsx, assets/src/components/v2/dup/departures/no_data_section.tsx, assets/src/components/v2/dup/departures/normal_section.tsx, assets/src/components/v2/dup/departures/overnight_section.tsx, assets/src/components/v2/dup/no_data.tsx, assets/src/components/v2/dup/normal_header.tsx, assets/src/components/v2/dup/overnight_departures.tsx, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
This ended up being an exercise in stumbling upon a bunch of little things that could be refactored, so best reviewed per-commit (there are some explanations in the commit messages). The main point here is the final commit!
---
- https://app.asana.com/0/0/1207574972639085
=> refactor: add types for DUP widgets

lib/screens/routes/route.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
The version of this function prior to the refactor in 297c302 returned only a list of routes, returning an empty list if an error occurred. The moved/renamed version returns an `:ok` tuple or `:error`, consistent with other data fetching functions, but the call sites were not updated to reflect this (😓), and no tests failed because the mocks for the function still used the old return type (or, in the case of `ElevatorClosures`, the module lacked any tests at all).
This keeps the return type of the fetching function the same, so errors can be distinguished if needed, but changes the existing call sites to perform the "default to empty list" logic themselves, so there should be no change in behavior.
Deployed this branch to dev-green so we should see errors if there are still any, from the …
=> fix: refactor of routes-serving-stop fetching

lib/screens/alerts/cache.ex, lib/screens/application.ex, lib/screens/streams/alerts.ex
Uses ServerSentEventStage to consume alerts events from the V3 API and store them in an ETS table keyed by alert ID.
=> feat: in-memory Alert storage

config/config.exs, config/dev.exs, config/runtime.exs, config/test.exs, lib/screens/streams/alerts.ex, lib/screens/v3_api.ex
The base url for the v3 api was previously calculated in `Screens.V3Api` based on the environment name (or fell back to :default_api_v3_url). This value is needed in more places than `Screens.V3Api` now (`Screens.Streams.Alerts` specifically) so `:default_api_v3_url` has been replaced with `:v3_api_url` and is set in `config/runtime.exs`.
=> fix: move v3 api url into config/runtime.exs

lib/screens/alerts/alert.ex, lib/screens/alerts/cache/filter.ex, lib/screens/alerts/parser.ex, test/screens/alerts/alert_test.exs
Supports filtering the Alerts in the in-memory cache on route, route_type, direction_id, stop, and activity.
Route, stop, route type, and activity filters are lists of values where _any_ of these values need to be present in at least one of the informed entities of an alert to match.
If no activity filters are provided the default activity filter of BOARD, EXIT, or RIDE is applied.
Direction ID can only be filtered on one value at a time because filtering on multiple values is the same as removing the filter altogether.
If no filters are passed no filtering is done including no filtering on the default activity filter.
=> feat: Filtering for in-memory Alerts cache

lib/screens/alerts/alert.ex, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/candidate_generator/widgets/subway_status.ex, test/screens/alerts/alert_test.exs
Replaces calls to `Alert.fetch/1` and `Alert.fetch_or_empty_list/1` that only filter on `route_id` with calls to `Alert.fetch_from_cache/1` and `Alert.fetch_from_cache_or_empty_list/1` respectively.
=> feat: switch alert requests for specific routes to cache

assets/src/components/v2/widget_tree_error_boundary.tsx, assets/src/util/sentry.tsx, config/runtime.exs, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/controllers/v2/screen_controller.ex, lib/screens_web/templates/screen/index.html.eex, lib/screens_web/templates/v2/screen/index.html.eex, lib/screens_web/views/screen_view.ex, lib/screens_web/views/v2/screen_view.ex
Simplifies the multiple overlapping mechanisms for enabling and disabling Sentry, hopefully without changing existing behavior.
* If a `SENTRY_DSN` environment variable is defined, and the Mix env is `prod`, Sentry is enabled on the backend.
* If the above is true _and_ there is not a `disable_sentry` query param in the URL, Sentry is also enabled on the frontend.
There do not appear to be any screens actively using `disable_sentry` at the time of writing, but we'll leave this feature alone for now.
=> refactor: remove redundant Sentry-disabling code

config/config.exs, config/test.exs, lib/screens/alerts/cache/filter.ex, lib/screens/application.ex, lib/screens/stops/stops_to_routes.ex
Adds a Nebulex cache for stops -> routes. Uses that cache from `Screens.Alerts.Cache.Filter` to make the alerts cache snappy again
=> feat: cache stops to routes for use in alerts cache filter expansion

config/test.exs, lib/screens/alerts/cache/filter.ex, lib/screens/routes/route.ex, test/screens/alerts/alert_test.exs, test/screens/alerts/cache/filter_test.exs
Adds `route_type` filter expansion to the alerts cache matcher building.
=> feat: Expand route filters to include route_type

lib/screens/audio.ex, lib/screens_web/controllers/audio_controller.ex, lib/screens_web/controllers/v2/audio_controller.ex
Over the weekend, we hit a "maximum text length exceeded" error when trying to synthesize audio for a pre-fare ([Sentry](https://mbtace.sentry.io/issues/5728118365/)). Unfortunately we don't know exactly what the text was, because A) the code to log the error itself contained an error, and B) even if it had worked, we weren't logging the input text. Also, we probably wouldn't know it had happened at all, since this report would have only gone to the logs and not to Sentry.
This fixes the string interpolation in the logging, adds some needed context, and adds a Sentry report so we'll be notified when this happens again.
The [current audio readout](https://screens.mbta.com/v2/audio/PRE-110/debug) for this pre-fare is indeed rather close to the …
=> fix: error reporting on speech synthesis failures

test/screens/alerts/alert_test.exs, test/screens/alerts/cache/filter_test.exs
Adds `:verify_on_exit!` setup calls to tests using Mox to prevent any missed mock functional call expectations later on.
As suggested by @digitalcora https://github.com/mbta/screens/pull/2145#discussion_r1722188841
=> chore: add :verify_on_exit! to tests using Mox

assets/eslint.config.mjs, assets/package-lock.json, assets/package.json, assets/src/hooks/v2/use_refresh_rate.ts
Inspired by mbta/screenplay#459. Pleasantly, there was only one extant "rule-breaker", which was easy to correct.
=> dev: enforce React hooks rules in ESLint

lib/screens/alerts/cache/filter.ex, test/screens/alerts/cache/filter_test.exs
The alerts cache was missing a step that's present in the V3 API which meant that filters were not being applied to the list of all alerts correctly producing the wrong results.
This change adds a test suite to verify that filters work as expected and adds the additional step of expanding built matchers so partial matches are considered a match.
=> fix: apply filters to alerts cache correctly

lib/screens/alerts/alert.ex, test/screens/alerts/alert_test.exs
Relies on the in-memory Alerts cache when a request for Alerts data has filters supported by the cache. Uses the existing V3 API client otherwise.
---
- https://app.asana.com/0/0/1207848480396826
=> feat: switch to in-memory Alerts cache instead of V3 API

assets/src/apps/admin.tsx, lib/screens_web/auth_manager/pipeline.ex, lib/screens_web/controllers/auth_controller.ex, lib/screens_web/router.ex, test/screens_web/controllers/auth_controller_test.exs
Updates the admin dash to use "real" routing instead of hash-based, and the admin authentication pipeline to preserve the originally requested path. With these changes, it's now possible to link directly to a specific admin page and for that link to work even if you need to authenticate.
The "previous path" implementation is mostly swiped from Screenplay. Thanks, Screenplay. [Thcreenplay](https://en.wikiquote.org/wiki/Look_Around_You#Water).
=> Admin dashboard routing improvements

assets/css/admin.scss, assets/css/admin/viewer.scss, assets/src/apps/admin.tsx, assets/src/components/admin/admin_cells.tsx, assets/src/components/admin/admin_form.tsx, assets/src/components/admin/admin_tables.tsx, assets/src/components/admin/inspector.tsx, assets/src/hooks/v2/use_api_response.tsx, assets/src/hooks/v2/use_refresh_rate.ts, assets/src/util/admin.tsx, assets/src/util/inspector.ts, lib/screens_web/controllers/admin_api_controller.ex, lib/screens_web/router.ex
Presenting a ~~proof that I should not be left unsupervised~~ new Screens admin tool: the **Inspector**.
This is, I promise, pursuant to [Set up parallel running of new DUP logic](https://app.asana.com/0/1185117109217413/1207992837169564). The train of thought went something like this:
* Rather than hunting down and typing in DUP screen IDs and query params, it'd be nice to have a little tool that lets you select any screen you want, display it, and flip between the code paths. That should only take a couple days to build, it'll just expand the scope of this task a little bit.
* Okay, neither "base" screen pages nor Screenplay simulations are very readable without zooming them out/in... we should be able to resize the screen.
* And we'll probably want a way to reload the screen data …
=> feat: admin screen inspector

.github/dependabot.yml
I want to try out Dependabot's `groups` option so we can reduce the number of PRs it opens. Feel free to call out groups that should be added or groups I added that don't look right.
=> chore: Add dependabot groups

assets/src/components/admin/inspector.tsx, assets/src/hooks/v2/use_api_response.tsx, assets/src/hooks/v2/use_refresh_rate.ts, assets/src/util/inspector.ts
On real Bus E-ink screens we saw a mysterious "[DOM Exception 12](https://mbtace.sentry.io/issues/5760152862/)" crash that seemed to be caused by the inspector changes. Though the message sending and listening should have already been a no-op when the screen is not "framed", this adds a check for whether the screen is "framed" by the inspector specifically, and otherwise doesn't even attempt to send/listen. This should sidestep any issues with e.g. a screen vendor rendering our pages inside a frame.
Deployed to dev to test on Jon's physical screen, and confirmed that this fixed the "blank screen" issue it was having since the previous dev deploy, presumably as a result of this DOM Exception 12.
=> fix: guard against inspector code crashing screens

lib/screens/v2/departure.ex, lib/screens/v2/widget_instance/cr_departures.ex, test/screens/v2/departure_test.exs, test/screens/v2/widget_instance/cr_departures_test.exs
The commuter rail departures widget made the assumption that there would never be a departure that had a prediction but no matching schedule. We have observed that this isn't always the case.
Adds handling of a `nil` schedule to the commuter rail departures widget. The only thing relying on a present schedule in `serialize_departure/5` was calculating if a departure was delayed. If there is no schedule we do not flag the departure as delayed; otherwise, the delayed calculation remains unchanged.
**Asana task**: [[Screens 🐞] Fix Departure prediction/schedule merging](https://app.asana.com/0/1185117109217413/1207953256080348/f)
> [!NOTE]
> The associated ticket references an issue with filtering out past schedules before merging them with predictions into departures. To verify that this is …
=> fix: handle unscheduled commuter rail departures

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
Alert #590467 represents suspension of red line service on the Braintree branch with shuttles connecting at Ashmont instead of JFK/UMass. Because of this abnormal shuttle pattern, the generated line maps will not be accurate. Evergreen content will be used to display the correct information to riders.
**Asana task**: [Custom graphics during Braintree Branch diversion](https://app.asana.com/0/1185117109217422/1208136071296475/f)
=> chore: suppress alert 590467 on pre-fare screens

.github/dependabot.yml
I noticed some deprecation warnings in CI because we're using old versions of some Actions, which themselves are using old versions of Node. Dependabot can now help us keep these up-to-date.
=> dev: enable Dependabot for Actions versions

lib/screens/predictions/parser.ex, lib/screens/predictions/prediction.ex, lib/screens/predictions/schedule_relationship.ex, lib/screens/v2/departure/builder.ex, test/screens/predictions/schedule_relationship_test.exs, test/screens/v2/departure/builder_test.exs
Parses the `schedule_relationship` field for `Predictions` and uses that data to remove departures with a SKIPPED or CANCELLED schedule relationship when merging `Prediction`s and `Schedule`s.
Some Predictions now have a SKIPPED schedule relationship **AND** arrival/departure times (indicating what time the vehicle is predicted to pass through the stop). These Predictions need to be filtered out when we fetch departures. Previously these didn't have times so our other filtering logic would remove them.
For completeness we are also filtering out Predictions with a CANCELLED schedule relationship.
**Asana task**: [Filter out cancelled/skipped departures on Screens](https://app.asana.com/0/1185117109217413/1207498013010848/f)
=> fix: filter cancelled & skipped departures

lib/screens/v2/screen_data.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/line_map.ex, lib/screens/v2/widget_instance/normal_header.ex, lib/screens_web/controllers/v2/screen_controller.ex
Some of the Mercury specific logic is not at all self-explanatory without context so I added some comments explaining why it exists and the Asana task used to track the work.
=> chore: Comment Mercury logic

test/screens/v2/widget_instance/cr_departures_test.exs
`Screens.V2.WidgetInstance.CRDepartures.serialize_departure/5` logs and error for departures with a prediction but no schedule. This updates tests to make assertions on that log output and also prevents that logging from showing when running tests, keeping things nice and clean! 🧼
=> chore: test logging output of serialize_departure/5

config/runtime.exs
Our ECS tasks all set a `API_V3_URL` pointing to the desired V3 API environment but we were ignoring that value and instead deriving the V3 API URL based on `ENVIRONMENT_NAME`. This is confusing.
With this change the URL used for the V3 API is always fetched from the environment as `API_V3_URL` (unless `MIX_ENV=test`).
This has the added benefit of picking up the changes in https://github.com/mbta/devops/pull/2122
**Asana task**: [Point screens-dev-green at api-dev-blue](https://app.asana.com/0/1185117109217413/1207488840910528/f)
=> fix: always use API_V3_URL environment variable

lib/screens_web/controllers/v2/screen_controller.ex
This PR addresses [this](https://mbtace.sentry.io/issues/5758610323/events/1f7281300b7c4299b88dd720971a38fd/) Sentry error. When screen ID is opened with the v2 URL, we don't check that the ID is a v2 screen. This causes v1 IDs to throw a cryptic error when we calculate refresh rates. We should instead return a 404. We could also redirect to the v1 controller but that seems a little heavy handed.
=> fix: Only match v2 screen IDs in v2 controller

lib/screens/routes/route.ex
Some time ago (36f9f83) we changed this specific data fetching function so it "doesn't trust" the V3 API if it says there are no routes serving a stop, and tries again up to 3 times.
Some more-recent time ago (297c302), as part of a refactor of this function, we added a warning when a retry occurs, so we'd get some idea whether this logic was still useful.
One month later, we have not logged this warning in any deployed environment, so it seems safe to remove.
=> chore: remove bespoke routes-at-stop retry logic

lib/screens/routes/route.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/candidate_generator/pre_fare_test.exs
Previously DUPs made one routes-serving-stop API request for every stop ID configured for every section. This may be inefficient given the API supports filtering by many stop IDs in one request, and suspiciously, DUPs configured with more stop IDs seem to encounter the "Failed to get section data" timeout [more often](https://mbtace.sentry.io/issues/5545381601/tags/url/?environment=screens-prod&project=6061747&statsPeriod=14d).
This enhances our routes-serving-stop fetching to support more than one stop ID, and passes in the entire list of stop IDs for each DUP section.
=> perf: reduce API request volume on DUPs

assets/src/components/v2/screen_container.tsx, assets/src/components/v2/simulation_screen_container.tsx, assets/src/hooks/v2/use_api_response.tsx
* Removes the need for a distinct "response handler" for simulation endpoints.
* Removes an unused field from an argument type.
* Improves some potentially confusing naming.
=> refactor: simplify frontend API data hook

config/runtime.exs
References the new environment variable from https://github.com/mbta/devops/pull/2129 instead of deriving this value based on `ENVIRONMENT_NAME`
> [!WARNING]
> ~~https://github.com/mbta/devops/pull/2129 must be deployed first!~~ **Update: This is done ✅**
=> chore: use SIGNS_UI_S3_BUCKET environment variable

lib/screens/v2/candidate_generator/gl_eink.ex
Somehow an incorrect arity slipped through the cracks in #2190. Bumping it from 2 to 3 corrects the issue.
=> fix: Correct arity of injected dependency

lib/screens/v2/screen_data/parameters.ex
This is now an unused duplicate of logic that was moved into `ScreensConfig.Screen.shows_alerts?`.
=> refactor: remove unused `shows_alerts?` code

assets/src/apps/v2/dup.tsx, assets/src/components/v2/dup/departures_no_data.tsx, assets/src/components/v2/dup/no_data.tsx, config/test.exs, lib/screens/stops/stop.ex, lib/screens/telemetry.ex, lib/screens/v2/candidate_generator/dup_new.ex, lib/screens/v2/candidate_generator/dup_new/departures.ex, lib/screens/v2/candidate_generator/dup_new/header.ex, test/screens/v2/candidate_generator/dup_new_test.exs, test/support/mocks.ex
Rather than being entirely placeholders, the `new_departures` DUP variant now generates header and evergreen content widgets that should work identically to the base variant. The "departures" area is stubbed to always render a "no data" message. (This PR incidentally fixes an existing bug with that message where it would render a duplicate header, pushing down and cutting off the content.)
Example of a `new_departures` DUP being rendered with an evergreen content item enabled, and without:
---
- https://app.asana.com/0/0/1207992837169563
=> Initial widgets for new DUP logic

.envrc.template, config/config.exs, config/runtime.exs, config/test.exs, lib/screens/application.ex, lib/screens/last_trip.ex, lib/screens/last_trip/cache.ex, lib/screens/last_trip/cache/last_trips.ex, lib/screens/last_trip/cache/recent_departures.ex, lib/screens/last_trip/parser.ex, lib/screens/last_trip/poller.ex, lib/screens/last_trip/trip_updates.ex, lib/screens/last_trip/trip_updates/gtfs.ex, lib/screens/last_trip/trip_updates/noop.ex, lib/screens/last_trip/vehicle_positions.ex, lib/screens/last_trip/vehicle_positions/gtfs.ex, lib/screens/last_trip/vehicle_positions/noop.ex, test/fixtures/TripUpdates_enhanced.json, test/fixtures/VehiclePositions_enhanced.json, test/screens/last_trip/cache_test.exs, test/screens/last_trip/parser_test.exs
Tracks trips marked as `last_trip: true` and recent departures from all route-direction-stop tuples.
Fetches TripUpdates and VehiclePositions data from concentrate S3 bucket to populate two caches (one for last trips and one for a list of recent departures from a stop on a given route going a direction).
Both caches have TTLs of one hour so old trips and departures will fall off over time. Recent departures are a special case because they are tracked as a list of recent departures. Departures (tuples of trip_id and departure time in unix epoch) are upserted into the cache key for a given RDS. During update departures more than one hour in the past are removed from the list for that RDS.
Caches are reset every day after 3:30am EST.
> [!NOTE]
> The realtime_signs code uses …
=> feat: track last train of the day

assets/src/components/v2/dup/README.md, assets/webpack.config.js, priv/dup-app.html
As we start working towards upgrading webpack, we want to split out DUP packages into a separate build. We know that the current configuration works for live DUPs so we want to ensure it remains unchanged as we upgrade webpack. 
---
- https://app.asana.com/0/0/1208162115483285
=> chore: Split DUP packages into separate webpack entry

assets/src/components/admin/admin_add_modal.tsx, assets/src/components/admin/admin_tables.tsx
Main goal of this PR is to correct default value for `evergreen_content` when creating a screen use the `Add New Screen` modal. I also saw an opportunity to clean up/fix columns shown on the app filter tabs.
---
- https://app.asana.com/0/0/1208461183523595
=> chore: Cleanup Admin columns and default values

lib/screens/alerts/alert.ex, lib/screens/departures/departure.ex, lib/screens/route_patterns/route_pattern.ex, lib/screens/routes/route.ex, lib/screens/schedules/schedule.ex, lib/screens/trips/trip.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/widgets/departures.ex, lib/screens/v2/departure.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/overnight_cr_departures.ex, lib/screens/vehicles/vehicle.ex, test/screens/v2/departure_test.exs
Implements the updated ["RDS generation" algorithm](https://www.notion.so/mbta-downtown-crossing/Real-time-departure-states-13dddc816adb43e79a3d952c246b08f7?pvs=4#347394ea5da94f4684ef0580783b09bd) and stubs out a `NoDepartures` state for all RDSes. Rather than doing this specifically "from DUP screen configs", the module accepts a `Departures` widget configuration struct, which is common to all screen types (though DUPs are a little odd in that they have two independent instances of this, for the multiple rotations — some glue logic will be needed in the candidate generator to accommodate this).
Currently this is not connected to anything "real" but will shortly be hooked up to the `new_departures` DUP variant as specified in the dependent Asana task.
---
- To see the specific tasks where …
=> Refactors from RDS generation

config/test.exs, lib/screens/departures/departure.ex, lib/screens/lines/line.ex, lib/screens/lines/parser.ex, lib/screens/predictions/parser.ex, lib/screens/predictions/prediction.ex, lib/screens/route_patterns/parser.ex, lib/screens/route_patterns/route_direction_stops.ex, lib/screens/route_patterns/route_pattern.ex, lib/screens/routes/parser.ex, lib/screens/routes/route.ex, lib/screens/schedules/parser.ex, lib/screens/schedules/schedule.ex, lib/screens/stops/parser.ex, lib/screens/stops/stop.ex, lib/screens/trips/parser.ex, lib/screens/trips/trip.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/departure.ex, lib/screens/v2/rds.ex, test/screens/route_patterns/route_pattern_test.exs, test/screens/routes/route_test.exs, test/screens/stops/stop_test.exs, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/candidate_generator/pre_fare_test.exs, test/screens/v2/rds_test.exs, test/support/mocks.ex
This adds a module which generates "destinations" from screen configs, the first step in the proposed [real-time destinations](https://www.notion.so/mbta-downtown-crossing/Real-time-destination-states-114f5d8d11ea8077b79cef05225e5725) logic. Both "permanent" (from typical route patterns) and "live" (from upcoming departures) destinations are generated. Initially there is only one possible state for a destination, `NoDepartures`. Following tasks will add more states and wire these into the `DupNew` screen variant.
This required a lot of refactoring and expansion of how we fetch data. Individual commit messages have the explanations of this. 📝
---
- https://app.asana.com/0/0/1207992837169561
=> Initial destinations framework

lib/screens_web/controllers/v2/screen_controller.ex
We have no logs for these endpoints in any environment but Mercury uses them to create images for the e-inks. Adding some logging so we have a way to tell when something goes wrong.
=> chore: Log requests to widget endpoints

assets/src/components/admin/inspector.tsx
Some things I noticed while testing Bus E-ink audio.
* Sort screen type groups in the screen selector (`bus_eink_v2` comes before `dup_v2`, etc.)
* Ensure the audio button always plays "fresh" audio (browser was caching it for subsequent plays)
=> Minor inspector fixes

assets/src/components/admin/inspector.tsx, lib/screens/v2/screen_data/parameters.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/normal_header.ex, lib/screens/v2/widget_instance/subway_status.ex, lib/screens_web/controllers/v2/screen_api_controller.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/normal_header_test.exs
We'll soon be setting up our first Bus E-ink screen provided by Mercury. This requires a couple of changes:
* In places we previously had logic to include extra "Mercury fields" when the screen type was `gl_eink`, we should instead key on the `vendor` field.
* Since this new screen will have an audio readout button similar to GL E-ink, the Bus E-ink screen type now needs to support audio.
---
- https://app.asana.com/0/0/1208343202037657
=> Support Mercury bus e-ink screens

lib/screens/health.ex
In the first PR, I removed this workaround because the author closed Cora's original [issue](https://github.com/ferd/recon/issues/95). This is definitely still an issue. I deployed the health check on Friday and saw the error occur about 60 times. Want to get this workaround in before deploying the check to prod.
=> fix: Recon error workaround.

lib/screens/signs_ui_config/cache.ex, lib/screens/signs_ui_config/parse.ex, lib/screens/util.ex, test/screens/util_test.exs
**Asana task**: [Change Screens to read these new values, handle appropriately](https://app.asana.com/0/1185117109217413/1208512927678682/f)
Description
This changes screens to use the new headway values, as outlined in the ticket. Also changes the parsing method slightly so that it's resilient to missing or unexpected values.
=> use new headway periods

assets/src/components/admin/inspector.tsx, assets/src/hooks/v2/use_audio_readout.tsx, assets/src/util/inspector.ts
Avoids being jumpscared by a periodic audio readout that also can't be silenced, short of closing the tab or navigating away. To replace the missing feedback on whether periodic audio is configured, also adds a line to the inspector audio controls to report the readout parameters that would have been used.
=> feat: suppress periodic audio in inspector

assets/src/components/v2/cr_departures/cr_departure_time.tsx, assets/src/util/time_representation.tsx
The `type` value we send to the client is always a lowercase atom converted to a string. For some reason, the client code was looking for an uppercase version of each value. This was causing the `div` that holds the time to be empty.
Before:
After:
=> fix: Incorrect types for TimeRepresentation

assets/css/admin.scss, assets/css/admin/inspector.scss, assets/src/components/admin/inspector.tsx
The admin inspector was originally named the "viewer". It was renamed before the feature was first merged, but some instances of the old term were missed.
=> refactor: rename inspector styles for consistency

lib/screens/stops/stop.ex, lib/screens/v2/candidate_generator/gl_eink.ex, lib/screens/v2/candidate_generator/gl_eink/headways.ex
This frees up the base `Headways` module name for use by a new system based on the OIO-controlled headway values in Signs UI. The plan is for this to eventually be used by all screen types, including GL E-ink, as part of the new "destinations" logic.
=> refactor: namespace GL E-ink headways module

lib/screens/predictions/parser.ex, lib/screens/route_patterns/parser.ex, lib/screens/route_patterns/route_direction_stops.ex, lib/screens/schedules/parser.ex, lib/screens/stops/parser.ex, lib/screens/stops/stop.ex, test/screens/route_patterns/route_pattern_test.exs, test/screens/stops/stop_test.exs
Some stop functions were already using this relationship by effectively hand-rolling the relevant bits of the parsing. We can simplify by fully parsing the parent/child relationships in the main stop `Parser`, and having the special-purpose `Stop` functions delegate to a main `fetch` function as we do with other resources.
Since we may be "starting from" either a parent or a child, we need a way to encode the complete data without recursing infinitely through this bidirectional link. For this purpose we introduce `:unloaded` as a special value indicating a relationship was not populated, similar to `Ecto.Association.NotLoaded`. This allows ending the recursion once we know we have all the data. It also allows the relationships to not be fetched in the first place, for functions that don't …
=> refactor: fetch parents/children with stops

config/test.exs, lib/screens/inject.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/dup_new/header.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/rds.ex, lib/screens/v2/screen_data.ex, lib/screens/v2/screen_data/layout.ex, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/candidate_generator/dup_new_test.exs, test/screens/v2/candidate_generator/elevator/closures_test.exs, test/screens/v2/rds_test.exs, test/screens/v2/screen_data_test.exs, test/support/mocks.ex
Rather than adding an app configuration key for every mockable dependency of every module, we can standardize on a convention for naming and defining the mocks, assisted by a small macro.
=> refactor: simplify dependency injection approach

lib/screens/v2/widget_instance/departures.ex, test/screens/v2/departure_test.exs, test/screens/v2/widget_instance/departures_test.exs
Currently deployed client code (in particular DUPs, which have to be updated manually by sending a new package to our vendor) requires this field to be present or it will crash.
=> fix: keep `inline_alerts` field for compatibility

assets/src/components/v2/widget_tree_error_boundary.tsx
The endpoint we use in the error boundary doesn't exist. Adjusting it to point to what is in `router`.
=> fix: client logging endpoint

assets/css/elevator_v2.scss, lib/screens/v2/candidate_generator/elevator.ex, lib/screens/v2/candidate_generator/widgets/evergreen.ex
Adds evergreen content support on elevator screens. Assuming `Screens.Util.Assets.s3_asset_url/1` points at the `screens-dev-green` bucket, you can use the following config to test:
```json
{
"ELE-101": {
"disabled": false,
"name": "",
"app_id": "elevator_v2",
"app_params": {
"evergreen_content": [
{
"priority": [0],
"slot_names": ["header"],
"asset_path": "images/elevator/header_test.png",
"schedule": [
{
"start_dt": null,
"end_dt": null
}
],
"text_for_audio": null,
"audio_priority": null
},
{
"priority": [0],
"slot_names": ["main_content"],
"asset_path": "images/elevator/main_content_test.png",
"schedule": [
{
"start_dt": null,
"end_dt": null
}
],
"text_for_audio": null,
"audio_priority": null
},
{
"priority": [0],
"slot_names": ["footer"],
"asset_path": …
```
=> feat: Elevator evergreen content

lib/screens/v2/screen_data.ex, lib/screens_web/controllers/v2/screen_api_controller.ex, test/fixtures/config.json, test/screens/v2/screen_data_test.exs, test/screens_web/controllers/v2/screen_api_controller_test.exs, test/support/candidate_generator_stub.ex
Mercury asked for us to append all flex zone pages to each data request. This will allow them to make less requests and improve battery life. Because the layout is required to get the flex zone data, I decided to make an alternative to `get/2` that works through `select_variant/3` with a different `then_fn`. I worry this might be a tad overcomplicated so happy to hear alternatives.
=> chore: Add flex_zone pages to Mercury screen requests

assets/src/components/v2/elevator/current_elevator_closed.tsx
Betsy pointed out that coordinates from Figma weren't matching up exactly in our code. I then realized I mapped `top` and `left` wrong 😅. Flipped them so coordinates work as expected.
=> fix: Map marker cords

lib/screens/audio.ex, lib/screens/cache/engine.ex, lib/screens/cache/owner.ex, lib/screens/config/cache/engine.ex, lib/screens/departures/departure.ex, lib/screens/log.ex, lib/screens/route_patterns/route_direction_stops.ex, lib/screens/screens_by_alert/memcache.ex, lib/screens/signs_ui_config/cache/engine.ex, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/location_context.ex, lib/screens/v2/widget_instance/audio_only/alerts_intro.ex, lib/screens/v2/widget_instance/audio_only/alerts_outro.ex, lib/screens/v2/widget_instance/audio_only/content_summary.ex, lib/screens/v2/widget_instance/cr_departures.ex, lib/screens/v2/widget_instance/dup_alert.ex, lib/screens/v2/widget_instance/serializer/route_pill.ex, lib/screens_web/controllers/v2/screen_controller.ex, test/screens/v2/widget_instance/audio_only/alerts_intro_test.exs, test/screens/v2/widget_instance/audio_only/alerts_outro_test.exs, test/screens/v2/widget_instance/audio_only/content_summary_test.exs, test/screens/v2/widget_instance/cr_departures_test.exs, test/screens/v2/widget_instance/serializer/route_pill_test.exs
Various modules were "manually" implementing the `key=value` log format we use for Splunk searchability, and most errors or warnings were only being logged rather than reported to Sentry (where they are easier to organize and we can be proactively notified about them). This change consolidates all existing errors/warnings into a shared function that logs to both `Logger` and Sentry.
* Sentry reports are also sent asynchronously, so they don't hold up returning a value to a client.
* All errors/warnings are given a unique underscored identifier rather than a free-text message, which improves Splunk ergonomics.
Existing logging at `info` level and below is not changed, but would be a logical next step.
=> chore: consolidate error/warning logging

assets/src/components/v2/elevator/elevator_closures_list.tsx
The previous code mutated the `stations` prop when sorting, and also did not implement a stable sort function[^1]. As a result, the closure list would be reversed each time a data request occurred. In the common case where the widget has two pages, this resulted in certain closures never being shown, since they would always be on the "other" page.
[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description
---
- https://app.asana.com/0/0/1208967508048795
=> fix: elevator closures sorting instability

lib/screens/image.ex
In local development, the Image Manager defaults to using the `dev` environment's S3 bucket — except that the environment name should have been `screens-dev`, so this did not work.
=> fix: incorrect environment name for Image Manager

assets/src/apps/v2/elevator.tsx, lib/screens/v2/candidate_generator/elevator.ex, test/screens/v2/candidate_generator/elevator_test.exs
This allows evergreen content to be configured to replace the whole screen, including the header and footer.
---
- https://app.asana.com/0/0/1209001244550623
=> feat: takeover layout for elevator screens

lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/alert_test.exs, test/screens/v2/widget_instance/subway_status_test.exs
For Bus Shelter screens that use push-button audio (i.e. do not have a periodic audio readout), the Alert and Subway Status widgets should be included in the readout.
**Asana task**: https://app.asana.com/0/1185117109217413/1208591545042715/f
=> feat: audio readout for push-button Bus Shelters

assets/css/v2/elevator/elevator_closures_list.scss, assets/src/components/v2/elevator/elevator_closures_list.tsx
**Asana task**: [Dividing Line Margin Issue on Elevator Screens](https://app.asana.com/0/1185117109217422/1209001244550628)
Fixes two issues with elevator closures separating lines on elevator screens, shown in the images below:
-  Padding: The dividing line for elevator closures had width set to 100%, which caused it to overflow to the right and appear on proceeding pages.
- Beyond the first page, there was no top line between the header and the closures.
---
- https://app.asana.com/0/0/1209061601128473
=> [Bugfix] Fix padding and locations of dividing lines for elevator closures

assets/css/elevator_v2.scss
**Asana task**: [Various small front-end issues on elevator screens](https://app.asana.com/0/1208877354406742/1209001244550628/f)
This fixes the bug where more than 2 pages of elevator screens would cause the page indicator dots to overlap. There was another bug pointed out where the bottom of the dots would be cut off, but I've been unable to replicate after th efix done in [this PR](https://github.com/mbta/screens/pull/2372).
=> [Bufix] Elevator closure page indicators overlap when more than 2

assets/src/components/v2/elevator/elevator_closures_list.tsx
**Asana task**: [Bugfix: Elevators should not be plural when only 1](https://app.asana.com/0/1185117109217413/1209061604856912)
Description
=> [Bugfix] Make elevator text being plural conditional

lib/screens/image.ex
Turning up more odd corners of the app in my memory usage investigations...
As far as I can tell, this function was actually _never_ used (in the commit where it was introduced, there are no references to it, and no commit since then has ever referenced it). And in general doesn't seem like it should be needed, since our image bucket is public-read and we load images directly using their S3 URLs.
=> refactor: remove unused `Image` function

config/config.exs, lib/screens/application.ex
Though this is unlikely to be causing any issues, it also seems very unnecessary. Over the past 30 days we've seen at most 2 concurrent connections out of a possible 50 in this pool (and 1 out of 50 for the default pool, which ExAws will use after this change). This aligns with how often we'd expect to be calling AWS APIs during normal operations.
Relevant Splunk query: `index=screens-prod-application hackney_pool | timechart max(in_use_count) by pool`
=> refactor: remove separate Hackney pool for ExAws

config/config.exs, lib/screens/application.ex, lib/screens/screen_api_response_cache.ex, lib/screens/telemetry.ex, lib/screens/v3_api.ex, lib/screens/v3_api/cache.ex, test/screens/v3_api/cache_test.exs
Investigating high memory usage in production suggested the V3 API connection pool was a major factor: each open connection consumes about 5MB, and with a pool size of 100, the pool could consume close to 500MB during peak usage, which is half the memory allotted to our instances. Add the 250MB limit on our API response cache and it becomes clear how we could start cutting things close.
Reducing the pool size would be an obvious step to take; but then we _do_ use all of those 100 connections (and still want more!) during peak times. If we could reduce the number of concurrent connections we need, then we could also reduce the pool size without impacting screen performance/stability.
To that end, this change:
* Reduces the V3 API connection pool size to 50 (the default). This should give …
=> refactor: new V3 API caching approach

assets/css/elevator_v2.scss, assets/css/v2/elevator/screen/takeover.scss
Ad-hoc
Betsy called out two issues seen with elevator screens showing evergreen content [in slack](https://mbta.slack.com/archives/C039ARUM48H/p1736361819704629), one of them being that the screen was appearing very small.
I'm not sure if I have the explanation down quite right, but I think this was happening because we were missing the appropriate CSS classes for elevator screen takeovers and so the typical down-scaling that we do to size screens appropriately into Screenplay was being applied to the screen's dimensions and not the takeover container's dimensions.
=> Add CSS for elevator takeover

lib/screens/v2/candidate_generator/elevator/closures.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs
**Asana task**: https://app.asana.com/0/1185117109217413/1209154878642792
=> fix: show only active closures on elevator screens

lib/screens/v2/candidate_generator/elevator/closures.ex, priv/elevators.json, test/screens/v2/candidate_generator/elevator/closures_test.exs
Today when checking out the elevator screens at Forest Hills, we noticed that the fallback text for elevator screen instructions did not reference the updated link.
Image with updated link below.
=> chore: Update fallback text to link to elevators endpoint

assets/src/components/admin/admin_form.tsx, assets/src/components/admin/admin_image_manager.tsx, assets/src/components/admin/admin_screen_config_form.tsx, assets/src/components/admin/admin_table.tsx, assets/src/components/admin/devops.tsx, assets/src/components/admin/inspector.tsx, assets/src/util/admin.tsx, config/config.exs, config/prod.exs, config/runtime.exs, lib/screens/ueberauth/strategy/fake.ex, lib/screens_web/auth_manager.ex, lib/screens_web/auth_manager/error_handler.ex, lib/screens_web/auth_manager/pipeline.ex, lib/screens_web/controllers/auth_controller.ex, lib/screens_web/router.ex, mix.exs, test/screens_web/auth_manager/error_handler_test.exs, test/screens_web/controllers/auth_controller_test.exs
Using the admin UI was previously plagued by auth errors that would occur after just a few minutes of idle time and required refreshing the page, losing any work in progress.
These changes should improve how we handle authentication, allowing an admin to be idle for up to 30 minutes and signed in for up to 12 hours before needing to reauthenticate, following the TID [Session Management](https://www.notion.so/mbta-downtown-crossing/Session-Management-ad53a774fd39462c82146f60700db5fc) guidelines and the prior art of mbta/screenplay#520.
This also revises and unifies how data fetching works in the admin UI, to allow showing admins a message indicating their session has expired when that happens (regardless of the interaction), rather than a generic error message.
In support of the above …
=> chore: improve authentication handling

lib/screens/v2/candidate_generator/elevator.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs, test/screens/v2/candidate_generator/elevator_test.exs
Some refactoring on the way to future elevator closures.
* Rather than the main Elevator screen candidate generator creating the header and footer widgets and the Closures generator "modifying" them with variants as appropriate, now the Closures generator alone is responsible. This somewhat simplifies the implementation and testing on both ends.
* Tests for the Closures generator were more verbose and testing more than they strictly needed to be (for example, that the correct header and footer were present in every case). These are now cut down to only the relevant and unique details.
=> refactor: elevator closure header/footer handling

assets/src/apps/v2/bus_shelter.tsx
When a screen normally capable of periodic audio readouts (Bus Shelter) had them disabled, this was incorrectly loaded as an interval of `NaN` minutes, rather than no interval at all. This basically worked anyway on the screens themselves, but showed up oddly in the Inspector.
=> fix: inspector showing `NaN` audio interval

lib/screens/elevator.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, priv/elevators.json, scripts/format_elevator_data.exs, test/screens/elevator_test.exs, test/screens/v2/candidate_generator/elevator/closures_test.exs
Previously the logic for elevator redundancy only cared about "exiting redundancy", so that was the only column of the spreadsheet we loaded. For the future elevator closures feature, we'll also have logic that depends on "entering redundancy", so both categories should be loaded and distinguishable.
=> refactor: parse elevator entering redundancy

lib/screens/departures/departure.ex, lib/screens/headways.ex, lib/screens/last_trip/poller.ex, lib/screens/schedules/schedule.ex, lib/screens/util.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/gl_eink/headways.ex, lib/screens/v2/candidate_generator/widgets/cr_departures.ex, lib/screens/v2/screen_data/parameters.ex, lib/screens/v2/widget_instance/cr_departures.ex, lib/screens/v2/widget_instance/departures.ex, lib/screens/v2/widget_instance/line_map.ex, lib/screens/v2/widget_instance/overnight_cr_departures.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens/v2/widget_instance/shuttle_bus_info.ex, test/screens/util_test.exs
* Replaces a multitude of slightly different one-off routines for translating a datetime into a "service date" with calls to a shared utility function.
* Replaces a bunch of duplicated `America/New_York` strings with calls to a new utility function.
=> refactor: unify local time and service date logic

assets/css/elevator_v2.scss, assets/css/v2/elevator/alternate_path.scss, assets/css/v2/elevator/closures.scss, assets/src/apps/v2/elevator.tsx, assets/src/components/v2/elevator/alternate_path.tsx, assets/src/components/v2/elevator/closures.tsx, assets/src/components/v2/elevator/constants.ts, assets/src/components/v2/elevator/elevator_constants.tsx, lib/screens/v2/candidate_generator/elevator.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/widget_instance/elevator_alternate_path.ex, lib/screens/v2/widget_instance/elevator_closures.ex, lib/screens_web/views/v2/audio/elevator_alternate_path_view.ex, lib/screens_web/views/v2/audio/elevator_closures_view.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs, test/screens/v2/widget_instance/elevator_alternate_path_test.exs, test/screens/v2/widget_instance/elevator_closures_test.exs
Goals:
* Align naming of the "this elevator is working" widget with the idea that it isn't _only_ a "list" of closures. (This already wasn't the case, since this widget incorporates the "status bar" for elevators at the current station, but it will be even more so with the introduction of future elevator closure info.)
* Clean up duplicative "elevator" naming. When a module is already in an `elevator` namespace, it does not itself need to include `elevator` in its name.
I'd like feedback / possible alternatives for these names — I don't love them (in particular how the word _"closures"_ is getting thrown around a lot), I just think it's incrementally better than before. Part of the problem is that we also have the entirely-separate-yet-similar-in-function "elevator _status_" widget for …
=> refactor: rework naming of elevator screen widgets

assets/css/v2/bus_eink/screen/normal.scss, assets/css/v2/eink/normal_header.scss, assets/css/v2/gl_eink/screen/normal.scss
**Asana task**: [[extra] bus e-ink header has incorrect appearance on widget endpoint](https://app.asana.com/0/1185117109217413/1209279595523778)
Description
- Fixed issue where header widget height was not being set to 288px
- Removed 288px from the other two spots in bus_eink and gl_eink
Let me know if removing them/putting them here has adverse effects, I tried to check the places that I could but I'm sure I missed places.
=> Moved 288px height to normal_header.scss instead of normal.scss

lib/screens/elevator.ex, test/screens/elevator_test.exs
For some elevators with in-station redundancy, the text "Accessible route available" would incorrectly be shown in the bold font reserved for more noteworthy redundancy categories.
The reason is that we were expecting the redundancy category to be exactly `2`, but some elevators had categories like `2A` or `2B`. Since the individual exiting summaries for category-2 elevators are all "Accessible route available" (which we normally ignore in favor of a hard-coded string that happens to be identical), this resulted in screens still showing the correct phrasing, but more boldly than intended.
**Asana task**: https://app.asana.com/0/1185117109217413/1209314103629054
=> fix: incorrect boldness in elevator outages

lib/screens/v2/screen_data.ex
**Asana task**: Fixing an alert caused by self_refresh_runner captured [here in Sentry](https://mbtace.sentry.io/issues/6300694849/?alert_rule_id=9523677&alert_timestamp=1739566014665&alert_type=email&environment=screens-prod&notification_uuid=dd59eeb0-0ee9-4514-a3b6-850f3f3a6a7d&project=6061747&referrer=alert_email)
Description
=> bugfix: ScreenData API sets default value for query_params for self_refresh_runner

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Custom image for Govt Ctr pre-fare](https://app.asana.com/0/1209229552734401/1209391199110652)
Description
- Replaced suppression of old alert
- This in conjunction with the config changes will effectively replace the Alert with a custom image on the Govt Ctr prefare screens and takeovers for Kenmore and Haymarket on DUP screens
=> Added suppression of alert 623609 for the Green Line diversion

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/widget_instance/alert.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/alerts/alert_test.exs
* The `start` of alert active periods is documented as non-nullable in the V3 API, so we can remove some special cases that assumed it could be null. This logic was unreachable anyway, since `Alerts.Parser` did _not_ have such handling and would have crashed if we ever encountered this situation.
* Remove some redundancy in the active period parsing code.
* Add a test case to cover `Alert.fetch/1` and more of the behavior of `Alerts.Parser`, using more realistic test data.
**Asana task**: https://app.asana.com/0/1185117109217413/1209447170673650
=> refactor: alert parsing and active period handling

assets/css/admin/inspector.scss, assets/src/components/admin/inspector.tsx
* Provide a basic "URL bar" for the inspector iframe, allowing an admin to see and copy the current screen URL.
* Minor refactor to iframe URL building to put all the logic in one place and allow the URL to be used as the key for resetting data controls, fixing potential issues where these might not be reset even when the URL changed.
=> feat(admin): inspector shows current screen URL

assets/css/pre_fare_v2.scss, assets/css/v2/pre_fare/screen_container.scss, assets/css/v2/pre_fare/viewport.scss, assets/src/components/v2/pre_fare/simulation_screen_container.tsx
**Asana task**: [Screenplay renaming / support for layout](https://app.asana.com/0/1185117109217413/1209255549956022)
Description
- These changes fix the cut off duo layout too
=> Added support for Pre-fare Solo layout to the Screenplay simulation

lib/screens/v2/candidate_generator/widgets/reconstructed_alert.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/candidate_generator/widgets/reconstructed_alert_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
In preparation for reconstructed alerts supporting the Pre-Fare solo template, `is_full_screen` is renamed, since this field will no longer directly determine whether an alert is placed in a "full screen" slot. The terminology of a "priority" alert is used instead.
=> refactor: rename ReconstructedAlert field

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_property_test.exs, test/screens/v2/widget_instance/reconstructed_alert_test.exs
`WidgetInstance.ReconstructedAlert` accepted a logging function as a second argument to `serialize`, to allow suppressing warnings in tests. The more conventional way to do this in ExUnit is `CaptureLog`.
* Switch to using `CaptureLog` in these tests (via the `:capture_log` tag which automatically wraps a test case, discarding the log output).
* Only capture logs for the specific cases we expect to log a warning.
* Use our `Report` module so these warnings are also logged to Sentry, proactively alerting us.
=> refactor: more targeted log capturing in tests

assets/src/components/admin/admin_image_manager.tsx, assets/src/util/admin.tsx
**Asana task**: [Fix Screens admin UI image uploads](https://app.asana.com/0/1185117109217413/1209279595523788)
Description
- Seems like previously we were passing FormData all the way through without serializing it and attaching content-type to the headers, in the new code we attempt to stringify + add the content-type of `application/json`
- Added the `formData` function in `fetch` to allow passing data through without trying to serialize it into JSON and attaching a content-type to it
=> Fixed admin image upload failing with 400 error

lib/screens_web/views/v2/audio/elevator_status_view.ex, test/screens_web/views/v2/audio/elevator_status_view_test.exs
**Asana task**: [Clean up phrasing of elevator widget audio on pre-fares](https://app.asana.com/0/1185117109217413/1209294078164616)
Only renders the additional closures messaging if there are actually additional closures. Added a test suite for this module. First elixir PR so let me know if this is the "elixir-y" way to go about this!  I think some of the functional programming mindset is starting to come back to me (I worked on an app in Clojure a looong time ago) :)
=> Clean up phrasing of elevator widget audio on pre-fares

assets/src/components/v2/reconstructed_alert.tsx, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209255549956021
The existing alert widget "hierarchy" of dual screen > single screen > flex zone does not make sense on Pre-Fares that only have one screen to work with. We "adjust" placement for solo screens by moving all alerts down one level in this hierarchy (with some exceptions):
* Alerts that would have been dual-screen are single-screen.
* Alerts that would have been single-screen are (mostly) flex-zone.
* Alerts that would have been in the flex zone stay there.
This reorganizes some of the tests for this widget and adds assertions for solo screens to existing test cases. Initially most of these are placeholders whose main purpose is to ensure we don't crash in any known scenarios.
=> feat: alert widget support for solo Pre-Fares

lib/screens/v2/candidate_generator/widgets.ex
This module contained nothing and has never been referenced anywhere (introduced in 9bb1e3aa).
=> refactor: remove unused module

.github/dependabot.yml
This package is a Webpack plugin and does not align with Babel's major releases, resulting in some odd PRs like #2487 where Dependabot tries to update to a new patch version of `@babel/core` and a new _major_ version of `babel-loader` at the same time. With this line removed, the latter is sorted into the `webpack` group, due to the existing `*-loader` pattern.
=> dev: remove `babel-loader` from Dependabot group

assets/css/v2/pre_fare/viewport.scss, assets/src/components/v2/pre_fare/simulation_screen_container.tsx
**Asana task**: [Pre-fare flex zone is broken in Screenplay](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209673539034709?focus=true)
(correct me if my CSS knowledge is wrong here)
- Seems like we were transforming the div around the widget instead of just the widget, leading to some cut off widgets.
- Moves the transform into the widget itself rather than the surrounding div
- Adds some scaling logic for the solo/duo panels for simulations to prevent unneeded horizontal scrolling
=> Fixed flex zones being cut off in Pre-fare simulations

lib/screens/v2/departure.ex, test/screens/v2/departure_test.exs
**Asana task**: [Don't display bus crowding at first stop on trip](https://app.asana.com/0/1185117109217413/1209411176930017/f)
- Removed checks for `current_status` for vehicle when doing crowding_data checks
Description
=> Suppress crowding data for first stop

assets/css/v2/elevator/closures.scss, assets/css/v2/elevator/normal.scss, assets/src/components/v2/elevator/closures.tsx, config/config.exs, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/widget_instance/elevator_closures.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs
**Asana task**: [No elevator alerts](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1209256677260370?focus=true)
Description
When the elevator alerts array is empty, display the "all elevators working screen." If there is an upcoming outage at the elevator, display that in a smaller bar on top.  One issue -- I wasn't sure how to remove the footer from these screens, or if I should. The mock-ups don't have a footer.
Screenshots added below:
=> UI for the "all elevators working" state

config/config.exs, lib/screens/v2/widget_instance/serializer/route_pill.ex
The Middleborough/Lakeville line is now the Fall River/New Bedford line, with a new route ID (`CR-NewBedford`).
* Add a route pill abbreviation for this line. Remove the abbreviation for the old route ID.
* Remove a DUP headsign abbreviation that only applied to the old line.
* Clean up some old DUP headsign abbreviations from the Orange Line Super Surge.
**Asana task**: https://app.asana.com/0/1185117109217413/1209770072971451
=> fix: support Fall River/New Bedford line

lib/screens/v2/candidate_generator/elevator/closures.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs
Some test assertions using `=` were written with an unpinned variable, causing the variable to be reassigned and therefore unused. We can also cut down on matching some values that are not relevant to the specific test cases in question.
As a separate commit, includes a minor refactor to the no-data logic being tested here:
* Push down an API fetch into the one branch that needs it.
* Push down the no-data conditional logic into the function that generates the only field it affects.
=> test: fix unused variable warnings

.github/workflows/asana.yml
* Add the `edited` event to prompt a task sync if a PR description is edited to add/change an Asana URL.
* Add the `review_requested` event, since the workflow only moves tasks to the in-review column when review has been requested (and CODEOWNERS review requests seem to happen after, and separately from, a PR being opened or moved out of draft).
=> ci: add more trigger events to Asana workflow

assets/src/components/v2/pre_fare_single_screen_alert.tsx, lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
The code previously assumed a station closure alert "here" (at the screen's station) would only be presented as a single-screen takeover if it was a closure of a single route at a transfer station; if an alert eliminated all service at the station, it would be a dual-screen takeover. This assumption is no longer valid with the addition of the "solo" template, which uses a single-screen takeover for anything that would have been a dual-screen takeover on a "duo".
This change enables such "full" station closures to be displayed as a single-screen takeover, with a disruption diagram and text matching the dual-screen version.
**Asana task**: https://app.asana.com/0/1185117109217413/1209255549956020
=> feat: "here" station closures for Pre-Fare solo

lib/screens_web/views/v2/audio/reconstructed_alert_single_screen_view.ex
The serialization for Pre-Fare single-screen station closure alerts now always includes the `unaffected_routes` field even if it is empty. The audio view was not updated to reflect this.
Audio of this scenario before the change (note improper "trains are stopping here" text):
```
<p><s>This is Harvard</s></p>
<p>Red Line trains are skipping this station due to a special event.
Please seek an alternate route.  trains are stopping here as usual.</p>
<p><s>For more information, go to <say-as interpret-as="spell-out">MBTA</say-as> dot com slash <break /> alerts</s></p>
```
and after:
```
<p><s>This is Harvard</s></p>
<p>Attention, Red line riders. This station is closed due to a special event.
Please seek an alternate route. Red Line trains are skipping this station.</p>
<p><s>For more …
```
=> fix: audio view for pre-fare station closures

lib/screens/checks/untestable_datetime.ex
cf0a573 made Credo a dev/test-only dependency, but we have a custom Credo check in the `lib` directory which Elixir will therefore try to compile even in the `prod` environment, [failing because Credo is not loaded there](https://github.com/mbta/screens/actions/runs/14173858612).
We could do something with `elixirc_paths` here (e.g. moving the module to a top-level `lib_dev` directory and only compiling that directory in dev/test), but this change goes the route of simply wrapping the module definition in a `Code.ensure_loaded?` conditional.
=> fix: don't try to compile Credo check in prod

assets/css/v2/bus_shelter/alert.scss, assets/css/v2/bus_shelter/flex/page_indicator.scss, assets/css/v2/bus_shelter/link_footer.scss, assets/css/v2/dup/alert/full_screen_alert.scss, assets/css/v2/dup/departures/destination.scss, assets/css/v2/dup/departures/row.scss, assets/css/v2/dup/departures/time.scss, assets/css/v2/dup/empty_state.scss, assets/css/v2/dup/free_text.scss, assets/css/v2/dup/normal_header.scss, assets/css/v2/lcd_common/departures/destination.scss, assets/css/v2/lcd_common/departures/section.scss, assets/css/v2/lcd_common/departures/time.scss, assets/css/v2/lcd_common/departures_no_data.scss, assets/css/v2/lcd_common/route_pill.scss, assets/css/v2/lcd_common/subway_status.scss, assets/css/v2/pre_fare/cr_departures/cr_departures.scss, assets/css/v2/pre_fare/cr_departures/cr_departures_table.scss, assets/css/v2/pre_fare/cr_departures/overnight_cr_departures.scss, assets/css/v2/pre_fare/departure_time.scss, assets/css/v2/pre_fare/disruption_diagram/disruption_diagram.scss, assets/css/v2/pre_fare/elevator_status.scss, assets/css/v2/pre_fare/flex/paging_indicator.scss, assets/css/v2/pre_fare/prefare_single_screen_alert.scss, assets/css/v2/pre_fare/reconstructed_alert.scss, assets/css/v2/pre_fare/subway_status.scss
There were a lot of CSS files I noticed that used color definitions where we had already defined constants in the `colors` namespace. Went through all the colors defined in the namespace and replaced any instances where we used the same hex code.
=> chore: Use consts defined in colors.scss for all equivalent hex code colors

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/facilities/facility.ex, lib/screens/facilities/parser.ex, lib/screens/stops/parser.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, lib/screens/v2/widget_instance/elevator_status.ex, test/screens/alerts/alert_test.exs, test/screens/facilities/facility_test.exs, test/screens/route_patterns/route_pattern_test.exs, test/screens/v2/candidate_generator/elevator/closures_test.exs, test/screens/v2/candidate_generator/widgets/elevator_closures_test.exs, test/screens/v2/widget_instance/elevator_status_test.exs
* Introduce a `Facility` struct and generic fetch functions for it. Allows replacing the narrower `fetch_stop_for_facility` function with fetching the facility and reading its `stop` relationship.
* Parse facilities related to alerts as the complete `Facility` instead of a map of ID and short name, potentially including relationships of the facilities as well. Allows replacing the special-purpose `fetch_elevator_alerts_with_facilities` with the normal `fetch`, since related facilities are now always included.
* Fix a minor bug in Stop parsing where `connecting_stops` being unloaded was represented as `nil`, rather than `:unloaded` as the typespec suggested.
For now only the `excludes-stop` facility property is parsed. This plus the `stop` relationship will ultimately let us determine the …
=> refactor: fetch and parse Facility resources

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/facilities/facility.ex, lib/screens/facilities/parser.ex, lib/screens/lines/parser.ex, lib/screens/predictions/parser.ex, lib/screens/predictions/prediction.ex, lib/screens/route_patterns/parser.ex, lib/screens/route_patterns/route_direction_stops.ex, lib/screens/route_patterns/route_pattern.ex, lib/screens/routes/parser.ex, lib/screens/routes/route.ex, lib/screens/schedules/parser.ex, lib/screens/schedules/schedule.ex, lib/screens/stops/parser.ex, lib/screens/stops/stop.ex, lib/screens/trips/parser.ex, lib/screens/v2/departure.ex, lib/screens/v3_api/parser.ex, lib/screens/vehicles/parser.ex, lib/screens/vehicles/vehicle.ex, test/screens/alerts/alert_test.exs, test/screens/facilities/facility_test.exs, test/screens/route_patterns/route_pattern_test.exs, test/screens/routes/route_test.exs
Some patterns were repeated across many of our resource parsing modules, including an implicit "API" for passing around included resources. This centralizes the shared logic in a `V3Api.Parser` module.
=> refactor: DRY up V3 API response parsing

assets/package.json
Just a change to the package.json that's been bothering me. Adds the [--list-different option](https://prettier.io/docs/cli#--list-different) so you can easily see what files prettier changed.
=> chore: When running prettier, only log files that have been changed

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, lib/screens/v2/candidate_generator/widgets/elevator_closures.ex, test/screens/alerts/alert_test.exs, test/screens/v2/candidate_generator/elevator/closures_test.exs, test/screens/v2/candidate_generator/widgets/elevator_closures_test.exs
Alert activities are an enum rather than an arbitrary string. Specify them as atoms and document the possible values as a type.
=> refactor: specify alert activities as atoms

lib/screens/facilities/facility.ex, lib/screens/facilities/parser.ex
As with 6bb51f0, these atoms did not reliably "exist", by virtue of only existing in a typespec.
=> fix: facility type atoms not existing

lib/screens/v2/widget_instance/elevator_closures.ex, test/screens/v2/widget_instance/elevator_closures_test.exs
The type of `stations_with_closures` is either a list of stations *or* an atom such as `:no_closures`. The recently introduced `Enum.map/2` did not account for this, so serialization [would always crash](https://mbtace.sentry.io/issues/6529369484/) if the screen was trying to display a "no data" state.
=> fix: elevator screen no-data state serialization

lib/screens/v2/candidate_generator/elevator/closures.ex, test/screens/v2/candidate_generator/elevator/closures_test.exs
Generating elevator screen closures requires, among other things, the ID and name of the elevator's station.
Previously the ID was obtained from the `stop` field of the same `informed_entity` that referenced the elevator (assuming the alerts feed would have to populate this, given "facilities" are a non-standard extension), and the name from a separate API fetch that collected the names of all parent stations in the system.
We can now populate the facilities associated with an alert and the stops associated with those facilities as part of the alert fetch, so this information can be gotten directly from the Stop resources. In particular this removes the need for the separate "station name map" to be fetched, passed around, and stubbed in tests.
Fetching alerts with the full Facility …
=> refactor: use facility stop in elevator closures

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
**Asana task**: [Filter Alert 636777 from Pre Fares](https://app.asana.com/0/1185117109217413/1209929226121665/f)
Description
- https://mbta.slack.com/archives/C039ARUM48H/p1744205951518679
- [This] alert is kind of a weird one-off that may be used by Transit Data to help generate predictions on the Ashmont branch during the "shuttle train" situation, but we don't want it to actually appear
=> Suppress Alert 636777 for Transit Data

assets/src/hooks/v2/use_api_response.tsx, assets/src/util/sentry.tsx
**Asana task**: [Prefare/bus shelter apps collectively making fewer requests](https://app.asana.com/0/1185117109217413/1209235802491489/f)
Description
1. Add sentry logging in cases where we get a failed screen data API request but it hasn't been a minute yet and therefore does not trigger the no-data state
2. Enable offline caching of Sentry events in cases where the screen doesn't have network access when it tries to send the event to sentry. Once the browser is back online, it will retry any cached events before clearing the cache.
Note: Raven doesn't support offline caching out of the box so had to write a custom transport callback and do the caching manually.
New event logged to sentry with `cached` field: https://mbtace.sentry.io/issues/6469468736/?project=6061747&query=&referrer=iss …
=> Enable offline caching of Sentry events

.github/actions/setup/action.yml, .github/workflows/ci.yml
Because we only had CI running on `pull_request`, it was never actually running on the main branch, which is the only branch whose caches other branches are allowed to use. This resulted in builds on feature branches slowing down as the main cache became progressively less usable due to dependency changes.
Also includes a small improvement to the caching logic as a separate commit; see commit message.
=> ci: fix caches never being populated on main

lib/screens/facilities/facility.ex, lib/screens/route_patterns/route_pattern.ex, lib/screens/v2/candidate_generator/elevator/closures.ex, test/screens/facilities/facility_test.exs, test/screens/route_patterns/route_pattern_test.exs, test/screens/v2/candidate_generator/elevator/closures_test.exs
Reintroduces hand-authored exiting summaries for closed elevators with redundancy that requires travel outside their station (e.g. "Exit at Harvard, request shuttle bus back to Davis"). This involves determining whether a rider looking at a given elevator screen could encounter a given closed elevator, if they traveled to its station from where they are and attempted to exit that station.
For now, this does not take transfers into account: a custom exiting summary only appears when the closed elevator is on the same line as the elevator screen.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209537234084964
The below test screen is associated with elevator 804 at Park Street station. From here, the Heath Street platform at Prudential station is …
=> feat: downstream elevator closure summaries

lib/screens/v2/candidate_generator/elevator/closures.ex
Due to a quirk of our data, shuttle bus stops that are considered child stops of the parent stations they "replace" are incorrectly implied to be served by elevators within the parent station. As a result, shuttle bus route patterns (which have some stops with no parent station) ended up in our "downstream" elevator closures logic (which assumed all stops would have a parent station).
We did not need to match on the full structure of the stop in this case, so it can be simplified.
=> fix: crash in elevator screen logic

lib/screens_web/views/v2/audio/cr_departures_view.ex
The previous audio unconditionally referred to e.g. "Red Line delays" and claimed the Commuter Rail was "free of charge", even when neither of these were the case. This now correctly takes the `is_free` config field into account and changes the audio to align more closely with the visual presentation.
There are no existing tests for this view — due to the small scope of this change and CR Departures being a "legacy" widget we don't expect to change much before it is ultimately replaced, this change was manually tested using the admin inspector rather than the heavier lift of adding automated tests.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209294078164618
=> chore: clean up audio on CR Departures widget

assets/css/v2/bus_eink/departures/time.scss, assets/css/v2/dup/departures/time.scss, assets/css/v2/gl_eink/departures/time.scss, assets/css/v2/lcd_common/departures/time.scss, assets/css/v2/on_bus/time.scss, assets/css/v2/pre_fare/departure_time.scss
**Asana task**: [Use tabular figures for departures on screens](https://app.asana.com/1/15492006741476/project/1208877354406742/task/1206945324796523?focus=true)
=> [chore] Add tabular-nums to departure time CSS classes

lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
* Fixes a gap in the logic where if a rotation's configured stops were served by at least one route, but no departures (or headways) were currently available, a "blank" departures widget would be displayed. This scenario now correctly generates a `NoDataSection`.
* Only consolidate rotations that consist entirely of `NoDataSection`s into a `DeparturesNoData` widget if this is true of *all* rotations. The presentation of `DeparturesNoData` is very generic and suggests something is wrong with our data or the screen's connection, when in reality we may have succeeded in fetching data and simply have no departures to show right now. `NoDataSection` at least has a route icon indicating which "mode" we don't have data for, so this is more informative when e.g. one rotation has subway departures …
=> fix: DUP departures no-data states

lib/screens/alerts/alert.ex, lib/screens/routes/route.ex, lib/screens/schedules/schedule.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/vehicles/vehicle.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
When no sections were configured for DUP secondary departures, the secondary rotation would be a copy of the primary departures. This extends that behavior to also occur when sections *are* configured but there are currently no departures to display. The primary use case is DUPs that display subway (primary) and bus (secondary) departures, where the relevant bus stops have no service on weekends.
Also restructure logic to reduce redundant data fetching, and add some typespecs.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210098606381697
=> feat: DUP secondary departures no-data fallback

assets/css/admin.scss, assets/src/components/admin/admin_image_manager.tsx, assets/src/util/admin.tsx, lib/screens/image.ex, lib/screens/util/assets.ex, lib/screens_web/controllers/admin_api_controller.ex, lib/screens_web/controllers/screen_controller.ex, lib/screens_web/router.ex
A recent motivation for [making files in the assets bucket public by default](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209486399971517) was that we often forgot to add the `public-read` ACL when manually uploading line map images. However, the admin UI already includes a file manager that allows uploading images to S3 and sets the correct ACL automatically; it's just limited to a specific prefix. This PR is a quick diversion into the idea of removing that limitation, and sprucing up the experience a bit while we're here.
👉 [Try it out on dev-green!](https://screens-dev-green.mbtace.com/admin/image-manager)
* The Image Manager can now manage all objects under the environment's `images/` prefix, rather than only in `images/psa/`. When uploading an image, admins …
=> feat: admin image manager improvements

lib/screens/v2/widget_instance/departures.ex, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [Wayfinding sub-headers in departures sections](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209972434938244?focus=true)
- Adds the subheader to the departures widget audio readout value when present
=> feat: Include subtitle in departures header audio readout

lib/screens/v2/candidate_generator/widgets/departures.ex
Previously, *whether* to perform the `bidirectional` logic was also handled by this function's pattern-matching, in a way that also covered the empty list:
```
defp make_bidirectional([first | rest], true), do: # ...
defp make_bidirectional(departures, _enabled), do: departures
```
In c18c8bf this condition was moved elsewhere and the second argument removed, leaving the only pattern for departures to match as `[first | rest]`, which crashes when there are no departures.
=> fix: `bidirectional` crash with no departures

lib/screens/v2/candidate_generator/dup/alerts.ex
**Asana task**: [Investigate Sentry report volume](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210072157534313?focus=true)
When the `stop_id` for Alerts is set to nil, the `LocationContext.fetch` call throws an error. We want to return an empty list from the `Alerts` fetcher before that method is ever called. 
Notes on implementation:
- This nil stop_id case is only relevant for the DUPs alert fetcher at present. 
- I included in the function instead of breaking out into a separate pattern matched function header b/c that ended up being cleaner and more concise with the default values being set.
=> bugfix: Add nil stop_id check into DUP alerts fetcher

lib/screens_web/views/v2/audio/elevator_status_view.ex
In 7f1b1445 we replaced existing instances of `mbta.com/alerts/access` with the preferred URL `mbta.com/elevators`, but missed this one.
=> fix: use correct URL for elevator status audio

lib/screens/v2/candidate_generator/pre_fare.ex, lib/screens/v2/widget_instance/audio_only/alerts_intro.ex, lib/screens/v2/widget_instance/audio_only/content_summary.ex, test/screens/v2/candidate_generator/pre_fare_test.exs, test/screens/v2/widget_instance/audio_only/alerts_intro_test.exs, test/screens/v2/widget_instance/audio_only/content_summary_test.exs
The `ContentSummary` and `AlertsIntro` audio-only widgets both had logic that prevented their inclusion when the screen had widgets in "takeover" slots, but these checks were duplicated and had drifted out of sync with regard to slot names. This moves the logic into the main candidate generator so it can be done in one place.
---
- https://app.asana.com/0/0/1210237684564486
=> fix: Pre-Fare audio consistency with takeovers

assets/src/components/v2/subway_status/eink_subway_status.tsx, assets/src/components/v2/subway_status/lcd_subway_status.tsx, lib/screens/v2/widget_instance/subway_status.ex, lib/screens_web/views/v2/audio/subway_status_view.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Asana task**: [Modify Subway Status logic to match website widget](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209950740101100?focus=true)
Description
Changed mbta.com/alerts to mbta.com/status for SubwayStatus widgets
Let me know if I missed any places, I know there a few places where we might concat the actual URL but I couldn't 100% find them.
=> Changed mbta.com/alerts to mbta.com/status for SubwayStatus widgets

lib/screens_web/views/v2/audio/departures_view.ex, test/screens_web/views/v2/audio/departures_view_test.exs
**Asana task**: [Fix pronunciation of bus berths on screen audio](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210077353559487?focus=true)
Description
Unfortunately, wrapping the berth identifier in a single SSML `say-as` tag and indicating to pronounce it as an address or any other option still results in the pronounciation "ah-two" or "ay tee double u oh".
The best option I could find was adding a slight break between "Berth" and the identifier to improve clarity, and then only specifying to "spell-out" the letter.
=> Fix bus berth pronounciation

lib/screens/v2/candidate_generator/widgets/subway_status.ex, lib/screens/v2/widget_instance/subway_status.ex, test/screens/v2/widget_instance/subway_status_test.exs
**Asana task**: [Modify Subway Status logic to match website widget](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1209950740101100?focus=true)
Description
- match the website subway status by allowing service_change alerts with severity > 3 to appear on the widget
- there will be a separate PR coming up shortly for switching mbta.com/alerts to mbta.com/status
=> Modify Subway Status logic to match website widget

assets/src/components/admin/admin_form.tsx, assets/src/components/admin/admin_screen_config_form.tsx, assets/src/components/admin/inspector.tsx
The Config Editor and the "single-screen" editor used in the Inspector no longer reload the entire page when the config is updated. This was mostly unnecessary and even counter-productive in the Inspector, since the reloaded screen would most likely be built from the pre-update cached copy of the config, requiring a second manual reload after a few seconds to allow the cache to update.
Also add a reload button to the Inspector to allow manually reloading only the screen iframe, so the current zoom level is retained.
=> feat(admin): don't reload page on config update

lib/screens/v2/location_context.ex
Fixes an issue introduced in 4efc67d8 where fetching data would crash for Bus Shelter and GL E-ink screens.
=> fix: crash fetching location context

lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Asana task**: [Investigate Kendall DUP evening bus issue](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210196927622064?focus=true)
In the example of the bug shown in the ticket, this occurred because only 2/3 routes shown on this section of the Kendall DUP was in overnight mode. However, there was still one bus that had trips scheduled for later in the night.
To solve this, I added a check that there are as many overnight trips as there are total routes available.
This also changes, and I believe improves, the following case
- When there are no trips scheduled for the next day, as in the case of the Kendall buses on Friday, then we will show a duplicate of the `primary_departures` screen instead of an Overnight screen
=> bugfix: Only show overnight screen on DUP if every route in the section is overnight

lib/screens/v2/departure.ex, lib/screens/v2/departure/builder.ex, test/screens/v2/departure/builder_test.exs, test/screens/v2/departure_test.exs
This issue was partly addressed in ee539a3, but the fix was inadvertently only applied to the case where scheduled departures were being displayed; the "predictions only" code path still had the issue.
This fixes the issue more systematically by removing the separate "predictions only" code path entirely. All departure fetching now goes through the same logic; in the case where only predictions are fetched, the schedule-related logic is a no-op.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210392853396720?focus=true
=> fix: filter out skipped/cancelled predictions

docs/tech_specs/dup_v2_alert_widget_backend.md, lib/screens/alerts/informed_entity.ex, lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Asana task**: [DUP screens: Omit no-data section if an alert is present](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210227886153331?focus=true)
This essentially adds logic to not show a `NoDataSection` for routes with closure alerts for all routes in section
Some pieces to note: 
- This is not explicitly tied to the alerts widget, since those candidate generators run in parallel. However, if we have no departures for a given section and alerts tied to each, it's a fair assumption that we don't want to show a `NoDataSection` regardless.
- In this alerts scenario, behavior on the FE depends on the number of routes in a section, but returning an empty list of departures works for both:
- If a page contains only one section of routes and they are closed, the …
=> feat: Omit no-data section if an alert is present

lib/screens/v2/widget_instance/reconstructed_alert.ex, test/screens/v2/widget_instance/reconstructed_alert_test.exs
This alert is a "mixed" shuttle/suspension represented in the data as only a suspension, so ReconstructedAlert content will not give the full picture. We will instead be scheduling custom content on Pre-Fares.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210534397902318
=> chore: suppress ReconstructedAlerts for 645336

lib/screens/alerts/informed_entity.ex, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/candidate_generator/dup/departures.ex, test/screens/v2/candidate_generator/dup/departures_test.exs
**Asana task**: [DUP "omit no-data with alerts" feature not working](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210675381138609?focus=true)
Fixes the DUP handling of the No Data Section when there are active alerts. 
- Root cause of the issue was that the stubbed `Informed Entity` values I used for testing had the route as a struct, when this is supposed to just be a string, the `route_id`. You can see this modified data in the unit test and how this was testing the code with incorrect data.
- Reordered so that the Alert handling comes before Overnight section logic. This Overnight check could be true for an alert case, i.e. if there is a suspension for the rest of the day and thus nothing scheduled until tomorrow. In this case, we still want return an empty …
=> bugfix: Hide DUP's NoDataSection during alerts, match IE route with section's route properly

assets/css/v2/lcd_common/normal_header.scss
On `lcd_common` screens (Bus Shelter, Sectional, Pre-Fare), headers with text long enough to trigger the "small" sizing and run onto two lines were awkwardly positioned.
| Before | After |
|---|---|
| <img width="1080" height="200" alt="Screen Shot 2025-07-18 at 15 00 03" src="https://github.com/user-attachments/assets/8e9a5315-3cb6-4a7b-b58f-2a80379cc8b3" /> | <img width="1080" height="200" alt="Screen Shot 2025-07-18 at 15 01 11" src="https://github.com/user-attachments/assets/5b143cec-ffe2-4f9d-b16a-d432482805a6" /> |
=> fix: positioning of long headers on `lcd` screens

lib/screens/alerts/alert.ex, lib/screens/alerts/parser.ex, lib/screens/v2/candidate_generator/widgets/subway_status.ex, lib/screens/v2/widget_instance/dup_alert/serialize.ex, lib/screens/v2/widget_instance/reconstructed_alert.ex, lib/screens/v2/widget_instance/subway_status.ex, lib/screens_web/views/v2/audio/reconstructed_alert_single_screen_view.ex, lib/screens_web/views/v2/audio/subway_status_view.ex, test/screens/v2/widget_instance/subway_status_test.exs
Most widgets technically already support single-tracking alerts since these have an effect of `DELAY`. However, where possible we want to:
1. call out that these are "due to single tracking"
2. show them regardless of severity, allowing "informational" alerts
This change adds these aspects to the Subway Status widget.
---
Includes several distinct but related commits, best reviewed per-commit.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210764886971057
=> Single-tracking messaging for Subway Status

config/test.exs, lib/screens/v2/candidate_generator/dup/alerts.ex, lib/screens/v2/widget_instance/dup_alert.ex, lib/screens/v2/widget_instance/dup_alert/serialize.ex, test/screens/v2/widget_instance/dup_alert_test.exs, test/screens/v2/widget_instance/dup_special_case_alert_test.exs
Most widgets technically already support single-tracking alerts since these have an effect of `DELAY`. However, when the cause of a delay is single-tracking specifically, we want to make this info more prominent, including showing the alert at severity levels we otherwise wouldn't. This updates the handling of DUP alerts accordingly.
---
Includes several distinct but related commits, best reviewed per-commit.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210603551669549
=> Single-tracking messaging for DUP Alerts

lib/screens/v2/candidate_generator/dup/departures.ex
**Asana task**: [Investigate: DUPs showing "overnight" departures incorrectly](https://app.asana.com/1/15492006741476/project/1208877354406742/task/1210559658847355?focus=true)
To fix the incorrect overnight times being shown on DUPs, this passes the param to the v3 API to sort departures by ascending order time. This ensures that the first/last schedule of today and first schedule of tomorrow that are found are all correct.
=> Sort overnight schedules in DUPs departures

assets/css/colors.scss, assets/css/lcd_free_text.scss, assets/css/v2/dup/departures/route_pill.scss, assets/css/v2/dup/free_text.scss, assets/css/v2/lcd_common/route_pill.scss, assets/css/v2/pre_fare/free_text.scss, assets/src/components/v2/departures/route_pill.tsx, assets/src/components/v2/free_text.tsx
**Asana task**: [Add CapeFlyer ocean blue color to FE](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211026247678603?focus=true)
Adding this new color to the Frontend will allow Outfront to deploy this new code so that we can use it on the backend.
=> feat: add CapeFlyer ocean blue color to FE

lib/screens/headways.ex, test/screens/headways_test.exs
When a DUP was configured with secondary bus departures, and on the "boundary" of an active alert for the subway route in primary departures, the secondary sections would incorrectly display headway messages for the subway route instead of the (still present) bus departures.
This issue was introduced in 6986ffb and caused by an incorrect implementation of headway key lookups, where if a station didn't have any transfers to other subway routes, it was assumed that the station served no other routes at all (including e.g. bus routes).
This updates the behavior of headway lookups to be more conservative, fixing the issue but with the side effect that sections not configured with an explicit route ID filter will never show headways.
**Asana task**: …
=> fix: DUP subway headways appearing in bus sections

lib/screens/routes/parser.ex, lib/screens/routes/route.ex, lib/screens/v2/candidate_generator/widgets/departures.ex, test/screens/route_patterns/route_pattern_test.exs, test/screens/routes/route_test.exs, test/screens/v2/candidate_generator/widgets/departures_test.exs
When configuring departures, we sometimes use a pattern where each direction of service gets its own dedicated section. When this is the case, and (only) one direction has no departures available, this meant live predictions were confusingly preceded/followed by a "no departures available" message using the same route pill — the screen apparently contradicting itself.
Improve support for this scenario by including a direction name in the no-data message of "directional" sections.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210825667877923
=> fix: improve directional no-data messages

test/screens/v2/screen_data_test.exs
This has been a minor annoyance for a while, but so minor it wasn't worth the equally minor effort of fixing it. I have spare time and this just failed a main branch build again, though, so it has Failed Me For The Last Time™.
=> test: increase timeout in flaky test

lib/screens/headways.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/widget_instance/departures.ex, test/screens/headways_test.exs, test/screens/v2/candidate_generator/dup/departures_headway_test.exs, test/screens/v2/candidate_generator/dup/departures_test.exs, test/screens/v2/widget_instance/departures_test.exs
**Asana task**: [Update how headway logic works on DUPs](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210911817494842?focus=true)
Description
Previously, Headway Mode would only work if there was an associated alert at the particular station.
The new changes keep the old terminal alert headway logic (along with the directional headsigns), but also checks if there are no departures, no alerts, and we're not in an overnight period and shows Headway Mode in this flow as well. This enables Headway Mode to show in cases where we have suppressed predictions at certain stations. 
Along with these display logic changes, direction_name is now being parsed from the V3 API and has been added as the headsign in cases where we have sections configured with a direction_id. This …
=> DUP Headway Logic Update

config/config.exs, lib/screens/alerts/alert.ex, lib/screens/stops/stop.ex, lib/screens/telemetry.ex, lib/screens/v2/candidate_generator/dup.ex, lib/screens/v2/candidate_generator/dup/departures.ex, lib/screens/v2/candidate_generator/dup_new.ex, lib/screens/v2/location_context.ex
This method of sending telemetry was regularly overloading the Splunk log handler and causing more important logs to be dropped (in particular DeviceMonitor, which we rely on for alerting us to screen outages). We have not actually used these log spans to investigate anything in a long time, so we'll remove them until we may need them again.
---
- https://app.asana.com/0/0/1211123747782268
=> chore: disable unneeded telemetry logging

assets/css/v2/dup/departures/route_pill.scss, assets/src/components/v2/departures/route_pill.tsx
- Added the small modifier for route-pill__text
- Had to change the size modifiers logic to check explicitly for TR text
**Asana task**: [Adjust font size for 2-digit CR Track Pills](https://app.asana.com/1/15492006741476/project/1185117109217422/task/1211138992434689?focus=true)
=> Decreased font size for DUP route pills text length > 3

lib/screens_web/views/v2/audio/reconstructed_alert_single_screen_view.ex
c945169 fixed an issue where audio readouts for Pre-Fare takeover alerts did not include the cause of an alert (e.g. "maintenance") as intended. This fix included a bug of its own where the phrase "due to" was not included as it should have been (e.g. "due to maintenance"). This fixes that bug.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211213524218569
=> fix: missing "due to" in Pre-Fare alert audio

lib/screens/v2/candidate_generator/dup/alerts.ex, test/screens/v2/candidate_generator/dup/alert_test.exs
**Asana task**: [DUP Info Level Single Tracking Alerts](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211229715108431?focus=true)
Description
- For informational severity alerts for single tracking, we now omit the alert banner
=> DUP removed banner for single tracking information alert

assets/css/v2/lcd_common/normal_header.scss
When the logo was enabled on a Sectional screen, the header was not aligned correctly. This is a recent regression introduced when these styles were refactored for cross-screen-type consistency.
| Bug | Fixed |
| :--: | :--: |
| <img width="1080" height="200" alt="Screen Shot 2025-09-15 at 11 32 36" src="https://github.com/user-attachments/assets/521d71c8-e5fc-48f1-be5c-a89fb7d9b53c" /> | <img width="1080" height="200" alt="Screen Shot 2025-09-22 at 13 40 04" src="https://github.com/user-attachments/assets/01fb77f4-7ada-4b8b-a8e7-520612238ab2" /> |
=> fix: bad header alignment with logo enabled

lib/screens/predictions/prediction.ex, lib/screens/v2/departure.ex, lib/screens/v2/departure/builder.ex, test/screens/v2/departure/builder_test.exs
**Asana task**: [[Investigation] CR Test Alerts > Screenplay dev-green Displays](https://app.asana.com/1/15492006741476/project/1185117109217413/task/1210793900723819?focus=true)
- For Commuter Rail Alerts, we weren't taking into consideration the cancelled/skipped prediction when showing the scheduled departure
- New logic moves some of the relevancy checks to after we combine the predictions and scheduled departures, to allow for proper cross checking of scheduled trips to predicted trips
- Also removed a departure_time nil check within the Prediction fetch, which will allow us to properly get all predictions within the Builder
=> Fixed issue where CR alerts weren't hiding appropriate departures

priv/dup-app.html
Just a small change I needed to make while testing an updated DUP package because of the earlier change to remove v2 from the naming in this app.
=> fix: Remove v2 from dup-app.html

lib/screens/alerts/alert.ex, test/screens/alerts/alert_test.exs
The fix to "alert direction" logic in 31bd15d introduced a regression when dealing with whole-route alerts, or in general, alerts that do not affect any specific parent stations. Improve this logic so it does not crash and gives the answer we want in more scenarios.
**Asana task**: https://app.asana.com/1/15492006741476/project/1185117109217413/task/1211563800336573
=> fix: Pre-Fare crash on whole-route alerts
